import type { EngineData } from '../types';

export const accountingCorporateEngine: EngineData = {
  category: 'accounting-corporate',
  title: 'Accounting & Corporate Finance',
  description: 'Financial statements analysis, business valuation, corporate structures, ratio analysis, and corporate finance fundamentals.',
  topics: [
    {
      name: 'Financial Statements Analysis',
      description: 'Reading and interpreting the three core financial statements to assess business health.',
      details: [
        'The three core financial statements: Income Statement (P&L), Balance Sheet, and Cash Flow Statement — together they tell the full story of a business',
        'Income Statement: Revenue - COGS = Gross Profit - Operating Expenses = Operating Income (EBIT) - Interest & Taxes = Net Income',
        'Revenue recognition: GAAP/IFRS rules dictate when revenue can be recorded. Accrual basis (when earned) vs. cash basis (when received)',
        'COGS (Cost of Goods Sold): Direct costs attributable to producing goods/services. Gross Margin = (Revenue - COGS) / Revenue',
        'Operating Expenses: SG&A (Selling, General & Administrative), R&D, Depreciation & Amortization. Operating Margin = EBIT / Revenue',
        'Balance Sheet: Assets = Liabilities + Shareholders\' Equity. A snapshot of financial position at a point in time',
        'Current Assets: Cash, accounts receivable, inventory, short-term investments — convertible to cash within 1 year',
        'Non-Current Assets: Property, Plant & Equipment (PP&E), intangible assets, goodwill, long-term investments',
        'Current Liabilities: Accounts payable, short-term debt, accrued expenses, current portion of long-term debt',
        'Shareholders\' Equity: Share capital + Retained earnings + Reserves. Represents owners\' claim on assets after all liabilities are paid',
        'Cash Flow Statement: Operating (core business), Investing (capex, acquisitions), Financing (debt, equity, dividends)',
        'Free Cash Flow (FCF) = Operating Cash Flow - Capital Expenditures. The cash available for distribution to stakeholders',
        'Horizontal analysis: compare line items across periods (year-over-year growth rates)',
        'Vertical analysis: express each line item as a percentage of a base (revenue for P&L, total assets for balance sheet)',
        'Common-size statements: converting to percentages for easy comparison across companies of different sizes',
      ],
      subtopics: [
        {
          name: 'Indian Accounting Standards',
          description: 'India-specific accounting standards and financial reporting requirements.',
          details: [
            'Ind AS (Indian Accounting Standards): converged with IFRS, mandatory for listed companies and large unlisted companies (net worth ≥₹250 Cr)',
            'Schedule III of Companies Act 2013: prescribes the format for Balance Sheet and P&L of Indian companies',
            'GST impact on financial statements: Input tax credit on balance sheet, GST collected/payable as current liability',
            'MCA (Ministry of Corporate Affairs) filings: Annual return (MGT-7), financial statements (AOC-4), director reports',
            'Auditing in India: Statutory audit mandatory for all companies. Tax audit under Section 44AB for businesses with turnover >₹1 Cr',
            'ICAI (Institute of Chartered Accountants of India): sets accounting and auditing standards for India',
          ],
        },
      ],
    },
    {
      name: 'Financial Ratio Analysis',
      description: 'Key financial ratios for evaluating company performance, health, and valuation.',
      details: [
        'Profitability Ratios — measure ability to generate profit relative to revenue, assets, or equity',
        'Gross Margin = Gross Profit / Revenue. Industry-specific: software (70-80%), retail (25-35%), manufacturing (30-50%)',
        'Operating Margin (EBIT Margin) = Operating Income / Revenue. Shows operational efficiency excluding financing/tax decisions',
        'Net Profit Margin = Net Income / Revenue. Bottom-line profitability after all expenses',
        'ROE (Return on Equity) = Net Income / Shareholders\' Equity. Measures return on owners\' investment. Healthy: 15%+',
        'ROA (Return on Assets) = Net Income / Total Assets. Measures how efficiently assets generate profit',
        'ROCE (Return on Capital Employed) = EBIT / (Total Assets - Current Liabilities). Popular in India for capital-intensive companies',
        'DuPont Analysis: Breaks ROE into 3 components — Profit Margin × Asset Turnover × Financial Leverage. Diagnoses drivers of ROE',
      ],
      subtopics: [
        {
          name: 'Liquidity & Solvency Ratios',
          description: 'Ratios measuring short-term liquidity and long-term solvency.',
          details: [
            'Current Ratio = Current Assets / Current Liabilities. Healthy: 1.5-3.0. Below 1.0 signals liquidity risk',
            'Quick Ratio (Acid Test) = (Current Assets - Inventory) / Current Liabilities. More conservative; excludes illiquid inventory',
            'Cash Ratio = Cash & Equivalents / Current Liabilities. Most conservative liquidity measure',
            'Debt-to-Equity Ratio = Total Debt / Shareholders\' Equity. Higher ratio = more leverage. Varies by industry',
            'Interest Coverage Ratio = EBIT / Interest Expense. Should be >3x for comfort. Below 1.5x is dangerous',
            'Debt Service Coverage Ratio (DSCR) = Net Operating Income / Total Debt Service. Banks require >1.25x for loans',
          ],
        },
        {
          name: 'Efficiency & Valuation Ratios',
          description: 'Ratios measuring operational efficiency and market valuation.',
          details: [
            'Inventory Turnover = COGS / Average Inventory. Higher = faster inventory conversion. Varies widely by industry',
            'Receivables Turnover = Revenue / Average Accounts Receivable. Days Sales Outstanding (DSO) = 365 / Receivables Turnover',
            'Payables Turnover = COGS / Average Accounts Payable. Days Payable Outstanding (DPO) = 365 / Payables Turnover',
            'Cash Conversion Cycle = DSO + DIO - DPO (Days Inventory Outstanding + Days Sales Outstanding - Days Payable Outstanding). Lower is better',
            'Asset Turnover = Revenue / Total Assets. Measures efficiency of asset utilization',
            'P/E Ratio = Market Price / EPS. Forward P/E uses estimated future earnings. PEG ratio adjusts P/E for growth rate',
            'EV/EBITDA = Enterprise Value / EBITDA. Preferred over P/E for comparing companies with different capital structures',
            'Price-to-Book (P/B) = Market Price / Book Value per Share. Below 1.0 may indicate undervaluation (or impaired assets)',
          ],
        },
      ],
    },
    {
      name: 'Business Valuation',
      description: 'Methods for determining the economic value of a business or company.',
      details: [
        'DCF (Discounted Cash Flow): Project future free cash flows, discount at WACC to present value. Most theoretically sound method',
        'WACC (Weighted Average Cost of Capital) = (E/V × Re) + (D/V × Rd × (1-T)). The blended cost of equity and debt financing',
        'Terminal Value: Value of all future cash flows beyond the projection period. Gordon Growth Model: FCF × (1+g) / (WACC-g)',
        'Comparable Company Analysis (Comps): Value a company using multiples (P/E, EV/EBITDA, P/S) from similar public companies',
        'Precedent Transaction Analysis: Value based on multiples paid in recent M&A deals for similar companies',
        'Asset-Based Valuation: Company value = Fair Market Value of Assets - Liabilities. Used for asset-heavy or distressed companies',
        'Book Value vs. Market Value: Book value reflects historical cost; market value reflects current economic worth',
        'Dividend Discount Model (DDM): Stock Price = Dividend / (Required Return - Growth Rate). Works for stable dividend-paying companies',
        'Sum-of-the-Parts Valuation: Value each business segment separately and sum them. Used for conglomerates and holding companies',
        'Rule of Thumb valuations: Small businesses often valued at 2-5x annual earnings or 0.5-2x annual revenue depending on industry',
        'Valuation in India: SEBI-registered merchant bankers perform valuations for M&A, IPOs, and corporate restructuring',
      ],
      subtopics: [
        {
          name: 'Startup & Private Company Valuation',
          description: 'Valuation methods specific to startups and private companies.',
          details: [
            'Pre-money vs. Post-money valuation: Pre-money = value before investment. Post-money = pre-money + new investment amount',
            'Venture Capital Method: Estimate exit value, discount back by target IRR to determine current value',
            'Scorecard Method: Adjust comparable average valuation by factors (team, market size, product, competition)',
            'Berkus Method: Assign up to $500K for each milestone — idea, prototype, team, strategic relationships, revenue',
            'Revenue multiples for Indian startups: SaaS (8-15x ARR), fintech (5-10x), e-commerce (1-3x), D2C (2-5x)',
            'Liquidation preference and equity dilution: critical for founders to understand before accepting VC funding',
          ],
        },
      ],
    },
    {
      name: 'Corporate Structures & Entity Types',
      description: 'Business entity types and their tax, liability, and operational implications.',
      details: [
        'Sole Proprietorship: Simplest structure, owner and business are one entity. Unlimited personal liability. Income taxed as personal income',
        'Partnership: Two or more people share ownership. General partners have unlimited liability. LLP (Limited Liability Partnership) protects partners',
        'LLP in India: Governed by LLP Act 2008. Partners\' liability limited to agreed contribution. No minimum capital requirement. Popular for professionals (CAs, lawyers)',
        'Private Limited Company (India): Most popular structure for startups. Limited liability, 2-200 shareholders, cannot raise capital from public',
        'Public Limited Company (India): Can raise capital from public via stock exchange listing. Minimum 7 shareholders, 3 directors. Heavier compliance burden',
        'One Person Company (OPC — India): Single owner, limited liability. Suitable for solo entrepreneurs. Converts to Pvt Ltd if turnover exceeds ₹2 Cr',
        'LLC (Limited Liability Company — US): Combines pass-through taxation with limited liability. Most popular structure for US small businesses',
        'S-Corporation (US): Pass-through taxation (no double taxation), limited to 100 shareholders, only one class of stock',
        'C-Corporation (US): Standard corporate structure. Separate tax entity — profits taxed at corporate rate AND dividends taxed at individual rate (double taxation)',
        'Section 8 Company (India) / 501(c)(3) (US): Non-profit entities. Tax-exempt status. Must reinvest surplus for stated objectives',
        'HUF (Hindu Undivided Family — India): Unique Indian entity for joint family property. Separate PAN, separate tax slab. Useful for tax planning',
        'Choosing entity type: Consider liability protection, tax efficiency, funding needs, compliance burden, and future exit plans',
      ],
      subtopics: [
        {
          name: 'Corporate Governance',
          description: 'Rules and practices for directing and controlling companies.',
          details: [
            'Board of Directors: Elected by shareholders to oversee management. Independent directors provide unbiased oversight',
            'SEBI LODR requires at least 1/3 independent directors for listed companies. Chairperson must be non-executive',
            'Audit Committee: Mandatory for listed companies. Oversees financial reporting, internal controls, and auditor appointment',
            'Companies Act 2013 (India): Mandates CSR spending (2% of net profit for companies with NW >₹500 Cr or turnover >₹1000 Cr)',
            'Sarbanes-Oxley (SOX) compliance (US): CEO/CFO must certify financial statements. Internal controls over financial reporting (ICFR)',
            'Annual General Meeting (AGM): Shareholders approve financial statements, dividends, auditor appointment, director elections',
          ],
        },
      ],
    },
    {
      name: 'Corporate Finance Fundamentals',
      description: 'Key corporate finance concepts including capital structure, cost of capital, and capital budgeting.',
      details: [
        'Capital Structure: The mix of debt and equity used to finance a company. Optimal structure minimizes WACC',
        'Modigliani-Miller Theorem: In a perfect market, capital structure doesn\'t affect firm value. In reality, tax benefits of debt matter',
        'Cost of Equity (Re): Estimated using CAPM: Re = Rf + β(Rm - Rf). Risk-free rate + beta × equity risk premium',
        'Cost of Debt (Rd): Interest rate on debt, adjusted for tax benefit: After-tax Rd = Rd × (1 - Tax Rate)',
        'Capital Budgeting: Evaluating whether long-term investments (projects, equipment, expansion) create value',
        'NPV (Net Present Value): Sum of present values of all cash flows (including initial investment). Positive NPV = value-creating project',
        'IRR (Internal Rate of Return): Discount rate that makes NPV = 0. Accept projects where IRR > cost of capital',
        'Payback Period: Time to recover initial investment. Simple but ignores time value of money and cash flows after payback',
        'Working Capital Management: Managing current assets and liabilities to ensure liquidity. WC = Current Assets - Current Liabilities',
        'Dividend Policy: How much profit to distribute vs. retain. Dividend payout ratio = Dividends / Net Income',
        'Share Buyback: Company repurchases its own shares. Reduces share count, increases EPS. Alternative to dividends for returning cash',
        'M&A (Mergers & Acquisitions): Horizontal (same industry), vertical (supply chain), conglomerate (unrelated). Synergies, due diligence, integration',
      ],
      subtopics: [
        {
          name: 'Working Capital & Treasury Management',
          description: 'Managing short-term financial operations and cash optimization.',
          details: [
            'Cash management: Maintain optimal cash balance — enough for operations but not idle. Invest surplus in liquid mutual funds or FDs',
            'Receivables management: Credit policy, collection procedures, aging analysis. Offer early payment discounts (2/10 net 30)',
            'Inventory management: JIT (Just-in-Time), EOQ (Economic Order Quantity). Excess inventory ties up capital; too little risks stockouts',
            'Payables management: Negotiate favorable payment terms. Use trade credit as a source of short-term financing',
            'Cash flow forecasting: Weekly/monthly projections of inflows and outflows. Essential for avoiding cash crunches',
            'Treasury operations: Foreign exchange management, interest rate hedging, bank relationship management, surplus fund investment',
          ],
        },
      ],
    },
  ],
  keyTerms: [
    { term: 'EBITDA', definition: 'Earnings Before Interest, Taxes, Depreciation & Amortization. A proxy for operating cash flow, widely used in valuation multiples.' },
    { term: 'Free Cash Flow (FCF)', definition: 'Cash generated by operations minus capital expenditures. The cash available to pay dividends, reduce debt, or reinvest.' },
    { term: 'WACC', definition: 'Weighted Average Cost of Capital. The blended rate of return required by all capital providers (debt and equity).' },
    { term: 'ROE', definition: 'Return on Equity. Net Income divided by Shareholders\' Equity. Measures profitability relative to owners\' investment.' },
    { term: 'Enterprise Value (EV)', definition: 'Market Cap + Total Debt - Cash. Represents the total value of a business to all stakeholders (equity + debt holders).' },
    { term: 'Goodwill', definition: 'Intangible asset arising when a company is acquired for more than the fair value of its net identifiable assets.' },
    { term: 'Depreciation', definition: 'Systematic allocation of the cost of a tangible asset over its useful life. Reduces taxable income but is a non-cash expense.' },
    { term: 'Amortization', definition: 'Gradual write-off of the cost of an intangible asset (patents, trademarks, goodwill) over its useful life.' },
    { term: 'Capital Expenditure (CapEx)', definition: 'Spending on long-term assets like property, equipment, or technology. Capitalized on the balance sheet and depreciated.' },
    { term: 'Working Capital', definition: 'Current Assets minus Current Liabilities. Measures a company\'s ability to meet short-term obligations.' },
    { term: 'Book Value', definition: 'The net asset value of a company as recorded on the balance sheet. Total Assets minus Total Liabilities.' },
    { term: 'Retained Earnings', definition: 'Cumulative net income kept by the company (not paid as dividends). Part of shareholders\' equity on the balance sheet.' },
  ],
  tips: [
    'Always read financial statements together — P&L, balance sheet, and cash flow tell different parts of the same story',
    'Compare ratios to industry averages, not absolute benchmarks. A 10% margin is great for retail but poor for software',
    'Watch for red flags: declining cash flow despite growing profits, rising receivables, frequent "one-time" charges',
    'Free Cash Flow is more reliable than net income — profits can be manipulated through accounting choices, cash cannot',
    'DuPont analysis reveals whether high ROE comes from margins, efficiency, or dangerous leverage',
    'For small businesses, understand the difference between business income and owner\'s salary/drawings',
    'Choose your business structure based on liability protection and tax efficiency, not just simplicity',
    'Maintain clean books from day one — messy accounting is the #1 obstacle to business valuation and funding',
  ],
  faqs: [
    {
      question: 'How do I read a company\'s financial statements as an investor?',
      answer: 'Start with the Income Statement: Is revenue growing? Are margins stable or improving? Then check the Balance Sheet: Is debt manageable (D/E < 1)? Is the company asset-heavy or asset-light? Finally, the Cash Flow Statement: Is operating cash flow positive and growing? Is FCF healthy? Key red flags: profits growing but cash flow declining, rising inventory, increasing debt without revenue growth. Use screener.in (India) or SEC EDGAR (US) to access financial statements.',
    },
    {
      question: 'What is the best way to value a small business in India?',
      answer: 'For small businesses, use multiple methods: 1) Earnings multiple: 3-5x annual net profit (varies by industry, growth rate, and risk), 2) Revenue multiple: 0.5-2x annual revenue for service businesses, 3) Asset-based: sum of all assets at fair market value minus liabilities, 4) DCF for businesses with predictable cash flows. Always adjust for owner-specific benefits (owner\'s salary, personal expenses running through the business). Get a SEBI-registered valuer for formal valuations.',
    },
    {
      question: 'Should I register my business as a Private Limited or LLP in India?',
      answer: 'Choose Pvt Ltd if: you plan to raise external funding (VCs/angels prefer Pvt Ltd), you expect rapid growth, or you want employee stock options (ESOPs). Choose LLP if: you\'re a professional services firm, you want lower compliance costs, you don\'t plan to raise equity funding, or you prefer pass-through taxation. LLP has no dividend distribution tax, lower annual compliance, but cannot issue shares. Pvt Ltd has more compliance but is better for scaling and fundraising.',
    },
    {
      question: 'What are the most important financial ratios for stock analysis?',
      answer: 'Core ratios: 1) P/E Ratio (valuation — compare within industry), 2) ROE >15% (profitability), 3) Debt-to-Equity <1 (leverage), 4) Current Ratio >1.5 (liquidity), 5) Operating Margin trend (efficiency), 6) Free Cash Flow yield (cash generation), 7) Dividend Payout Ratio (shareholder returns). Use DuPont analysis to decompose ROE. Compare ratios across 5+ years to identify trends. In India, use Screener.in for free ratio analysis of listed companies.',
    },
  ],
};
