import type { EngineData } from '../types';

export const advisorySkillsEngine: EngineData = {
  category: 'advisory-skills',
  title: 'Financial Advisory Skills & Practice Management',
  description: 'Communication, sales, soft skills, client management, and professional development for financial advisors and finance professionals.',
  topics: [
    {
      name: 'Communication Skills for Finance',
      description: 'How to explain complex financial concepts clearly and build trust through effective communication.',
      details: [
        'The Pyramid Principle: lead with the conclusion, then support with data — clients want the "so what" first',
        'Use analogies to explain complex concepts: compound interest as a snowball, diversification as not putting all eggs in one basket',
        'The 3-Level Explanation Framework: 1) One-sentence summary, 2) Key points with examples, 3) Deep technical details if asked',
        'Avoid jargon with retail clients — say "stock market index fund" not "passively managed equity ETF tracking a broad-based benchmark"',
        'Active listening: repeat back what the client said ("So you\'re concerned about outliving your savings..."), ask clarifying questions, take notes',
        'Written communication: financial reports should have an Executive Summary, Key Findings, Recommendations, and Appendix with data',
        'Use visuals — pie charts for allocation, line charts for growth projections, tables for comparisons. Clients retain 65% more with visuals',
        'Email best practices: subject line with action needed, bullet points not paragraphs, one clear call-to-action per email',
        'Delivering bad news: be direct, provide context, present the plan forward. "Your portfolio is down 12% due to market correction. Here\'s our strategy..."',
        'Presentation skills: 10-20-30 rule (10 slides, 20 minutes, 30pt font minimum) for financial presentations',
      ],
      subtopics: [
        {
          name: 'Financial Report Writing',
          description: 'How to write clear, actionable financial reports and plans.',
          details: [
            'Investment Policy Statement (IPS): objectives, constraints, asset allocation, rebalancing rules, benchmarks',
            'Financial Plan Structure: Executive summary → Current situation → Goals → Recommendations → Implementation timeline → Monitoring plan',
            'Quarterly Review Reports: Portfolio performance vs benchmark, asset allocation drift, market commentary, recommendations',
            'Use plain English summaries alongside technical data. Example: "Your portfolio returned 8.2% vs the benchmark 7.5%, beating it by 0.7%"',
            'Include action items with clear deadlines: "Rebalance by March 15", "Increase SIP by ₹2,000 starting April"',
            'Risk disclaimers: always include appropriate disclaimers about past performance, market risks, and advisory limitations',
          ],
        },
        {
          name: 'Client Meeting Framework',
          description: 'Structuring productive financial advisory meetings.',
          details: [
            'Pre-meeting: Review client file, recent transactions, market conditions, prepare agenda',
            'Opening (5 min): Personal check-in, set agenda, confirm time available',
            'Review (15 min): Portfolio performance, progress toward goals, any life changes',
            'Discussion (20 min): Address concerns, present recommendations, answer questions',
            'Action items (10 min): Summarize decisions, assign tasks, set next meeting date',
            'Follow-up: Send meeting notes within 24 hours, implement agreed changes promptly',
          ],
        },
      ],
    },
    {
      name: 'Sales & Business Development',
      description: 'Client acquisition, relationship management, and building a financial advisory practice.',
      details: [
        'The consultative selling approach: diagnose before you prescribe. Ask about goals, fears, timeline before recommending products',
        'Client segmentation: A-clients (top 20% revenue, quarterly meetings), B-clients (monthly check-ins), C-clients (annual reviews)',
        'Referral strategy: ask satisfied clients "Who else do you know who might benefit from this kind of planning?" — timing matters, ask after delivering value',
        'Elevator pitch formula: "I help [target client] achieve [outcome] through [method]. For example, [brief success story]"',
        'Fee structures: AUM-based (0.5-1.5% of assets), flat fee (₹25,000-₹1,00,000/year), hourly ($150-$400/hr), commission-based, hybrid',
        'AUM model: ₹1 crore AUM at 1% = ₹1 lakh/year revenue per client. Need ₹50 crore AUM for ₹50 lakh annual revenue',
        'Client onboarding checklist: KYC documents, risk profiling questionnaire, IPS, account opening, initial investment plan, first 90-day milestones',
        'Retention metrics: client churn rate should be below 5% annually. Cost of acquiring new client is 5-7x retaining existing one',
        'Digital presence: LinkedIn thought leadership posts, educational YouTube/blog content, webinars on trending topics (tax season, market corrections)',
        'Networking: join industry associations (FPSB, CFA Society, ICAI), attend financial planning conferences, local business groups',
      ],
      subtopics: [
        {
          name: 'Client Acquisition Strategies',
          description: 'Methods to attract and convert new financial advisory clients.',
          details: [
            'Content marketing: write about "5 Tax Mistakes Salaried Employees Make" — educational content attracts prospects',
            'Seminar selling: host free financial literacy workshops at corporates, colleges, community centers',
            'Centers of influence: build relationships with CAs, lawyers, real estate agents who can refer clients',
            'Online lead generation: Google Ads for "financial advisor near me", Facebook ads targeting life events (marriage, new job, retirement)',
            'Niche specialization: become the go-to advisor for doctors, IT professionals, NRIs, or retirees — niche expertise commands premium fees',
            'Free initial consultation (30-60 min): demonstrate value, assess fit, present your process and fees',
          ],
        },
        {
          name: 'Negotiation Skills',
          description: 'Negotiation techniques for financial professionals.',
          details: [
            'BATNA (Best Alternative to Negotiated Agreement): always know your walkaway point before entering any negotiation',
            'Anchoring: present your fee structure confidently first — the first number mentioned anchors the negotiation',
            'Value framing: "My fee is ₹50,000/year, but I typically save clients 2-5x that amount in tax optimization alone"',
            'Handling fee objections: compare advisory fees to cost of mistakes. "A wrong insurance policy can cost ₹10-20 lakhs over its lifetime"',
            'Win-win approach: flexible payment plans, tiered service models, family pricing — find solutions that work for both parties',
            'Salary negotiation coaching for clients: market research, total compensation analysis, counter-offer strategies',
          ],
        },
        {
          name: 'Practice Management',
          description: 'Running an efficient financial advisory business.',
          details: [
            'Capacity planning: one advisor can effectively manage 75-150 client households depending on service model',
            'Revenue targets: set annual revenue goals, track monthly, review quarterly. Typical independent advisor targets ₹50L-₹2Cr revenue',
            'Team building: hire a paraplanner first (₹4-8 LPA), then admin support, then junior advisors as practice grows',
            'Compliance calendar: SEBI/AMFI renewals, CPE credits, audit preparation, client disclosure updates',
            'Standard Operating Procedures (SOPs): document every process — client onboarding, review meetings, rebalancing, tax-loss harvesting',
            'Business continuity plan: partnership agreements, succession planning, key-person insurance, data backup protocols',
          ],
        },
      ],
    },
    {
      name: 'Soft Skills & Emotional Intelligence',
      description: 'Building trust, showing empathy, and maintaining ethical standards in financial advisory.',
      details: [
        'Trust equation: Trust = (Credibility + Reliability + Intimacy) / Self-Orientation. Lower self-interest perception = higher trust',
        'Empathy in finance: acknowledge emotions before logic. "I understand this market drop is scary. Let\'s look at what this means for YOUR specific plan"',
        'Patience during market volatility: prevent panic selling by reminding clients of their long-term plan and historical recoveries',
        'Ethical judgment framework: 1) Is it legal? 2) Is it in the client\'s best interest? 3) Would I do this for my own family? 4) Would I be comfortable if this was public?',
        'Fiduciary mindset: always put client interest first, even when it means recommending lower-commission products',
        'Handling difficult conversations: life insurance needs assessment after a health scare, retirement shortfall discussions, estate planning',
        'Cultural sensitivity: understand different communities\' attitudes toward money, inheritance, joint family finances, gender dynamics in financial decisions',
        'Conflict of interest management: disclose all commissions, affiliations, and potential conflicts transparently',
        'Burnout prevention: financial advisors face decision fatigue. Schedule complex decisions in the morning, routine tasks in the afternoon',
        'Continuous learning: read 1 financial book per month, attend 2-3 industry events per year, maintain certifications (CFP, CFA, NISM)',
      ],
      subtopics: [
        {
          name: 'Client Psychology & Behavioral Coaching',
          description: 'Helping clients overcome emotional financial decisions.',
          details: [
            'Goal visualization: help clients picture their retirement, children\'s education, dream home — emotional connection drives discipline',
            'Loss aversion coaching: show clients that market timing failures cost more than staying invested. Missing the best 10 days = 50% lower returns',
            'Accountability partnership: regular check-ins keep clients on track with savings goals, debt repayment, insurance renewals',
            'Celebrating milestones: acknowledge when clients hit savings targets, become debt-free, or reach investment milestones',
            'Pre-commitment strategies: set up auto-invest SIPs, automatic salary deductions — remove the decision from the equation',
            'Reframing technique: "You\'re not losing money, you\'re buying more units at a lower price" during market corrections for SIP investors',
          ],
        },
        {
          name: 'Professional Certifications & Development',
          description: 'Key certifications and career paths in financial advisory.',
          details: [
            'CFP (Certified Financial Planner): gold standard globally. FPSB India certification. Covers all 6 areas of financial planning',
            'CFA (Chartered Financial Analyst): 3-level program. Best for investment management roles. Takes 2.5-4 years typically',
            'NISM Certifications (India): Series V-A (Mutual Fund), Series VIII (Equity Derivatives), Series X-A (Investment Adviser) — mandatory for practice',
            'CA/CPA: essential for tax planning specialization. CA (India) or CPA (US) credentials add significant credibility',
            'SEBI RIA Registration: mandatory for charging advisory fees in India. Requirements: net worth ₹5 lakh (individual), qualification (CFP/CFA/CA + post-grad)',
            'Continuing education: CFP requires 30 CPE credits every 2 years, CFA requires annual attestation, NISM requires renewal every 3 years',
          ],
        },
      ],
    },
  ],
  keyTerms: [
    { term: 'Fiduciary Duty', definition: 'Legal obligation to act in the client\'s best interest, not the advisor\'s. SEBI RIAs and US RIAs are fiduciaries.' },
    { term: 'AUM (Assets Under Management)', definition: 'Total market value of assets a financial advisor manages. Used as basis for fee calculation (typically 0.5-1.5%).' },
    { term: 'KYC (Know Your Customer)', definition: 'Regulatory process to verify client identity, address, and financial profile before providing services.' },
    { term: 'IPS (Investment Policy Statement)', definition: 'Written document defining investment objectives, risk tolerance, constraints, and strategy for a client.' },
    { term: 'Risk Profiling', definition: 'Assessment of a client\'s ability and willingness to take financial risk, using questionnaires and discussion.' },
    { term: 'Suitability', definition: 'Regulatory requirement that financial products recommended must be appropriate for the client\'s situation and goals.' },
    { term: 'Churning', definition: 'Unethical practice of excessive trading in a client\'s account to generate commissions.' },
    { term: 'Fee-Only vs Fee-Based', definition: 'Fee-only advisors earn only from client fees. Fee-based may also earn commissions — important conflict of interest distinction.' },
    { term: 'Client Lifetime Value (CLV)', definition: 'Total revenue expected from a client relationship over its duration. High CLV justifies higher acquisition costs.' },
    { term: 'Paraplanner', definition: 'Support professional who assists financial advisors with research, plan preparation, and administrative tasks.' },
  ],
  tips: [
    'The best financial advice is useless if the client doesn\'t understand or trust it — communication is 50% of the job',
    'Document everything — meeting notes, recommendations, client decisions. It protects both you and the client',
    'Return calls and emails within 24 hours — responsiveness builds trust faster than performance',
    'Specialize in a niche rather than being a generalist — "financial advisor for IT professionals" beats "financial advisor"',
    'Review your own finances regularly — credibility comes from practicing what you preach',
    'Build systems that scale: templates, checklists, automated reports. Your time should be spent on client relationships, not paperwork',
    'Ask "What keeps you up at night about money?" in every first meeting — it reveals priorities no questionnaire can capture',
    'Track Net Promoter Score (NPS) from clients annually — it predicts referrals and retention better than any other metric',
  ],
  faqs: [
    {
      question: 'How do I become a financial advisor in India?',
      answer: 'Get qualified (CFP/CFA/CA + post-graduate degree), register with SEBI as a Registered Investment Adviser (RIA) with ₹5 lakh net worth requirement, obtain NISM certifications, and build a practice. Alternatively, join an existing advisory firm to gain experience first.',
    },
    {
      question: 'What is the difference between a financial advisor and a financial planner?',
      answer: 'A financial advisor is a broad term covering anyone giving financial advice (investment, insurance, tax). A financial planner specifically creates comprehensive financial plans covering all aspects — budgeting, investing, tax, insurance, retirement, and estate planning. All planners are advisors, but not all advisors are planners.',
    },
    {
      question: 'How should I handle a client who wants to panic-sell during a market crash?',
      answer: 'Acknowledge their fear (empathy), remind them of their long-term financial plan and goals, show historical recovery data (markets have recovered from every crash), review their risk tolerance, and suggest reviewing rather than reacting. If appropriate, discuss tactical rebalancing as a constructive action.',
    },
    {
      question: 'What are the most important skills for a successful financial advisor?',
      answer: 'In order of impact: 1) Trustworthiness and ethical conduct, 2) Communication skills (explaining complex concepts simply), 3) Active listening and empathy, 4) Technical knowledge (investments, tax, insurance), 5) Business development and networking. Technical skills get you in the door, but soft skills determine long-term success.',
    },
  ],
};
