import type { EngineData } from '../types';

export const debtManagementEngine: EngineData = {
  category: 'debt-management',
  title: 'Debt Management',
  description: 'Comprehensive guide to understanding, managing, and eliminating debt — covering loan types, credit management, repayment strategies, mortgages, education loans, and common debt traps to avoid.',
  topics: [
    {
      name: 'Types of Debt',
      description: 'Understanding different categories of debt and how they impact your financial health.',
      details: [
        'Secured debt is backed by collateral (an asset the lender can seize if you default) — examples include mortgages, auto loans, and gold loans.',
        'Unsecured debt has no collateral backing — examples include credit cards, personal loans, and medical bills. Lenders charge higher interest rates to compensate for the added risk.',
        'Revolving debt allows you to borrow repeatedly up to a credit limit — credit cards and home equity lines of credit (HELOCs) are common examples. Interest is charged only on the outstanding balance.',
        'Installment debt is repaid in fixed periodic payments over a set term — mortgages, auto loans, personal loans, and student loans are installment debts.',
        'Good debt is borrowing that builds wealth or increases earning potential — examples include home loans (appreciating asset), education loans (higher earning power), and business loans (income generation).',
        'Bad debt is borrowing for depreciating assets or consumption — high-interest credit card debt, payday loans, and auto loans on luxury vehicles typically fall into this category.',
        'Priority debt has serious consequences for non-payment — mortgage/rent, taxes owed, and child support. These should always be paid before non-priority debts.',
        'Non-priority debt includes credit cards, personal loans, and medical bills. Consequences of default are less severe (no home loss) but still damage credit and may lead to legal action.',
        'Debt-to-income (DTI) ratio = Total monthly debt payments / Gross monthly income. Lenders typically prefer DTI below 36%, with no more than 28% on housing.',
        'The cost of debt is not just the interest rate — fees, penalties, opportunity cost of payments, and psychological stress all factor into the true cost of borrowing.',
      ],
      subtopics: [
        {
          name: 'Secured vs Unsecured Debt',
          description: 'Key differences between debt backed by assets and debt based solely on creditworthiness.',
          details: [
            'Secured debt typically carries lower interest rates (e.g., mortgage 6-8%, auto loan 5-9%) because the lender has recourse to the collateral.',
            'Unsecured debt carries higher interest rates (e.g., credit cards 15-30%, personal loans 10-24%) due to higher lender risk.',
            'If you default on secured debt, the lender can repossess or foreclose on the collateral. Remaining balance after sale (deficiency) may still be owed.',
            'Unsecured creditors must sue you in court and obtain a judgment before they can garnish wages or place liens on your property.',
            'Secured debt can become a trap if the asset depreciates faster than the loan is repaid — being "underwater" on a car loan or mortgage means you owe more than the asset is worth.',
            'Loan against securities (LAS) and loan against fixed deposits are secured loans that use financial assets as collateral — lower rates but risk of forced liquidation if asset value drops.',
            'In bankruptcy, secured creditors are paid first from the proceeds of the collateral. Unsecured creditors share the remaining assets.',
            'Converting unsecured debt to secured debt (e.g., consolidating credit cards into a home equity loan) lowers rates but puts your home at risk.',
          ],
        },
        {
          name: 'Good Debt vs Bad Debt',
          description: 'Framework for evaluating whether borrowing creates or destroys wealth.',
          details: [
            'Good debt has three characteristics: (1) finances an appreciating asset or income-producing opportunity, (2) has a reasonable interest rate, and (3) the expected return exceeds the cost of borrowing.',
            'A home loan is typically good debt — real estate generally appreciates, mortgage interest may be tax-deductible, and it replaces rent payments.',
            'Education loans can be good debt if the degree significantly increases earning potential — STEM and professional degrees often yield strong ROI. Liberal arts at expensive private institutions may not.',
            'Business loans are good debt when used for ventures with solid business plans and realistic profitability projections.',
            'Bad debt examples: carrying a credit card balance at 20%+ APR to fund vacations, dining, or shopping. The purchased items depreciate immediately while interest compounds.',
            'Auto loans on new cars are borderline — a new car loses 20-30% of value in the first year. Financing a reliable used car at a reasonable rate is more financially sound.',
            'Payday loans (300-500% APR) and buy-now-pay-later schemes with hidden fees are almost always bad debt.',
            'Even "good debt" becomes bad debt if you borrow more than you can comfortably repay or if the terms are predatory.',
          ],
        },
      ],
    },
    {
      name: 'Loan Structuring',
      description: 'Understanding how different loan products work, their terms, and how to choose the right structure for your needs.',
      details: [
        'EMI (Equated Monthly Installment) = [P x R x (1+R)^N] / [(1+R)^N - 1], where P = principal, R = monthly interest rate, N = number of months.',
        'Amortization schedule shows the breakdown of each EMI into principal and interest components — early payments are mostly interest, later payments are mostly principal.',
        'Loan tenure directly impacts total interest paid — a 20-year home loan pays significantly more total interest than a 15-year loan, even though monthly EMI is lower.',
        'Processing fees typically range from 0.5-2% of the loan amount. Factor these into the effective cost of borrowing.',
        'Prepayment/foreclosure charges: Fixed-rate loans may charge 2-4% of outstanding principal for early repayment. Floating-rate loans in India cannot charge prepayment penalties (per RBI rules).',
        'Loan-to-value (LTV) ratio = Loan amount / Asset value. Higher LTV means more borrowing but often requires mortgage insurance and carries higher rates.',
        'Co-borrower or guarantor arrangements can help secure better rates or higher loan amounts — but the co-borrower is equally liable for repayment.',
        'Debt service coverage ratio (DSCR) = Net operating income / Total debt service. Used primarily for business and investment property loans. Lenders typically require DSCR > 1.25.',
        'Pre-approved loans from your existing bank may offer better rates and faster processing, but always compare with other lenders before accepting.',
        'Read the fine print on reset clauses, rate adjustment frequency, and penalty clauses before signing any loan agreement.',
      ],
      subtopics: [
        {
          name: 'Home Loans / Mortgages',
          description: 'The largest debt most people will carry — understanding structure is critical.',
          details: [
            'Fixed-rate mortgage: Interest rate stays constant throughout the loan term. Provides payment predictability. Typically slightly higher initial rate than floating.',
            'Floating/adjustable-rate mortgage (ARM): Rate is linked to a benchmark (MCLR in India, SOFR/Prime in US) and changes periodically. Lower initial rate but payment uncertainty.',
            'Hybrid ARMs (e.g., 5/1 ARM): Fixed rate for initial 5 years, then adjusts annually. Useful if you plan to sell or refinance before the adjustment period.',
            'In India, home loan interest is tax-deductible up to ₹2 lakh per year under Section 24(b), and principal repayment up to ₹1.5 lakh under Section 80C.',
            'In the US, mortgage interest is tax-deductible on loans up to $750,000 (post-2017 Tax Cuts and Jobs Act). Property taxes deductible up to $10,000 (SALT cap).',
            'Down payment: Typically 10-20% of property value. Less than 20% in the US requires Private Mortgage Insurance (PMI), adding 0.5-1% of loan amount annually.',
            'Home loan balance transfer: Switching your existing home loan to another lender offering a lower interest rate. Saves significant interest over the remaining tenure.',
            'Prepayment strategy: Even small additional payments toward principal dramatically reduce total interest. Paying one extra EMI per year on a 20-year loan can cut the tenure by 3-4 years.',
            'Home loan tenure in India: Up to 30 years. Most banks calculate maximum tenure based on retirement age (typically 60-65 years).',
          ],
        },
        {
          name: 'Personal Loans',
          description: 'Unsecured loans for various personal needs with higher interest rates.',
          details: [
            'Interest rates typically range from 10-24% depending on credit score, income, and lender. Significantly higher than secured loans.',
            'Loan amounts usually range from ₹50,000 to ₹40 lakh (India) or $1,000 to $100,000 (US), based on income and creditworthiness.',
            'Tenures typically range from 1-5 years. Shorter tenures mean higher EMIs but lower total interest paid.',
            'No collateral required — approval is based on income, employment stability, credit score, and existing obligations.',
            'Best used for genuine emergencies, debt consolidation (if it lowers overall interest), or short-term needs. Not ideal for discretionary spending.',
            'Top-up loans: Some lenders offer additional borrowing on existing personal loans at potentially lower rates than a new loan.',
            'Personal loan interest is generally not tax-deductible in India or the US (exception: if used for business purposes or home improvement in certain cases).',
            'Peer-to-peer (P2P) lending platforms may offer competitive rates but verify the platform is regulated (RBI-registered in India, SEC-registered in US).',
          ],
        },
        {
          name: 'Education Loans',
          description: 'Financing higher education domestically and internationally.',
          details: [
            'In India, education loans cover tuition, hostel, books, equipment, and travel expenses for approved courses at recognized institutions.',
            'Indian education loan interest is fully tax-deductible under Section 80E — no upper limit on the deduction, available for up to 8 years from the start of repayment.',
            'Moratorium period: Repayment typically begins 6-12 months after course completion or 6 months after getting a job, whichever is earlier.',
            'Collateral requirements (India): Loans up to ₹4-7.5 lakh may not require collateral. Above that, banks typically require property or fixed deposit as security.',
            'US federal student loans offer income-driven repayment plans (IBR, PAYE, REPAYE/SAVE) that cap payments at 10-20% of discretionary income.',
            'US Public Service Loan Forgiveness (PSLF): Remaining balance forgiven after 120 qualifying payments while working full-time for a qualifying employer (government, nonprofit).',
            'US federal loan interest rates are set annually by Congress — for 2024-25, undergraduate Direct Loans are approximately 6.53%.',
            'Private student loans in the US typically have higher rates and fewer protections than federal loans. Exhaust federal options first.',
            'Refinancing student loans can lower rates but federal loans refinanced into private loans lose access to federal protections (IBR, PSLF, forbearance).',
          ],
        },
        {
          name: 'Auto Loans and Gold Loans',
          description: 'Financing vehicles and leveraging gold assets for liquidity.',
          details: [
            'Auto loan rates: New cars typically 7-9% (India) or 5-8% (US). Used cars carry higher rates due to higher risk and lower collateral value.',
            'Auto loan tenure: Typically 1-7 years. Longer tenures reduce EMI but increase total interest and risk of being underwater (owing more than car is worth).',
            'The 20/4/10 rule for auto loans: 20% down payment, no more than 4-year term, and total vehicle expenses (EMI + insurance + fuel) under 10% of gross income.',
            'Gold loans (India): Borrow against gold jewelry or coins at 10-16% interest. Quick disbursement, minimal documentation, no income proof needed.',
            'Gold loan LTV: RBI permits up to 75% of gold value. If gold price drops significantly, the lender may ask for additional gold or partial repayment (margin call).',
            'Gold loan tenures are typically short (3-24 months) with flexible repayment options: interest-only EMIs with bullet principal repayment, or regular EMIs.',
            'If gold loan is not repaid, the lender auctions the pledged gold. Any surplus after loan recovery is returned to the borrower.',
            'Loan against securities (LAS): Borrow against mutual funds, shares, bonds, or insurance policies at 9-12%. Retains investment exposure while providing liquidity.',
          ],
        },
      ],
    },
    {
      name: 'Credit Management',
      description: 'Building and maintaining a strong credit profile for better loan terms and financial opportunities.',
      details: [
        'A credit score is a three-digit number (300-900 in India, 300-850 in the US) that represents your creditworthiness based on your credit history.',
        'CIBIL (TransUnion CIBIL) is India\'s primary credit bureau. A score of 750+ is considered good for loan approvals at competitive rates.',
        'FICO scores (US) range from 300-850: Exceptional (800+), Very Good (740-799), Good (670-739), Fair (580-669), Poor (below 580).',
        'Payment history is the single largest factor in credit scores — accounting for 35% (FICO) of the score. Even one 30-day late payment can drop your score significantly.',
        'Credit utilization ratio (outstanding balance / credit limit) accounts for 30% of FICO score. Keep utilization below 30%, ideally below 10%, for the best scores.',
        'Length of credit history (15% of FICO): Longer history is better. Avoid closing your oldest credit card account as it shortens average account age.',
        'Credit mix (10% of FICO): Having different types of credit (credit card, auto loan, mortgage) can slightly improve your score.',
        'New credit inquiries (10% of FICO): Each hard inquiry may lower your score by 5-10 points temporarily. Multiple inquiries for the same loan type within 14-45 days count as one.',
        'Check your credit report annually for errors — dispute inaccuracies with the bureau. In the US, you are entitled to one free report per year from each bureau at AnnualCreditReport.com.',
        'In India, CIBIL, Experian, Equifax, and CRIF High Mark are the four credit bureaus. You can get one free credit report per year from each.',
      ],
      subtopics: [
        {
          name: 'Improving Your Credit Score',
          description: 'Actionable strategies to build or rebuild your credit profile.',
          details: [
            'Pay all bills on or before the due date — set up autopay for at least the minimum payment to avoid missed payments.',
            'Reduce credit utilization: Pay down balances, request credit limit increases, or spread spending across multiple cards.',
            'Do not close old credit card accounts unless they carry an annual fee — the age of your oldest account matters.',
            'Become an authorized user on a family member\'s old, well-maintained credit card to inherit their positive payment history.',
            'Use a secured credit card (backed by a fixed deposit) if you have no credit history or are rebuilding after defaults.',
            'Limit hard inquiries — avoid applying for multiple credit cards or loans within a short period.',
            'Dispute errors on your credit report promptly: incorrect balances, accounts that are not yours, or payments wrongly marked as late.',
            'Settling a debt for less than owed ("settled" status) is worse for your credit than paying in full ("closed" status). Negotiate for "paid in full" when settling.',
            'Credit score improvements take time — expect 3-6 months of consistent positive behavior before seeing significant changes.',
          ],
        },
        {
          name: 'Credit Card Management',
          description: 'Using credit cards responsibly and maximizing rewards without falling into debt.',
          details: [
            'Always pay the full statement balance by the due date. Paying only the minimum payment triggers interest on the entire outstanding balance (not just the unpaid portion in many countries).',
            'Credit card interest rates are among the highest of any borrowing — typically 24-42% APR in India and 15-30% in the US. Never treat credit cards as a borrowing tool.',
            'The grace period (20-50 days) is interest-free only if you pay the previous statement in full. Carrying a balance eliminates the grace period on new purchases.',
            'Rewards optimization: Choose cards aligned with your spending — travel cards for frequent flyers, cashback cards for everyday spending, fuel cards for commuters.',
            'Annual fee cards are worth it only if the value of rewards and benefits exceeds the fee. Calculate the break-even spending amount.',
            'Balance transfer cards offer 0% APR for 12-21 months (US) — useful for paying down high-interest debt, but watch for the 3-5% transfer fee and the rate after the promotional period.',
            'EMI conversion: Converting large purchases to EMI on credit cards often carries 12-18% interest. Compare with a personal loan rate before opting.',
            'Avoid cash advances on credit cards — they carry no grace period, higher interest rates (25-40%), and an immediate cash advance fee (2.5-3%).',
          ],
        },
      ],
    },
    {
      name: 'Debt Reduction Strategies',
      description: 'Systematic approaches to paying off debt efficiently and regaining financial freedom.',
      details: [
        'Step 1 of any debt reduction plan: List all debts with their balances, interest rates, minimum payments, and due dates. You cannot manage what you do not track.',
        'Build a small emergency fund ($500-$1,000 or ₹20,000-50,000) before aggressively paying debt — this prevents new debt from unexpected expenses.',
        'The debt avalanche method mathematically minimizes total interest paid but requires discipline as the highest-rate debt may also have the largest balance.',
        'The debt snowball method provides quick psychological wins by eliminating small debts first, building momentum and motivation.',
        'Debt consolidation combines multiple debts into a single loan, ideally at a lower interest rate. Simplifies payments but does not reduce the principal owed.',
        'Balance transfer to a 0% APR card can save significant interest — but you must pay off the transferred balance before the promotional period ends, or deferred interest may apply.',
        'Negotiating with creditors: Many creditors will agree to lower interest rates, waive fees, or create hardship payment plans if you explain your financial situation honestly.',
        'Debt Management Plans (DMPs) through nonprofit credit counseling agencies negotiate reduced rates and consolidated payments. Takes 3-5 years. Does not involve borrowing.',
        'The 50/30/20 budget rule can guide debt repayment: 50% needs, 30% wants, 20% savings/debt repayment. When in debt, shift more from "wants" to repayment.',
        'Windfalls (tax refunds, bonuses, gifts) should be directed toward high-interest debt rather than discretionary spending when you are actively reducing debt.',
      ],
      subtopics: [
        {
          name: 'Debt Avalanche Method',
          description: 'Paying off debts ordered by interest rate from highest to lowest — mathematically optimal.',
          details: [
            'Step 1: List all debts from highest interest rate to lowest. Make minimum payments on all debts.',
            'Step 2: Direct all extra payment capacity toward the debt with the highest interest rate.',
            'Step 3: Once the highest-rate debt is fully paid, roll that entire payment (minimum + extra) into the next highest-rate debt.',
            'Advantage: Minimizes total interest paid over the repayment period. You save the most money with this approach.',
            'Disadvantage: If the highest-rate debt has a large balance, it may take months to see progress, which can be discouraging.',
            'Example: If you have a credit card at 24%, personal loan at 14%, and car loan at 8%, pay minimums on all and throw extra money at the 24% credit card first.',
            'Hybrid approach: Use avalanche order but split any very large high-rate debts into psychological milestones to maintain motivation.',
            'The avalanche method can save thousands in interest compared to snowball on the same debt portfolio, depending on the rate differential.',
          ],
        },
        {
          name: 'Debt Snowball Method',
          description: 'Paying off debts ordered by balance from smallest to largest — psychologically powerful.',
          details: [
            'Step 1: List all debts from smallest balance to largest, regardless of interest rate. Make minimum payments on all debts.',
            'Step 2: Direct all extra payment capacity toward the smallest balance debt.',
            'Step 3: Once the smallest debt is fully paid, roll that entire payment into the next smallest debt — the "snowball" grows with each eliminated debt.',
            'Advantage: Quick wins from eliminating small debts build confidence and momentum. Behavioral research shows higher completion rates with snowball.',
            'Disadvantage: You may pay more total interest over time compared to the avalanche method, especially if small-balance debts have low rates.',
            'Popularized by Dave Ramsey as part of his "Baby Steps" financial plan — effective for people who need psychological motivation.',
            'The snowball method reduces the number of creditors faster, simplifying financial management and reducing the chance of missed payments.',
            'Best suited for people with multiple small debts and who struggle with motivation — the emotional wins outweigh the mathematical cost.',
          ],
        },
        {
          name: 'Debt Consolidation and Balance Transfer',
          description: 'Combining multiple debts into a single, more manageable payment.',
          details: [
            'Debt consolidation loan: Taking a single personal loan to pay off multiple high-interest debts (credit cards, store cards, etc.). Works only if the consolidation rate is lower.',
            'Home equity loan or HELOC for debt consolidation: Lower rates (secured by home), but you risk your home if you cannot repay.',
            'Balance transfer cards (US): 0% APR for 12-21 months with a 3-5% transfer fee. Calculate if the fee savings exceed the interest you would have paid.',
            'Balance transfer trap: If you do not pay off the balance before the promotional period ends, the remaining balance is hit with the regular APR (often 18-25%).',
            'Consolidation does NOT reduce the total principal owed — it only restructures the debt. If spending habits do not change, you will end up with more debt.',
            'Close or freeze the original credit cards/accounts after consolidation to prevent accumulating new debt on top of the consolidation loan.',
            'In India, personal loan balance transfer allows moving an existing loan to a new lender at a lower rate — typically saves 1-3% on interest rate.',
            'Negotiate with your current lender for a rate reduction before consolidating — they may match or beat the competing offer to retain your business.',
          ],
        },
      ],
    },
    {
      name: 'Mortgage / Home Loan Deep Dive',
      description: 'Advanced strategies for managing the largest debt in most people\'s lives.',
      details: [
        'Total cost of a home = Purchase price + Total interest paid + Property taxes + Insurance + Maintenance. A ₹50 lakh loan at 8.5% for 20 years costs approximately ₹52 lakh in interest alone.',
        'EMI calculation example: ₹50,00,000 loan at 8.5% for 20 years (240 months). EMI ≈ ₹43,391. Total payment = ₹1,04,13,840. Interest paid = ₹54,13,840.',
        'Fixed vs floating: In a declining rate environment, floating rates save money. In a rising rate environment, fixed rates provide stability. India\'s market predominantly uses floating rates.',
        'Refinancing (home loan balance transfer): Switch to a lower-rate lender when rates have dropped by at least 0.50-0.75%. Factor in processing fees and legal costs.',
        'Part-prepayment strategy: Direct any surplus funds (bonus, increment) toward home loan principal. Even ₹1 lakh extra per year on a ₹50 lakh loan can save ₹8-10 lakh in interest and cut tenure by 3-4 years.',
        'Step-up EMI plans: Start with lower EMIs that increase annually — suitable for young professionals expecting income growth.',
        'Step-down EMI plans: Start with higher EMIs that decrease over time — suitable for those nearing retirement.',
        'Overdraft home loan facility: Allows you to park surplus funds in a linked account that offsets the outstanding principal, reducing effective interest. Withdraw surplus anytime.',
        'Joint home loans with a co-applicant (especially spouse) can increase loan eligibility and provide additional tax benefits — both borrowers can claim Section 24(b) and 80C deductions in India.',
        'Always compare the Annual Percentage Rate (APR), not just the nominal interest rate — APR includes processing fees, insurance, and other costs for a true cost comparison.',
      ],
      subtopics: [
        {
          name: 'Prepayment Strategies',
          description: 'How to pay off your home loan faster and save on total interest.',
          details: [
            'Reduce tenure vs reduce EMI: When making a prepayment, choosing to reduce tenure saves more interest than reducing EMI. Reduce EMI only if you need immediate cash flow relief.',
            'Lump-sum prepayment: Use bonuses, tax refunds, or inheritance to make annual or semi-annual lump-sum payments toward principal.',
            'Increase EMI with income growth: If your income increases by 10% annually, increase your EMI by 5% — the loan could be paid off years earlier.',
            'Bi-weekly payment strategy: Pay half the EMI every two weeks instead of one full EMI monthly — this results in 13 full payments per year instead of 12.',
            'RBI mandate: Banks in India cannot charge prepayment penalties on floating-rate home loans. Fixed-rate loans may carry a 2-4% prepayment penalty.',
            'Opportunity cost check: If your home loan rate is 8% and you can earn 12% on equity investments, the mathematical choice favors investing. But guaranteed debt reduction has its own psychological and risk-adjusted value.',
            'Top-up home loan: Instead of taking a personal loan at 14%, consider a top-up on your home loan at 8.5-9.5% for renovations or other needs.',
            'SIP + prepayment combo: Start a SIP in equity mutual funds and use the accumulated corpus for periodic bulk prepayments — leverages compounding while reducing debt.',
          ],
        },
        {
          name: 'Fixed vs Floating Rate Decision',
          description: 'Choosing the right interest rate structure for your home loan.',
          details: [
            'Fixed-rate loans in India are typically 0.5-1.5% higher than the prevailing floating rate. This premium is the "price of certainty."',
            'In the US, 30-year fixed-rate mortgages are the most popular — providing complete payment stability for the entire loan term.',
            'Floating rates in India are linked to external benchmarks (repo rate via EBLR) since October 2019. Rate changes are transmitted more quickly to borrowers.',
            'When RBI cuts the repo rate, floating-rate borrowers benefit through reduced EMIs or shorter tenure. When rates rise, EMIs increase or tenure extends.',
            'Rate sensitivity: On a ₹50 lakh, 20-year loan, a 1% rate increase adds approximately ₹3,000-3,500 per month to the EMI.',
            'If you plan to prepay or sell within 5-7 years, floating rates are usually better since you benefit from the lower initial rate without long-term rate risk.',
            'If you need budget certainty and plan to hold the loan for the full tenure, fixed rates eliminate rate risk — especially valuable in a low-rate environment.',
            'Some lenders offer hybrid loans: fixed for the first 2-5 years, then floating. This balances initial certainty with longer-term flexibility.',
          ],
        },
      ],
    },
    {
      name: 'Student / Education Loan Planning',
      description: 'Strategies for financing education, managing student debt, and leveraging loan benefits.',
      details: [
        'The return on investment of education should justify the debt — compare the expected salary increase against the total cost of the degree including interest.',
        'In India, government banks typically offer education loans at 8-11% for domestic studies and 9.5-13% for international studies.',
        'In the US, federal student loan debt totals over $1.7 trillion, with average borrower owing approximately $37,000. It is the second-largest consumer debt category after mortgages.',
        'Indian education loans up to ₹4 lakh generally do not require collateral or co-borrower. ₹4-7.5 lakh requires a co-borrower. Above ₹7.5 lakh requires collateral.',
        'Interest subsidy schemes (India): Central government provides interest subsidy on education loans for economically weaker sections during the moratorium period.',
        'US federal loans have borrower protections not available with private loans: income-driven repayment, forgiveness programs, deferment, and forbearance.',
        'Grace period / moratorium: Most loans allow 6-12 months after graduation before repayment begins, but interest may continue to accrue and capitalize.',
        'Capitalizing interest: Unpaid interest during the moratorium period is added to the principal, increasing the total amount you repay. Pay interest during school if possible.',
        'Loan forgiveness programs: US PSLF forgives remaining federal loan balance after 10 years of qualifying payments while employed by a qualifying public service employer.',
        'Tax benefits on education loans: India Section 80E allows unlimited deduction on interest paid (not principal) for up to 8 years from the start of repayment.',
      ],
      subtopics: [
        {
          name: 'US Federal Student Loan Options',
          description: 'Types of federal student loans and their features.',
          details: [
            'Direct Subsidized Loans: For undergraduate students with financial need. Government pays interest while in school and during grace/deferment periods.',
            'Direct Unsubsidized Loans: Available to all students regardless of need. Interest accrues from disbursement — you pay all the interest.',
            'Direct PLUS Loans: For graduate students and parents. Higher interest rates and fees. Credit check required but criteria is lenient.',
            'Annual borrowing limits: Dependent undergraduates can borrow $5,500-$7,500/year in Direct Loans. Independent undergraduates: $9,500-$12,500/year.',
            'Aggregate limits: $31,000 for dependent undergraduates, $57,500 for independent undergraduates, $138,500 for graduate/professional students (including undergraduate borrowing).',
            'Income-Driven Repayment (IDR): SAVE plan (newest) caps payments at 5% of discretionary income for undergraduate loans, 10% for graduate loans.',
            'Standard repayment: 10-year fixed payment plan. Highest monthly payment but lowest total interest. This is the default plan.',
            'Graduated repayment: Payments start low and increase every two years. 10-year term. Useful for those expecting income growth.',
          ],
        },
        {
          name: 'Education Loan Repayment Strategies',
          description: 'Approaches to efficiently manage and pay off education debt.',
          details: [
            'Start paying interest during the moratorium period if possible — prevents interest capitalization and reduces total loan cost significantly.',
            'Refinance when your credit score and income improve — rates can drop 1-3% when moving from an in-school rate to a post-employment rate.',
            'Employer student loan repayment benefits: Some employers offer $5,250/year tax-free toward student loan payments. Ask your HR department.',
            'Prioritize high-interest private loans for extra payments while making minimum payments on lower-rate federal loans.',
            'In India, consider partial prepayment from annual bonuses — even small additional payments in the early years of the loan significantly reduce total interest.',
            'US income-driven repayment can result in loan forgiveness after 20-25 years, but the forgiven amount may be taxable as income (except PSLF).',
            'If working in public service (US), enroll in PSLF immediately — submit annual Employment Certification Forms and use an IDR plan for qualifying payments.',
            'Consolidation of multiple federal loans simplifies repayment into one payment but uses a weighted average interest rate (no actual rate reduction).',
          ],
        },
      ],
    },
    {
      name: 'Debt Traps to Avoid',
      description: 'Common predatory practices and dangerous borrowing patterns that can lead to a debt spiral.',
      details: [
        'A debt trap occurs when the cost of servicing existing debt exceeds your ability to repay, forcing you to borrow more just to keep up with payments.',
        'Payday loans charge 300-500% APR (annualized). A $500 loan with a $75 fee due in two weeks equals 391% APR. 80% of payday loans are rolled over or followed by another loan within 14 days.',
        'Credit card minimum payment trap: Paying only the minimum (typically 2-5% of balance) on a ₹1 lakh credit card balance at 36% APR would take over 10 years to repay and cost over ₹2 lakh in interest.',
        'Loan stacking: Taking multiple loans simultaneously from different lenders. Each loan individually may seem manageable, but combined EMIs can exceed 50-60% of income.',
        'Buy-now-pay-later (BNPL) schemes can encourage overspending. Missed payments often trigger retroactive interest from the date of purchase at 20-30% APR.',
        'Debt recycling (using borrowed money to invest) is a valid advanced strategy but goes wrong when investments underperform or when people use high-cost debt for speculative investments.',
        'Guarantee trap: Co-signing or guaranteeing someone else\'s loan makes you fully liable if they default. This has destroyed relationships and finances of countless guarantors.',
        'Gold loan rollovers: Continuously renewing gold loans without reducing principal, paying only interest. Over years, you may pay more in interest than the gold is worth.',
        'Unsolicited pre-approved loans and credit limit increases are designed to encourage borrowing — they are marketing tools, not endorsements of your financial capacity.',
        'Digital lending app traps (India): Unregulated apps offering instant loans at 25-50%+ effective interest rates with aggressive and sometimes illegal collection practices.',
      ],
      subtopics: [
        {
          name: 'Payday Loans and Predatory Lending',
          description: 'Understanding and avoiding the most dangerous forms of consumer debt.',
          details: [
            'Payday loans are short-term (typically 2-4 weeks) small-dollar loans that charge fees of $15-$30 per $100 borrowed — translating to 300-780% APR.',
            'The payday loan cycle: Borrower cannot repay on payday, so they roll over the loan (paying another fee). This cycle repeats, with the borrower paying fees that exceed the original loan amount.',
            'In India, unauthorized digital lending apps operate similarly — offering instant small loans with processing fees of 15-30% deducted upfront and very short repayment periods.',
            'Alternatives to payday loans: Negotiate with creditors for extensions, borrow from family, credit union payday alternative loans (PALs), employer salary advances, or community assistance programs.',
            'Predatory lending signs: Pressure to borrow quickly, lack of clear APR disclosure, no assessment of ability to repay, and penalty structures that encourage rollovers.',
            'Title loans (borrowing against car title) carry similar risks — 100-300% APR, and you can lose your vehicle if you default.',
            'RBI in India has cracked down on unregulated digital lenders. Only borrow from RBI-registered NBFCs and banks. Check the RBI NBFC registry before borrowing.',
            'If trapped in a payday loan cycle, seek help from a nonprofit credit counseling agency — they can negotiate with lenders and help create an exit plan.',
          ],
        },
        {
          name: 'Credit Card Debt Spiral',
          description: 'How credit card debt compounds and strategies to break free.',
          details: [
            'Credit card interest is calculated on the average daily balance and compounds monthly. At 36% APR (India), ₹1 lakh becomes ₹1,42,576 in just one year if untouched.',
            'Minimum payment illusion: Banks show a low minimum payment (2-5%) that feels manageable, but this ensures the debt persists for years while generating maximum interest income for the bank.',
            'The "no grace period" trap: Once you carry a balance, new purchases start accruing interest immediately — there is no interest-free period until you pay the full balance.',
            'Converting outstanding balance to EMI can reduce the interest rate from 36-42% to 12-18% — still high, but significantly better.',
            'Stop using the credit card immediately once you are carrying a balance you cannot pay in full. Switch to a debit card or cash for daily expenses.',
            'Consider a balance transfer to a lower-rate card or a personal loan to convert revolving high-interest debt into a structured repayment plan.',
            'Negotiate with your credit card company: Request a lower interest rate, fee waivers, or a hardship plan. They prefer negotiated repayment over defaults.',
            'Warning signs you are heading into a debt spiral: using one card to pay another, taking cash advances, only paying minimums on multiple cards, and hiding debt from family.',
          ],
        },
      ],
    },
  ],
  keyTerms: [
    {
      term: 'EMI (Equated Monthly Installment)',
      definition: 'A fixed monthly payment made to a lender that includes both principal and interest components. Calculated using the formula: EMI = [P x R x (1+R)^N] / [(1+R)^N - 1].',
    },
    {
      term: 'Credit Score',
      definition: 'A numerical representation of creditworthiness based on credit history. FICO (US) ranges from 300-850; CIBIL (India) ranges from 300-900. Higher scores indicate lower risk to lenders.',
    },
    {
      term: 'Debt-to-Income Ratio (DTI)',
      definition: 'The percentage of gross monthly income that goes toward debt payments. Calculated as total monthly debt payments divided by gross monthly income. Lenders prefer DTI below 36%.',
    },
    {
      term: 'Amortization',
      definition: 'The process of spreading loan repayment over time through scheduled periodic payments. In early payments, a larger portion goes to interest; in later payments, more goes to principal.',
    },
    {
      term: 'APR (Annual Percentage Rate)',
      definition: 'The total yearly cost of borrowing expressed as a percentage, including the interest rate plus fees and other charges. APR provides a more accurate cost comparison than the nominal interest rate alone.',
    },
    {
      term: 'Loan-to-Value Ratio (LTV)',
      definition: 'The ratio of the loan amount to the appraised value of the asset being purchased. LTV = Loan Amount / Property Value. Higher LTV means more borrowing and typically requires mortgage insurance.',
    },
    {
      term: 'Debt Consolidation',
      definition: 'Combining multiple debts into a single loan with one monthly payment, ideally at a lower interest rate. Simplifies repayment but does not reduce the principal amount owed.',
    },
    {
      term: 'Balance Transfer',
      definition: 'Moving outstanding debt from one credit card or loan to another, typically to take advantage of a lower interest rate or a 0% promotional APR period.',
    },
    {
      term: 'MCLR / EBLR',
      definition: 'MCLR (Marginal Cost of Funds-based Lending Rate) and EBLR (External Benchmark Lending Rate) are interest rate benchmarks used by Indian banks. EBLR (linked to RBI repo rate) is now mandatory for new floating-rate loans.',
    },
    {
      term: 'Prepayment Penalty',
      definition: 'A fee charged by lenders when a borrower pays off a loan before the scheduled term ends. In India, RBI prohibits prepayment penalties on floating-rate home loans.',
    },
    {
      term: 'Credit Utilization Ratio',
      definition: 'The percentage of available credit that is currently being used. Calculated as total credit card balances divided by total credit limits. Keeping this below 30% is recommended for a healthy credit score.',
    },
    {
      term: 'Debt Avalanche',
      definition: 'A debt repayment strategy where extra payments are directed toward the debt with the highest interest rate first, while making minimum payments on all other debts. Minimizes total interest paid.',
    },
    {
      term: 'Debt Snowball',
      definition: 'A debt repayment strategy where extra payments are directed toward the debt with the smallest balance first, regardless of interest rate. Provides quick psychological wins to build motivation.',
    },
    {
      term: 'Secured Debt',
      definition: 'A loan backed by collateral (an asset like a house, car, or gold). If the borrower defaults, the lender can seize the collateral. Typically carries lower interest rates than unsecured debt.',
    },
    {
      term: 'Floating / Adjustable Rate',
      definition: 'An interest rate that changes periodically based on a benchmark rate (repo rate, SOFR, prime rate). Payments may increase or decrease over the loan term depending on market conditions.',
    },
  ],
  tips: [
    'Always know your total debt picture — list every debt with its balance, interest rate, EMI, and due date. Review this list monthly.',
    'Pay more than the minimum on credit cards every month. Even ₹500 or $50 extra per month makes a significant difference over time due to compound interest.',
    'Build a small emergency fund (3-6 months of expenses) alongside debt repayment to avoid falling back into debt when unexpected expenses arise.',
    'Before taking any new loan, calculate the total cost of borrowing (principal + total interest + fees) — not just the monthly EMI.',
    'Check your credit report from all bureaus at least once a year and dispute any errors immediately — a single reporting error can cost you thousands in higher interest rates.',
    'When choosing between debt avalanche and snowball methods, pick the one you will stick with. Consistency matters more than mathematical optimization.',
    'Negotiate with your lenders — interest rate reductions, fee waivers, and flexible payment plans are often available but rarely offered proactively.',
    'Avoid taking new debt to pay off existing debt unless it genuinely reduces your overall interest rate and you have a concrete repayment plan.',
    'For home loans, make at least one extra EMI payment per year directed entirely toward principal — this can reduce your loan tenure by 3-5 years on a 20-year loan.',
    'Never co-sign or guarantee a loan unless you are fully prepared and financially able to repay the entire amount yourself.',
    'Keep your credit utilization below 30% of your total credit limit. If you need to make a large purchase, pay it off before the statement closing date.',
    'If you are struggling with debt, contact a nonprofit credit counseling agency early — waiting until accounts are delinquent limits your options significantly.',
  ],
  faqs: [
    {
      question: 'Should I pay off debt or invest my surplus money?',
      answer: 'Compare the after-tax interest rate on your debt with the expected after-tax return on investments. If your debt is at 12% and expected investment returns are 10%, pay off the debt first — it is a guaranteed 12% return. However, always contribute enough to capture employer 401(k) matches or EPF matching first, as that is an immediate 100% return. For low-interest debt (home loan at 7-8%), a balanced approach — invest while making regular prepayments — often works best.',
    },
    {
      question: 'What is the fastest way to improve my credit score?',
      answer: 'The fastest improvements come from: (1) Paying down credit card balances to below 30% utilization — this can improve your score within one billing cycle. (2) Getting errors removed from your credit report via disputes. (3) Becoming an authorized user on a family member\'s old, well-maintained account. (4) Setting up autopay to ensure no missed payments going forward. Most strategies take 3-6 months to show significant results, but reducing utilization can show within 30 days.',
    },
    {
      question: 'Is it better to choose a fixed or floating rate on a home loan?',
      answer: 'In India, floating rates are generally recommended because: (1) They are 0.5-1.5% lower than fixed rates initially. (2) RBI prohibits prepayment penalties on floating-rate loans. (3) If rates drop, you benefit automatically. Choose fixed rates only if you need absolute payment certainty and are in a low-rate environment. In the US, 30-year fixed mortgages are popular because rate differentials are smaller and they offer complete payment stability for the entire loan term.',
    },
    {
      question: 'Should I prepay my home loan or invest in mutual funds?',
      answer: 'If your home loan rate is 8.5% and you expect 12-14% long-term equity returns, investing may yield more. However, home loan prepayment gives a guaranteed, risk-free return equal to your loan rate, plus the psychological benefit of reduced debt. A balanced approach works well: increase your EMI by 5-10% annually and invest the rest through SIPs. Also consider the tax implications — home loan interest up to ₹2 lakh is deductible (Section 24b), which reduces the effective cost of the loan.',
    },
    {
      question: 'How do I get out of a credit card debt spiral?',
      answer: 'Step 1: Stop using the credit card immediately — switch to debit card or cash. Step 2: Call your credit card company to negotiate a lower interest rate or hardship plan. Step 3: Consider converting the outstanding balance to a lower-rate EMI plan. Step 4: If you have multiple cards, use either the avalanche (highest rate first) or snowball (smallest balance first) method. Step 5: Explore balance transfer to a lower-rate card or taking a personal loan at a lower rate to pay off the card. Step 6: Cut expenses aggressively and direct all surplus to debt repayment.',
    },
    {
      question: 'What happens if I default on a loan in India?',
      answer: 'Defaulting triggers several consequences: (1) Your CIBIL score drops significantly (by 75-100+ points), making future borrowing difficult. (2) Late payment fees and penal interest charges accumulate. (3) After 90 days of non-payment, the account is classified as NPA (Non-Performing Asset). (4) For secured loans, the lender can initiate recovery through the SARFAESI Act — seizing and auctioning the collateral. (5) For unsecured loans, the lender may engage recovery agents (regulated by RBI) or file a civil suit. (6) The default stays on your credit report for 7 years. Contact your lender at the first sign of difficulty — restructuring options exist.',
    },
  ],
};
