import type { EngineData } from '../types';

export const economicsMarketEngine: EngineData = {
  category: 'economics-market',
  title: 'Economics & Market Analysis',
  description: 'Comprehensive guide to macroeconomics, interest rates, market cycles, economic indicators, and global market analysis.',
  topics: [
    {
      name: 'Macroeconomic Fundamentals',
      description: 'Key concepts that drive the overall economy and influence financial markets.',
      details: [
        'GDP (Gross Domestic Product): Total value of goods and services produced in a country. Primary measure of economic health.',
        'GDP growth rate: 2-3% is healthy for developed economies, 5-8% for developing economies like India.',
        'Inflation: Sustained increase in general price levels. Measured by CPI (Consumer Price Index) and WPI (Wholesale Price Index in India).',
        'Target inflation: RBI targets 4% (±2%) for India. US Federal Reserve targets 2%. Moderate inflation is healthy; deflation or hyperinflation is harmful.',
        'Unemployment rate: Percentage of the labor force actively seeking but unable to find work. Natural rate of unemployment is 4-5%.',
        'Fiscal policy: Government spending and taxation decisions. Expansionary (more spending/lower taxes) vs. Contractionary (less spending/higher taxes).',
        'Monetary policy: Central bank actions to control money supply and interest rates. Tools: Policy rates, open market operations, reserve requirements.',
        'Balance of trade: Exports minus imports. Trade surplus (positive) strengthens currency; trade deficit (negative) weakens it.',
        'Current account deficit/surplus: Broader measure including trade balance, income from abroad, and transfers.',
        'Purchasing Power Parity (PPP): Exchange rate adjustment that equalizes the purchasing power of different currencies.',
      ],
    },
    {
      name: 'Interest Rates',
      description: 'How central bank rates influence the economy, markets, and personal finances.',
      details: [
        'Central bank policy rates: Fed Funds Rate (US Federal Reserve), Repo Rate (RBI, India), Bank Rate (Bank of England).',
        'RBI Repo Rate: The rate at which RBI lends to commercial banks. As of 2024, around 6.5%. Determines the baseline for all lending rates.',
        'Federal Funds Rate: The rate at which US banks lend to each other overnight. Influences all US interest rates.',
        'Rate cuts stimulate economy: Cheaper borrowing → more spending and investment → economic growth → stock market generally rises.',
        'Rate hikes cool economy: Expensive borrowing → less spending → lower inflation → bond yields rise, stock market may fall.',
        'Yield curve: Plot of bond yields across different maturities. Normal (upward sloping) indicates economic growth expectations.',
        'Inverted yield curve: Short-term rates exceed long-term rates. Historically one of the most reliable recession predictors.',
        'Real interest rate = Nominal interest rate - Inflation rate. Negative real rates erode savings purchasing power.',
        'MCLR (Marginal Cost of Funds Lending Rate — India): Benchmark for bank lending rates, linked to RBI policy rate.',
        'Impact on investments: Rate hikes → bond prices fall, bank FD rates rise, equity valuations may compress. Rate cuts → opposite.',
        'Central banks use forward guidance — communicating future rate intentions to manage market expectations.',
      ],
    },
    {
      name: 'Market Cycles',
      description: 'Recurring patterns of expansion and contraction in financial markets and the economy.',
      details: [
        'Business cycle phases: Expansion → Peak → Contraction (Recession) → Trough → Recovery → Expansion.',
        'Bull market: Extended period of rising prices (typically 20%+ gain from recent low). Average bull market lasts 4-5 years.',
        'Bear market: Extended period of falling prices (typically 20%+ decline from recent high). Average bear market lasts 9-16 months.',
        'Market corrections: 10-20% decline from recent highs. Normal and healthy — occur on average once per year.',
        'Recession: Two consecutive quarters of GDP decline. Characterized by rising unemployment, falling production, and reduced spending.',
        'Recovery: Period after a trough when the economy begins growing again. Often the best time for equity investments.',
        'Sector rotation: Different sectors outperform at different cycle stages. Early cycle: Consumer discretionary, financials. Late cycle: Energy, materials. Recession: Consumer staples, healthcare, utilities.',
        'Average S&P 500 bull market return: ~180%. Average bear market decline: ~36%. Markets spend ~80% of time in bull markets.',
        'Nifty 50 historical: Major bears — 2008 (52% decline), 2020 Covid (38% decline). Major bulls — 2009-2020, 2020-2024.',
        'Time in the market beats timing the market: Missing just the 10 best trading days over 20 years can cut returns by more than half.',
      ],
      subtopics: [
        {
          name: 'Market Bubbles and Crashes',
          description: 'Historical episodes of extreme market behavior.',
          details: [
            'Tulip Mania (1637): First recorded speculative bubble. Dutch tulip bulb prices soared before collapsing spectacularly.',
            'South Sea Bubble (1720): Shares of the South Sea Company inflated on promises of monopoly trade, then collapsed.',
            'Wall Street Crash (1929): Triggered the Great Depression. Dow fell 89% from peak. Took 25 years to recover.',
            'Dot-com Bubble (1999-2000): Internet company valuations soared on speculation. NASDAQ fell 78% from peak to trough.',
            'Global Financial Crisis (2008): Subprime mortgage crisis caused a global banking/credit crisis. S&P 500 fell 57%.',
            'COVID-19 Crash (2020): Fastest bear market in history (34% decline in 23 days). Also one of the fastest recoveries.',
            'Common bubble characteristics: Rapid price increases, speculation by novice investors, "this time is different" narrative, easy credit, widespread media coverage.',
          ],
        },
      ],
    },
    {
      name: 'Economic Indicators',
      description: 'Key data points used to assess the health and direction of an economy.',
      details: [
        'Leading indicators (predict future activity): PMI (Purchasing Managers Index), consumer confidence, building permits, stock market, yield curve, new business orders.',
        'Coincident indicators (confirm current state): GDP, industrial production, employment, retail sales, personal income.',
        'Lagging indicators (confirm past trends): Unemployment rate, CPI, corporate profits, interest rates, bank lending.',
        'PMI (Purchasing Managers Index): >50 indicates expansion, <50 indicates contraction. Among the most closely watched leading indicators.',
        'CPI (Consumer Price Index): Measures inflation from the consumer\'s perspective. Basket of goods and services.',
        'WPI (Wholesale Price Index): Measures inflation at the wholesale level. More relevant for India\'s economy.',
        'IIP (Index of Industrial Production — India): Measures industrial output and manufacturing activity.',
        'Non-Farm Payrolls (US): Monthly employment data. One of the most market-moving economic releases.',
        'RBI Monetary Policy minutes: Published after each MPC meeting. Markets analyze the voting pattern and stance closely.',
        'FOMC (Federal Open Market Committee) statements: Guide expectations for US monetary policy direction.',
      ],
    },
    {
      name: 'Global Markets',
      description: 'Major world markets, their characteristics, and interconnections.',
      details: [
        'US markets: NYSE and NASDAQ. S&P 500 (500 largest US companies), Dow Jones (30 blue-chips), NASDAQ Composite (tech-heavy).',
        'Indian markets: BSE (Sensex — 30 stocks, oldest Asian exchange est. 1875) and NSE (Nifty 50 — 50 stocks, est. 1992).',
        'European markets: FTSE 100 (UK), DAX (Germany), CAC 40 (France), Euro Stoxx 50 (Eurozone).',
        'Asian markets: Nikkei 225 (Japan), Hang Seng (Hong Kong), Shanghai Composite (China), KOSPI (South Korea).',
        'Emerging markets: Higher growth potential but higher volatility. MSCI Emerging Markets Index includes India, China, Brazil, Taiwan, South Korea.',
        'Forex markets: Largest financial market ($7.5 trillion daily volume). Major pairs: EUR/USD, USD/JPY, GBP/USD. USD/INR for India.',
        'Commodity markets: Gold (safe haven, inflation hedge), Crude oil (impacts transportation, manufacturing costs), Agricultural commodities.',
        'Global market correlation: Markets are increasingly interconnected. US market movements often influence other global markets.',
        'FII/FPI flows (India): Foreign Institutional Investor flows significantly impact Indian market direction. Net FPI buying is bullish; selling is bearish.',
        'DII flows (India): Domestic Institutional Investor flows — mutual funds, insurance companies — have become an important stabilizing force.',
      ],
    },
    {
      name: 'Monetary and Fiscal Policy Impact',
      description: 'How government and central bank policies affect markets and personal finances.',
      details: [
        'Quantitative Easing (QE): Central bank buys government bonds to inject money into the economy. Lowers long-term interest rates, boosts asset prices.',
        'Quantitative Tightening (QT): Central bank reduces its bond holdings, withdrawing liquidity from the financial system.',
        'Government bonds: When central bank buys bonds, prices rise and yields fall. When it sells, prices fall and yields rise.',
        'Currency impact: Higher interest rates attract foreign capital → currency appreciation. Lower rates → capital outflows → currency depreciation.',
        'Fiscal deficit: Government spending exceeds revenue. High fiscal deficit can lead to inflation and higher interest rates.',
        'Stimulus packages: Government spending to boost economic activity during downturns. Can be fiscal (direct spending) or monetary (rate cuts, QE).',
        'Austerity: Reducing government spending to lower fiscal deficit. Can slow economic growth in the short term.',
        'Budget impact on markets (India): Union Budget announcements on taxes, spending, and reforms significantly move Indian markets.',
      ],
    },
    {
      name: 'Currency Risk & Foreign Exchange',
      description: 'Understanding currency risk and its impact on investments and business.',
      details: [
        'Currency risk (exchange rate risk): The risk that changes in exchange rates will reduce the value of investments denominated in foreign currencies',
        'USD/INR impact on Indian investors: When rupee depreciates (e.g., ₹75→₹85), US investments gain in INR terms, but imported goods become expensive',
        'Types: Transaction risk (short-term, specific trades), Translation risk (converting foreign subsidiary financials), Economic risk (long-term competitive position)',
        'Hedging with forwards: Lock in a future exchange rate today. Indian exporters use USD/INR forwards to guarantee INR realization on future dollar inflows',
        'Hedging with options: Buy a put option on the foreign currency for downside protection while keeping upside potential. Costs a premium',
        'Currency ETFs: Invest in foreign currency exposure. WisdomTree Bloomberg U.S. Dollar Bullish Fund, CurrencyShares Euro Trust',
        'Natural hedging: Match foreign currency revenues with foreign currency expenses. Reduces need for financial hedging instruments',
        'Carry trade: Borrow in low-interest-rate currency (JPY, CHF), invest in high-interest-rate currency (INR, BRL). Profits from rate differential but risky if exchange rates move adversely',
        'Impact on equity returns: A US investor in Indian stocks earns equity return ± INR/USD change. Currency can add or subtract 5-15% annually',
        'RBI intervention: RBI manages excessive INR volatility through forex reserves ($600B+). Buys/sells dollars to stabilize the rupee',
        'Dollarization risk for Indian investors: Holding too many INR-only assets when future liabilities may be dollar-linked (children\'s foreign education, medical treatment abroad)',
        'Diversification benefit: Holding assets in multiple currencies provides natural diversification as currencies don\'t move in lockstep',
      ],
    },
  ],
  keyTerms: [
    { term: 'GDP', definition: 'Gross Domestic Product. Total monetary value of all finished goods and services produced within a country in a specific period.' },
    { term: 'Inflation', definition: 'The rate at which the general level of prices for goods and services rises, eroding purchasing power.' },
    { term: 'CPI', definition: 'Consumer Price Index. Measures the average change in prices paid by consumers for a basket of goods and services.' },
    { term: 'Repo Rate', definition: 'The rate at which the central bank (RBI) lends money to commercial banks. The primary monetary policy tool in India.' },
    { term: 'Fed Funds Rate', definition: 'The interest rate at which US banks lend reserves to each other overnight. Set by the Federal Reserve.' },
    { term: 'Yield Curve', definition: 'A graph plotting bond yields across different maturities. Its shape indicates market expectations for growth and rates.' },
    { term: 'PMI', definition: 'Purchasing Managers Index. A leading economic indicator based on surveys of purchasing managers. Above 50 indicates expansion.' },
    { term: 'Bull Market', definition: 'A financial market in which prices are rising or expected to rise, typically defined as a 20%+ increase from recent lows.' },
    { term: 'Bear Market', definition: 'A financial market in which prices are falling, typically defined as a 20%+ decline from recent highs.' },
    { term: 'Recession', definition: 'A significant decline in economic activity lasting more than a few months, typically defined as two consecutive quarters of GDP decline.' },
    { term: 'Quantitative Easing', definition: 'Central bank policy of purchasing government securities to increase money supply, lower interest rates, and stimulate the economy.' },
    { term: 'FII/FPI', definition: 'Foreign Institutional Investors / Foreign Portfolio Investors. Foreign entities investing in a country\'s securities markets.' },
    { term: 'Fiscal Deficit', definition: 'The difference between total government revenue and total government expenditure. Indicates government borrowing needs.' },
  ],
  tips: [
    'Follow key economic indicators (PMI, CPI, GDP, employment data) to understand the economic environment for your investments.',
    'Don\'t try to time markets based on economic data alone — by the time data is published, markets have often already priced it in.',
    'Understand where we are in the business cycle to inform (not dictate) asset allocation decisions.',
    'Interest rate changes affect different asset classes differently — understand the transmission mechanism.',
    'Watch the yield curve — an inverted yield curve has preceded every US recession since 1955.',
    'FPI flows are a key driver of Indian market sentiment — track net FPI buying/selling trends.',
    'Diversify globally — different economies grow at different rates and have different market cycles.',
    'Inflation is the silent wealth destroyer — ensure your investments grow faster than inflation.',
    'Read RBI monetary policy statements and US Fed minutes for insights into future policy direction.',
    'Economic cycles are normal — recessions are temporary. Stay invested through cycles for long-term wealth creation.',
  ],
  faqs: [
    {
      question: 'How do interest rate changes affect my investments?',
      answer: 'Rate hikes: Bond prices fall (yields rise), fixed deposit rates increase, borrowing costs rise (EMIs increase), equity markets may face pressure (higher discount rates reduce valuations), currency may strengthen. Rate cuts: Opposite effects — bond prices rise, FD rates fall, borrowing becomes cheaper, equity markets tend to benefit, currency may weaken. Strategy: In a rising rate environment, favor shorter-duration bonds, floating rate instruments, and value stocks. In a falling rate environment, favor longer-duration bonds and growth stocks.',
    },
    {
      question: 'What causes stock market crashes?',
      answer: 'Crashes are caused by a combination of factors: 1) Excessive valuations creating bubbles. 2) Economic shocks (recessions, pandemics, wars). 3) Credit/banking crises (2008). 4) Sudden monetary policy changes. 5) Panic selling and herd behavior amplifying declines. 6) Leverage and margin calls forcing selling. Historical pattern: Markets always recover eventually — the S&P 500 has recovered from every crash in history. Average recovery time: 1-4 years. The best strategy is to stay invested, continue SIPs, and even increase investment during crashes if you have the capacity.',
    },
    {
      question: 'What is the relationship between inflation and investments?',
      answer: 'Inflation erodes purchasing power. To build real wealth, investments must beat inflation. At 6% inflation (India avg), ₹1 lakh becomes worth ₹55,839 in 10 years in real terms. Asset class behavior: Equities generally beat inflation over long periods (Nifty 50 ~12% CAGR vs ~6% inflation). Bonds and FDs may barely keep pace. Gold is a traditional inflation hedge. Real estate tends to match or beat inflation. Cash and savings accounts lose purchasing power. Strategy: Maintain a significant equity allocation for long-term inflation protection.',
    },
    {
      question: 'How do global events affect Indian markets?',
      answer: 'Indian markets are influenced by global events through several channels: 1) FPI flows — global risk-off sentiment leads to FPI selling in emerging markets. 2) Oil prices — India imports ~85% of its crude oil; higher prices hurt the economy. 3) US Fed policy — rate hikes lead to capital flowing from emerging to developed markets. 4) US dollar strength — a strong dollar pressures the rupee and emerging market assets. 5) Global supply chains — disruptions affect Indian exports and imports. 6) Geopolitical tensions — wars, trade disputes affect sentiment. However, strong domestic fundamentals, DII flows, and India-specific reforms can partially decouple Indian markets from global trends.',
    },
  ],
};
