import type { EngineData } from '../types';

export const estatePlanningEngine: EngineData = {
  category: 'estate-planning',
  title: 'Estate Planning',
  description: 'Comprehensive guide to wills, trusts, succession planning, wealth transfer strategies, power of attorney, probate, and estate planning considerations for both the US and Indian contexts.',
  topics: [
    {
      name: 'Wills',
      description: 'A will is a legally binding document that directs how your assets are distributed after death and names guardians for minor children.',
      details: [
        'A will (testament) is the cornerstone of any estate plan — it specifies who receives your property, who manages your estate (executor/personal representative), and who cares for your minor children.',
        'Dying without a valid will is called intestacy — the state or country\'s default laws determine who inherits, which may not match your wishes.',
        'A valid will generally requires the testator to be of legal age (18 in most US states, 21 in India under Indian Succession Act), be of sound mind, and sign the document voluntarily.',
        'Most US states require two disinterested witnesses who watch the testator sign and then sign the will themselves. Some states (e.g., Colorado, Indiana) also recognize holographic (handwritten) wills without witnesses.',
        'A will only takes effect upon death and goes through probate — a court-supervised process to validate the will and oversee distribution.',
        'Wills are revocable during the testator\'s lifetime — they can be updated via a codicil (amendment) or replaced entirely with a new will.',
        'Assets with designated beneficiaries (life insurance, retirement accounts, POD/TOD accounts) pass outside the will directly to the named beneficiary.',
        'Joint tenancy with right of survivorship and community property with right of survivorship also bypass the will — ownership transfers automatically to the surviving co-owner.',
        'A will should be reviewed and potentially updated after major life events: marriage, divorce, birth of a child, significant asset changes, or moving to a different state/country.',
        'Self-proving affidavits (notarized statements attached to the will) can streamline probate by eliminating the need to locate witnesses later.',
      ],
      subtopics: [
        {
          name: 'Types of Wills',
          description: 'Different forms of wills serving various estate planning needs.',
          details: [
            'Simple Will: The most common type — straightforward distribution of assets to named beneficiaries. Best for smaller or uncomplicated estates.',
            'Testamentary Trust Will: Creates one or more trusts upon the testator\'s death. Used to manage assets for minor children, spendthrift beneficiaries, or to control distribution timing.',
            'Joint Will: A single will shared by two people (typically spouses) that becomes irrevocable upon the first death. Largely discouraged by estate planning attorneys due to inflexibility.',
            'Mirror/Mutual Wills: Separate wills by spouses with matching provisions — each leaves everything to the other, then to the same final beneficiaries. More flexible than a joint will.',
            'Living Will (Advance Directive): Not a property distribution document — it specifies medical treatment preferences if you become incapacitated (e.g., life support, resuscitation). Legally distinct from a standard will.',
            'Holographic Will: Entirely handwritten and signed by the testator, often without witnesses. Recognized in about half of US states and in India. Prone to challenges due to ambiguity.',
            'Nuncupative (Oral) Will: A verbal will declared before witnesses, usually only valid in very limited circumstances (e.g., imminent death in military service). Recognized in very few US jurisdictions.',
            'Pour-Over Will: Works in conjunction with a living trust — any assets not already in the trust are "poured over" into it upon death. Still goes through probate for the pour-over assets.',
          ],
        },
        {
          name: 'US Intestacy Laws',
          description: 'Default inheritance rules when someone dies without a valid will in the United States.',
          details: [
            'Each US state has its own intestacy statute, but common patterns apply: the surviving spouse and children are primary heirs.',
            'Community property states (AZ, CA, ID, LA, NV, NM, TX, WA, WI): Surviving spouse typically inherits all community property; separate property may be split with children.',
            'Common law states: Surviving spouse usually receives one-third to one-half of the estate, with children splitting the remainder.',
            'If no spouse: Children inherit equally. If no children: Parents inherit. If no parents: Siblings, then extended relatives in order of closeness.',
            'If absolutely no heirs can be found, the estate escheats (reverts) to the state government.',
            'Unmarried partners, stepchildren, and close friends receive nothing under intestacy unless legally adopted or otherwise qualifying.',
            'The Uniform Probate Code (UPC), adopted in some form by about 18 states, provides a standardized framework for intestate succession.',
            'Intestacy can result in unintended beneficiaries, higher legal costs, and family disputes — having a will avoids these outcomes.',
          ],
        },
        {
          name: 'Indian Will and Intestacy Rules',
          description: 'Legal framework for wills and intestate succession in India.',
          details: [
            'In India, any person of sound mind who is a major (18+ years; 21+ under Indian Succession Act guardianship) can make a will.',
            'Indian wills require the testator\'s signature and attestation by two or more witnesses who must also sign. Witnesses should not be beneficiaries.',
            'Will registration is optional but strongly recommended — registered wills carry stronger evidentiary value and are harder to challenge. Registration is done at the Sub-Registrar\'s office.',
            'Hindu Succession Act, 1956 (amended 2005) governs intestate succession for Hindus, Buddhists, Jains, and Sikhs. Gives daughters equal coparcenary rights in ancestral property.',
            'Indian Succession Act, 1925 governs wills and intestate succession for Christians, Parsis, and those married under the Special Marriage Act.',
            'Muslim personal law governs inheritance for Muslims — a Muslim can bequeath only up to one-third of the estate by will; the remaining two-thirds is distributed per Sharia inheritance rules.',
            'Ancestral property (joint family property under Hindu law) has special rules — coparceners have a birthright share, and a will can only dispose of the testator\'s own share.',
            'Nominee vs. legal heir: A nominee (on bank accounts, insurance, investments) is a custodian, not automatically the owner. Legal heirs determined by will or succession law are the true beneficiaries.',
          ],
        },
      ],
    },
    {
      name: 'Trusts',
      description: 'A trust is a fiduciary arrangement where a trustee holds and manages assets on behalf of beneficiaries, offering control, privacy, and potential tax benefits.',
      details: [
        'A trust involves three parties: the grantor/settlor (who creates and funds it), the trustee (who manages the assets), and the beneficiary/beneficiaries (who benefit from the assets).',
        'Unlike a will, a properly funded living trust avoids probate — assets held in the trust pass directly to beneficiaries without court involvement.',
        'Trusts provide privacy — unlike wills that become public record during probate, trust documents and asset details remain confidential.',
        'A trust can include detailed instructions for distributions: age-based milestones, incentive provisions (e.g., matching earned income), or discretionary distributions by the trustee.',
        'Trusts can protect assets from beneficiaries\' creditors, lawsuits, and even divorce proceedings when structured as spendthrift trusts.',
        'Funding the trust is critical — an unfunded or partially funded trust provides no benefit for the assets left outside it. Assets must be retitled in the trust\'s name.',
        'Trusts can own real estate, bank accounts, brokerage accounts, business interests, life insurance policies, and other assets.',
        'Trusts are subject to their own tax rules — in the US, trusts reach the highest income tax bracket (37%) at just $14,450 of income (2024), making distributions to beneficiaries tax-advantageous.',
        'In India, trusts are governed by the Indian Trusts Act, 1882 (private trusts) and relevant sections of the Income Tax Act. Public charitable trusts are registered under state-specific laws.',
        'A corporate trustee (bank or trust company) provides professional management and continuity but charges annual fees, typically 0.5%-1.5% of trust assets.',
      ],
      subtopics: [
        {
          name: 'Revocable Living Trust',
          description: 'A flexible trust that can be modified or dissolved by the grantor during their lifetime.',
          details: [
            'The grantor retains full control — can amend terms, change beneficiaries, add/remove assets, or revoke the trust entirely at any time while competent.',
            'No separate tax ID needed during the grantor\'s lifetime — income is reported on the grantor\'s personal tax return (it\'s a "grantor trust" for tax purposes).',
            'Primary benefit: Avoids probate. At the grantor\'s death, the successor trustee distributes assets per the trust terms without court involvement.',
            'Provides incapacity planning — if the grantor becomes incapacitated, the successor trustee can manage assets seamlessly without a court-appointed conservator/guardian.',
            'Does NOT provide asset protection from the grantor\'s creditors during their lifetime, since the grantor retains control.',
            'Does NOT reduce estate taxes — assets in a revocable trust are still included in the grantor\'s taxable estate.',
            'Typically becomes irrevocable upon the grantor\'s death, at which point it may split into sub-trusts (e.g., an A-B trust for married couples).',
            'Cost to establish: $1,500-$5,000+ for attorney fees in the US, depending on complexity and jurisdiction.',
          ],
        },
        {
          name: 'Irrevocable Trust',
          description: 'A trust that generally cannot be modified or revoked once established, offering estate tax and asset protection benefits.',
          details: [
            'Once assets are transferred to an irrevocable trust, the grantor relinquishes ownership and control — the transfer is essentially a completed gift.',
            'Assets are removed from the grantor\'s taxable estate, potentially saving federal estate taxes (applicable if estate exceeds the exemption — $13.61 million per person in 2024).',
            'Provides strong asset protection — since the grantor no longer owns the assets, they are generally shielded from the grantor\'s creditors and lawsuits.',
            'An Irrevocable Life Insurance Trust (ILIT) holds life insurance policies outside the estate, keeping the death benefit from being subject to estate tax.',
            'Grantor Retained Annuity Trust (GRAT): The grantor receives annuity payments for a set term; remaining assets pass to beneficiaries at potentially reduced gift tax cost.',
            'Qualified Personal Residence Trust (QPRT): Transfers a home to beneficiaries at a discounted gift tax value while the grantor retains the right to live there for a term of years.',
            'Irrevocable trusts receive their own tax ID (EIN) and file separate tax returns (Form 1041 in the US).',
            'Some irrevocable trusts include limited powers of appointment or trust protector provisions that allow certain modifications under specific circumstances.',
          ],
        },
        {
          name: 'Special Needs and Charitable Trusts',
          description: 'Specialized trust structures for protecting disabled beneficiaries and advancing charitable goals.',
          details: [
            'Special Needs Trust (SNT/Supplemental Needs Trust): Provides for a disabled beneficiary without disqualifying them from government benefits like Medicaid/SSI in the US or disability benefits in India.',
            'First-party SNT: Funded with the disabled person\'s own assets (e.g., a lawsuit settlement). Must include a Medicaid payback provision upon the beneficiary\'s death.',
            'Third-party SNT: Funded by someone other than the beneficiary (parents, grandparents). No Medicaid payback requirement — remaining assets can pass to other family members.',
            'ABLE Accounts (US): Tax-advantaged savings accounts for individuals disabled before age 26 — up to $100,000 without affecting SSI eligibility (as of ABLE Age Adjustment Act).',
            'Charitable Remainder Trust (CRT): Provides income to the grantor or other beneficiaries for life or a term of years, with the remainder going to charity. Offers an immediate income tax deduction.',
            'Charitable Lead Trust (CLT): The inverse of a CRT — charity receives income for a period, then remaining assets pass to non-charitable beneficiaries at reduced gift/estate tax cost.',
            'Donor-Advised Fund (DAF): Not technically a trust, but a charitable giving vehicle where the donor gets an immediate tax deduction and recommends grants to charities over time.',
            'Pooled Trust: A special needs trust managed by a nonprofit organization, pooling investments from multiple beneficiaries while maintaining separate accounts. Useful when there is no suitable individual trustee.',
          ],
        },
      ],
    },
    {
      name: 'Succession Planning',
      description: 'Strategies for ensuring the smooth transition of business ownership, leadership, and wealth across generations.',
      details: [
        'Succession planning is critical for business owners — approximately 70% of family businesses fail to survive into the second generation, often due to inadequate planning.',
        'A succession plan should address three dimensions: ownership transfer (who gets the equity), management transition (who runs the business), and estate tax implications.',
        'Start planning early — a comprehensive succession plan typically takes 5-10 years to implement fully, including leadership development and gradual ownership transfer.',
        'Business valuation is a foundational step — common methods include discounted cash flow (DCF), comparable company analysis, and asset-based approaches.',
        'Minority interest and lack-of-marketability discounts can reduce the taxable value of transferred business interests by 20-40% when gifting to family members.',
        'Key person insurance provides liquidity to the business if a critical owner or executive dies or becomes disabled, funding the transition period.',
        'A written succession plan should include emergency provisions — who steps in immediately if the owner dies or is incapacitated unexpectedly.',
        'In India, family businesses often involve Hindu Undivided Family (HUF) structures — succession must account for coparcenary rights, partition rules, and Karta (manager) succession.',
        'Communication is as important as documentation — unclear expectations among family members are a leading cause of failed successions and family disputes.',
        'Consider professional management — bringing in non-family executives can preserve family harmony while ensuring competent business leadership.',
      ],
      subtopics: [
        {
          name: 'Family Business Succession',
          description: 'Transferring a family-owned business to the next generation or other successors.',
          details: [
            'Identify and develop successors early — assess family members\' interest, skills, and aptitude. Not every child wants or is suited to run the family business.',
            'Create a formal development program for successors: education, mentoring, rotational assignments within the business, and outside work experience.',
            'Establish a family governance structure — a family council, family constitution, or family charter that defines roles, decision-making processes, and conflict resolution.',
            'Consider an Employee Stock Ownership Plan (ESOP) if no suitable family successor exists — it provides a market for the owner\'s shares and benefits employees.',
            'Installment sales to family members allow gradual ownership transfer with tax-efficient payment over time, secured by business assets.',
            'Gifting shares using the annual gift tax exclusion ($18,000 per recipient in 2024 in the US) or lifetime exemption can transfer ownership with minimal tax impact.',
            'An Intentionally Defective Grantor Trust (IDGT) can freeze the estate value: the business is sold to the trust, future appreciation occurs outside the estate, and the grantor pays income tax on trust earnings (further reducing the taxable estate).',
            'Non-active family members can receive equivalent value through life insurance proceeds, other assets, or preferred equity with limited voting rights to maintain fairness.',
          ],
        },
        {
          name: 'Buy-Sell Agreements',
          description: 'Legally binding contracts that govern the transfer of business interests upon triggering events.',
          details: [
            'A buy-sell agreement defines what happens to an owner\'s interest upon death, disability, retirement, divorce, or voluntary departure — preventing unwanted outsiders from becoming co-owners.',
            'Cross-purchase agreement: Remaining owners buy the departing owner\'s share. Works well with few owners. Each owner holds insurance on the others to fund the purchase.',
            'Entity-purchase (redemption) agreement: The business entity itself buys back the departing owner\'s share. Simpler with many owners but may have different tax consequences.',
            'Hybrid (wait-and-see) agreement: The entity has the first right to purchase, with remaining owners picking up any unpurchased interest. Combines benefits of both approaches.',
            'Funding mechanisms: Life insurance (most common for death events), disability buy-out insurance, sinking funds, installment payments, or third-party financing.',
            'Valuation method must be agreed upon upfront: fixed price (updated annually), formula-based (e.g., multiple of earnings), or independent appraisal at the time of the triggering event.',
            'The agreement should be reviewed and updated regularly — at minimum every 2-3 years — to ensure the valuation and terms reflect current business realities.',
            'In India, shareholders\' agreements and partnership deeds serve similar functions. Right of first refusal, tag-along, and drag-along clauses are commonly used in Indian private companies.',
          ],
        },
      ],
    },
    {
      name: 'Wealth Transfer Strategies',
      description: 'Tax-efficient methods for transferring assets to the next generation and to charitable causes while minimizing estate, gift, and generation-skipping transfer taxes.',
      details: [
        'The US federal estate and gift tax exemption is $13.61 million per individual ($27.22 million per married couple) in 2024, with a top rate of 40%. This exemption is unified — lifetime gifts reduce the available estate tax exemption.',
        'The current high exemption is set to sunset after December 31, 2025, potentially reverting to approximately $6-7 million per person (adjusted for inflation) under the Tax Cuts and Jobs Act sunset provision.',
        'Annual gift tax exclusion: $18,000 per recipient per year (2024) — gifts within this limit do not count against the lifetime exemption and require no gift tax return.',
        'Married couples can split gifts — effectively giving $36,000 per recipient per year without using any lifetime exemption.',
        'Direct payments for medical expenses or tuition (paid directly to the institution) are exempt from gift tax with no dollar limit — they do not count toward the annual or lifetime exclusion.',
        'India does not have an estate tax or inheritance tax (abolished in 1985). However, gifts exceeding ₹50,000 to non-relatives may be taxable as income in the recipient\'s hands.',
        'Step-up in cost basis (US): Inherited assets receive a cost basis equal to the fair market value at the date of death, eliminating capital gains tax on appreciation during the decedent\'s lifetime.',
        'In India, the cost basis for inherited property is the original cost to the previous owner (with indexation benefits where applicable), not the value at the time of inheritance.',
        'Portability (US): A surviving spouse can use the deceased spouse\'s unused estate tax exemption (Deceased Spousal Unused Exclusion, or DSUE) by filing a timely estate tax return.',
        'Wealth transfer planning should coordinate with income tax planning — sometimes paying income tax now (e.g., Roth conversions) is more efficient than deferring and subjecting the estate to both income and estate taxes.',
      ],
      subtopics: [
        {
          name: 'Gifting Strategies',
          description: 'Systematic approaches to transferring wealth during the grantor\'s lifetime using gift tax exclusions and exemptions.',
          details: [
            'Annual exclusion gifting: A married couple with three children and three grandchildren can gift $36,000 each to six people — $216,000 per year — with zero gift tax impact.',
            'Gifts of appreciating assets are more tax-efficient than gifts of cash — future appreciation occurs outside the donor\'s estate.',
            'Gifts to a 529 education savings plan can be front-loaded: up to 5 years of annual exclusions at once ($90,000 per beneficiary, $180,000 for a married couple in 2024) without using the lifetime exemption.',
            'Crummey trusts: Irrevocable trusts with temporary withdrawal rights for beneficiaries, qualifying contributions as present-interest gifts eligible for the annual exclusion.',
            'Grantor Retained Annuity Trust (GRAT): A zeroed-out GRAT allows transfer of asset appreciation to beneficiaries with minimal gift tax cost — highly effective for rapidly appreciating assets.',
            'Family loans at the Applicable Federal Rate (AFR) — lending to family members at IRS minimum interest rates is not considered a gift, and any return on the borrowed funds above the AFR benefits the borrower tax-free.',
            'In India, gifts to specified relatives (spouse, children, siblings, parents, etc.) are fully exempt from income tax regardless of amount.',
            'Gifts of property in India: If a donor gifts immovable property valued above ₹50,000 to a non-relative, the entire value (not just the excess) is taxable as income for the recipient.',
          ],
        },
        {
          name: 'Generation-Skipping Transfer (GST) Strategies',
          description: 'Techniques for transferring wealth to grandchildren and later generations while minimizing additional transfer taxes.',
          details: [
            'The Generation-Skipping Transfer Tax (GSTT) is a separate tax on transfers that skip a generation (e.g., grandparent to grandchild), imposed at a flat 40% rate on top of estate/gift tax.',
            'Each individual has a GST exemption equal to the estate tax exemption ($13.61 million in 2024), which can be allocated to trusts or direct transfers.',
            'Dynasty trusts: Trusts designed to last for multiple generations (or perpetually in states without a Rule Against Perpetuities), keeping assets out of each generation\'s taxable estate.',
            'States with no Rule Against Perpetuities or very long trust durations include South Dakota, Nevada, Alaska, Delaware, and New Hampshire — making them popular for dynasty trusts.',
            'GST exemption allocation is critical — failure to properly allocate the exemption on gift tax returns can result in massive unintended tax liability.',
            'A Health and Education Exclusion Trust (HEET) pays medical and educational expenses for grandchildren and later generations without using GST or gift tax exemptions.',
            'GST planning is especially valuable during the current high-exemption period — locking in the $13.61 million GST exemption before the potential 2026 sunset.',
            'In India, there is no generation-skipping transfer tax — direct gifts to grandchildren follow the same income tax rules as gifts to any other person or relative.',
          ],
        },
        {
          name: 'Charitable Giving Vehicles',
          description: 'Structured charitable strategies that provide tax benefits while supporting philanthropic goals.',
          details: [
            'Donor-Advised Fund (DAF): Contribute assets (cash, stock, etc.) for an immediate tax deduction, then recommend grants to qualified charities over time. No minimum distribution requirement.',
            'Charitable Remainder Trust (CRT): Irrevocable trust paying income to the grantor (or others) for life or up to 20 years. Remainder goes to charity. Two types: Annuity Trust (CRAT) pays a fixed amount; Unitrust (CRUT) pays a fixed percentage of annually revalued assets.',
            'Charitable Lead Trust (CLT): Charity receives annual payments for a set term; remaining assets pass to heirs at reduced gift/estate tax value. Especially effective in low-interest-rate environments.',
            'Private foundation: Provides maximum control over charitable giving but requires annual 5% minimum distribution, has more restrictive deduction limits, and incurs administrative costs.',
            'Qualified Charitable Distribution (QCD): Individuals aged 70.5+ can direct up to $105,000 (2024) annually from their IRA directly to charity — satisfies RMD requirements without increasing taxable income.',
            'Charitable gift of appreciated stock: Donate stock held over one year to avoid capital gains tax entirely while receiving a deduction for the full fair market value.',
            'In India, Section 80G of the Income Tax Act provides deductions for donations to approved charities — 50% or 100% deduction depending on the institution, subject to qualifying limits.',
            'In India, Section 35AC (now expired) and Section 12A/12AA registered trusts have specific rules for tax-exempt charitable organizations receiving donations.',
          ],
        },
      ],
    },
    {
      name: 'Power of Attorney',
      description: 'Legal documents that authorize a designated agent to act on your behalf for financial, legal, or healthcare decisions if you become unable to do so.',
      details: [
        'A Power of Attorney (POA) is a legal instrument where the principal grants authority to an agent (attorney-in-fact) to act on their behalf in specified matters.',
        'Without a POA, if you become incapacitated, your family may need to go through a costly and time-consuming court guardianship/conservatorship proceeding to manage your affairs.',
        'A POA is effective only during the principal\'s lifetime — it automatically terminates upon the principal\'s death, at which point the executor/administrator takes over.',
        'The agent under a POA has a fiduciary duty — they must act in the principal\'s best interest, keep records, avoid conflicts of interest, and not commingle funds.',
        'Choose your agent carefully — select someone trustworthy, financially responsible, and capable of handling the responsibility. Consider naming a successor agent as a backup.',
        'A POA can be broad (general) or limited (specific) — a general POA covers all financial matters, while a limited POA may authorize only a single transaction (e.g., selling a property).',
        'Banks and financial institutions sometimes have their own POA forms and may refuse to honor older or unfamiliar documents — consider getting your institution\'s specific form or updating your POA periodically.',
        'In India, a POA is governed by the Powers of Attorney Act, 1882. It can be general or special, and must be executed on non-judicial stamp paper of prescribed value.',
        'Indian POAs for immovable property transactions must be registered. A general POA for managing property should be registered at the Sub-Registrar\'s office.',
        'Revoking a POA requires written notice to the agent and, ideally, to any third parties who were relying on it. If the POA was registered (as in India), the revocation should also be registered.',
      ],
      subtopics: [
        {
          name: 'Financial Power of Attorney',
          description: 'Authorization for an agent to handle financial and legal matters on the principal\'s behalf.',
          details: [
            'A financial POA typically covers: banking transactions, bill payments, investment management, real estate transactions, tax filing, business operations, insurance claims, and government benefits.',
            'Durable Financial POA: Remains effective even if the principal becomes mentally incapacitated. This is the most recommended type for estate planning purposes.',
            'Springing POA: Becomes effective only upon a specified triggering event, usually the principal\'s incapacity as certified by one or more physicians.',
            'Springing POAs can cause practical delays — banks may require proof of incapacity before honoring the document, creating gaps in financial management.',
            'Most estate planning attorneys now recommend a durable POA (effective immediately) over a springing POA, with trust in the chosen agent to use it only when needed.',
            'The Uniform Power of Attorney Act (adopted by many US states) provides default rules and protections, including mandatory acceptance by financial institutions and liability for agents who breach fiduciary duty.',
            'Consider including specific gifting authority in the POA if the agent may need to continue the principal\'s gift-giving pattern for estate tax planning purposes.',
            'In India, a Power of Attorney for financial matters is commonly used by NRIs (Non-Resident Indians) to manage property and investments through a trusted family member or representative.',
          ],
        },
        {
          name: 'Healthcare Power of Attorney and Advance Directives',
          description: 'Legal documents governing medical decision-making when you cannot speak for yourself.',
          details: [
            'Healthcare POA (also called Healthcare Proxy or Medical POA): Appoints an agent to make medical decisions on your behalf when you are unable to communicate your wishes.',
            'Living Will/Advance Directive: A written document specifying your preferences for end-of-life medical treatment — life support, ventilators, feeding tubes, resuscitation (DNR), organ donation, and palliative care.',
            'A healthcare POA is more flexible than a living will alone — an agent can respond to unanticipated medical situations that a written directive may not cover.',
            'HIPAA Authorization: In the US, a separate document authorizing your healthcare agent (and potentially other family members) to access your protected health information.',
            'The POLST (Physician Orders for Life-Sustaining Treatment) or MOLST form is a medical order (not just a directive) signed by a physician — it carries more immediate authority in emergency situations than a living will.',
            'Your healthcare agent should understand your values, religious beliefs, and quality-of-life preferences — have explicit conversations about your wishes, not just the legal documents.',
            'In India, passive euthanasia and the right to refuse life support were recognized by the Supreme Court in the Common Cause v. Union of India case (2018). Advance directives are now legally valid.',
            'Indian advance directives should be in writing, signed by the person in the presence of two witnesses, and preferably countersigned by a first-class judicial magistrate for legal strength.',
          ],
        },
      ],
    },
    {
      name: 'Probate Process',
      description: 'The court-supervised legal process of validating a will, paying debts, and distributing a deceased person\'s assets to heirs.',
      details: [
        'Probate serves three main purposes: validating the will, providing a forum for creditors to make claims against the estate, and ensuring lawful distribution of assets to beneficiaries.',
        'The executor (named in the will) or administrator (appointed by the court if there is no will) manages the probate process — gathering assets, paying debts and taxes, and distributing the remainder.',
        'Probate is a public process — the will, asset inventory, and financial details become part of the public court record, which is one reason many people prefer trusts for privacy.',
        'Probate timeline varies significantly by jurisdiction: simple estates may be settled in 6-9 months, while complex or contested estates can take 2-5 years or more.',
        'Probate costs typically range from 3-8% of the estate\'s value, including court fees, attorney fees, executor fees, appraisal costs, and accounting fees.',
        'Some states have simplified procedures for small estates — for example, California allows affidavit transfers for estates under $184,500 (2024), and many states have similar thresholds.',
        'Assets that bypass probate: jointly held property, assets in a living trust, accounts with beneficiary designations (life insurance, retirement accounts, POD/TOD accounts), and community property with survivorship rights.',
        'Creditors typically have a limited claims period during probate (4-12 months depending on the state) — after this window, valid claims against the estate may be barred.',
        'Ancillary probate may be required if the decedent owned real property in a state other than their state of domicile, creating additional cost and complexity.',
        'In India, the equivalent of probate is obtaining a "Probate of Will" from the High Court or District Court. In some jurisdictions (e.g., Mumbai, Kolkata, Chennai), probate is mandatory for wills of immovable property.',
      ],
      subtopics: [
        {
          name: 'Avoiding Probate',
          description: 'Strategies and tools for transferring assets outside the probate process.',
          details: [
            'Revocable living trust: The most comprehensive probate avoidance tool — assets titled in the trust pass directly to beneficiaries without court involvement.',
            'Joint tenancy with right of survivorship (JTWROS): Property automatically passes to the surviving co-owner upon death. Common for real estate and bank accounts between spouses.',
            'Payable-on-Death (POD) and Transfer-on-Death (TOD) designations: Bank accounts, brokerage accounts, and in some states, real estate deeds can be set to transfer automatically upon death.',
            'Beneficiary designations on retirement accounts (401(k), IRA), life insurance policies, and annuities transfer these assets directly to named beneficiaries outside probate.',
            'Tenancy by the entirety (available in some states for married couples): A form of joint ownership that also provides creditor protection and automatic survivorship.',
            'Lady Bird deed (enhanced life estate deed): Available in a few states (FL, MI, TX, WV, and others) — allows property transfer at death while retaining full control during life, without probate.',
            'Gifting assets during your lifetime removes them from the probate estate entirely, though gift tax implications must be considered.',
            'In India, probate can be avoided by holding assets jointly, using nominee designations (though nominees are custodians, not owners), and creating a registered trust for major assets.',
          ],
        },
        {
          name: 'Probate Costs and Timelines by Jurisdiction',
          description: 'Comparative overview of how probate expenses and duration vary across jurisdictions.',
          details: [
            'California: Attorney and executor fees are set by statute based on estate value (4% of first $100K, 3% of next $100K, 2% of next $800K, etc.). Probate typically takes 12-18 months.',
            'Florida: Attorney fees are based on a similar statutory schedule. Homestead property has special protections and descent rules that can complicate probate.',
            'New York: Surrogate\'s Court handles probate. Attorney fees are "reasonable" (no statutory schedule), typically 2-5% of the estate. Process takes 9-15 months for uncontested estates.',
            'Texas: Independent administration (if authorized in the will) is faster and cheaper — executor can act without court approval for most actions. Dependent administration is more court-supervised.',
            'States with the Uniform Probate Code (e.g., Colorado, Arizona, Montana) generally have more streamlined, cost-effective probate procedures.',
            'UK: Grant of Probate is required from the Probate Registry. Inheritance tax of 40% applies to estates over £325,000 (nil rate band). Process typically takes 6-12 months.',
            'India: Probate fees vary by state — typically based on the value of the estate (e.g., ad valorem court fees in Maharashtra). The process can take 1-3 years due to court backlogs.',
            'In India, obtaining a Succession Certificate from a civil court is an alternative to probate for movable assets (bank accounts, securities) when there is no will.',
          ],
        },
      ],
    },
    {
      name: 'Estate Planning for the Indian Context',
      description: 'Specific legal frameworks, religious personal laws, and practical considerations unique to estate planning in India.',
      details: [
        'India has no estate tax, inheritance tax, or gift tax (gift tax was abolished in 1998). However, gifts received above ₹50,000 from non-relatives are taxable as income for the recipient.',
        'Multiple personal laws govern succession: Hindu Succession Act (Hindus, Buddhists, Jains, Sikhs), Indian Succession Act (Christians, Parsis), and Muslim Personal Law (Muslims).',
        'The Hindu Succession (Amendment) Act, 2005 gave daughters equal coparcenary rights in ancestral/joint family property — a landmark change that applies to both living and deceased fathers\' property.',
        'Ancestral property (property inherited up to four generations of male lineage in an undivided Hindu family) is distinct from self-acquired property — it has its own rules for division and testamentary disposition.',
        'A Hindu can will away only their individual share of joint family property, not the shares of other coparceners. Self-acquired property can be freely willed to anyone.',
        'Registration of wills in India is done at the Sub-Registrar\'s office under the Registration Act, 1908. While optional, registration significantly strengthens the will\'s legal standing.',
        'Stamp duty on inheritance varies by state in India — some states (e.g., Maharashtra) charge stamp duty on inherited property transfers, while others exempt intra-family inheritance.',
        'NRI estate planning is complex — it involves coordination between Indian laws, the laws of the country of residence/citizenship, and Double Taxation Avoidance Agreements (DTAA).',
        'HUF (Hindu Undivided Family) has a separate tax identity in India — proper HUF planning can split income among family members and provide additional tax deductions.',
        'Digital estate planning is increasingly important — include digital assets, online banking credentials (process, not passwords in the will), social media accounts, and cryptocurrency in your estate plan.',
      ],
      subtopics: [
        {
          name: 'Hindu Succession Act and Ancestral Property',
          description: 'Rules governing intestate succession and ancestral property rights for Hindus under Indian law.',
          details: [
            'Class I heirs (who inherit first in intestacy): Son, daughter, widow, mother, son of a predeceased son, daughter of a predeceased son, widow of a predeceased son, son of a predeceased daughter, daughter of a predeceased daughter, and others.',
            'Class I heirs inherit simultaneously and in equal shares. If a Class I heir has predeceased, their branch representatives (children) inherit their share by representation.',
            'If no Class I heirs exist, property passes to Class II heirs (father, siblings, and their descendants), then to agnates, and finally to cognates.',
            'Coparcenary property (ancestral): Each coparcener (including daughters post-2005 amendment) has an equal undivided share by birth. A coparcener can demand partition at any time.',
            'On the death of a male Hindu coparcener, his share is determined as if a notional partition had taken place immediately before death — this share can be willed.',
            'Self-acquired property of a Hindu male or female can be bequeathed to anyone through a will without any restrictions from the Hindu Succession Act.',
            'A Hindu woman\'s property (whether inherited, gifted, or self-acquired) is her absolute property post-2005 amendment — she has full testamentary power over it.',
            'Partition of HUF property can be total or partial, by metes and bounds, or by dividing the value. An oral partition among family members is legally valid if acted upon.',
          ],
        },
        {
          name: 'Indian Succession Act and Other Personal Laws',
          description: 'Succession rules for Christians, Parsis, Muslims, and those married under the Special Marriage Act in India.',
          details: [
            'Indian Succession Act, 1925 applies to Christians and Parsis for intestate succession, and governs wills for all non-Muslims. Probate of will is mandatory in certain jurisdictions (Kolkata, Mumbai, Chennai).',
            'Christian intestate succession: Spouse receives one-third, children share two-thirds equally. If no children, spouse receives half and the other half goes to the deceased\'s kindred.',
            'Parsi intestate succession: Special rules — spouse and children share equally. If only a spouse survives, they get half (rest to deceased\'s parents). Gender-neutral division among children.',
            'Muslim Personal Law (Hanafi school, most common in India): A Muslim can bequeath only one-third of the net estate by will. The remaining two-thirds is distributed to Quranic heirs in fixed shares.',
            'Muslim inheritance: Daughters receive half the share of sons. Spouse receives one-fourth (if children) or one-half (if no children) for husband; one-eighth or one-fourth for wife. Parents also receive fixed shares.',
            'Under the Special Marriage Act, 1954: Couples married under this act follow the Indian Succession Act for intestate succession, regardless of their religion.',
            'Wills by Muslims: Valid even if oral (though written is strongly advisable). Does not require attestation by witnesses under Muslim law, but two witnesses are recommended for evidentiary purposes.',
            'In Goa, the Portuguese Civil Code still applies — Goa follows a community property system for married couples, and forced heirship rules limit the testator\'s freedom to disinherit children.',
          ],
        },
        {
          name: 'Nominee vs. Legal Heir in India',
          description: 'The critical distinction between nomination and inheritance under Indian law.',
          details: [
            'A nominee is a person appointed to receive assets (bank accounts, insurance, mutual funds, shares) on the holder\'s death — but a nominee is legally a custodian/trustee, NOT the owner.',
            'The Supreme Court of India has repeatedly held that nomination does not override succession law — the nominee holds assets in trust for the legal heirs as determined by will or succession law.',
            'Exception: Under the Insurance Act, if the nominee is a beneficial nominee (parent, spouse, or child nominated with an express intent to benefit), the nominee has a beneficial interest in the insurance proceeds.',
            'For bank accounts and fixed deposits: Banks pay the nominee for operational convenience, but the nominee must distribute to legal heirs as per the will or succession law.',
            'For shares and demat accounts: SEBI regulations allow transmission to nominees, but the nominee holds them as a trustee for legal heirs. Disputes are resolved by civil courts.',
            'For mutual funds: SEBI and AMFI allow payment to nominees, but the nominee is expected to distribute per succession law. Nomination simplifies the claims process but does not confer ownership.',
            'To avoid disputes: Clearly specify the distribution of each asset in a valid will, ensure nominations are updated and consistent with the will, and communicate your intentions to the family.',
            'Obtaining a Succession Certificate or Letters of Administration from a civil court is often required by institutions to transfer assets to legal heirs when there is no will or when the will is contested.',
          ],
        },
      ],
    },
  ],
  keyTerms: [
    {
      term: 'Testator/Testatrix',
      definition: 'The person who creates a will. Testator (male) and testatrix (female) — the person whose estate plan is being established.',
    },
    {
      term: 'Executor/Personal Representative',
      definition: 'The person or institution named in a will to carry out its terms — managing the estate, paying debts, filing taxes, and distributing assets to beneficiaries.',
    },
    {
      term: 'Intestacy',
      definition: 'Dying without a valid will. The estate is distributed according to the state or country\'s default succession laws, which may not reflect the deceased\'s actual wishes.',
    },
    {
      term: 'Probate',
      definition: 'The court-supervised legal process of validating a will, inventorying assets, paying debts and taxes, and distributing the remaining estate to rightful beneficiaries.',
    },
    {
      term: 'Fiduciary',
      definition: 'A person or entity with a legal obligation to act in the best interest of another party. Trustees, executors, and POA agents are fiduciaries with duties of loyalty, care, and prudence.',
    },
    {
      term: 'Grantor/Settlor/Trustor',
      definition: 'The person who creates and funds a trust. These terms are used interchangeably depending on jurisdiction.',
    },
    {
      term: 'Beneficiary',
      definition: 'The person or entity entitled to receive assets or income from a will, trust, insurance policy, retirement account, or other estate planning instrument.',
    },
    {
      term: 'Coparcener',
      definition: 'Under Hindu law, a person who has a birthright share in ancestral/joint family property. After the 2005 Hindu Succession Act amendment, both sons and daughters are coparceners.',
    },
    {
      term: 'Portability (US Estate Tax)',
      definition: 'The ability of a surviving spouse to use the deceased spouse\'s unused federal estate and gift tax exemption (DSUE), effectively doubling the available exemption for the surviving spouse.',
    },
    {
      term: 'Step-Up in Basis',
      definition: 'A US tax provision where inherited assets receive a new cost basis equal to their fair market value at the date of the decedent\'s death, eliminating capital gains tax on appreciation during the decedent\'s lifetime.',
    },
    {
      term: 'Pour-Over Will',
      definition: 'A will that directs any assets not already held in a living trust to be transferred ("poured over") into the trust upon the testator\'s death. These assets still pass through probate.',
    },
    {
      term: 'Escheat',
      definition: 'The legal process by which a deceased person\'s property reverts to the state government when there are no identifiable heirs or beneficiaries.',
    },
    {
      term: 'Karta',
      definition: 'The manager of a Hindu Undivided Family (HUF) — typically the senior-most male coparcener. The Karta has broad powers to manage HUF property for the family\'s benefit.',
    },
    {
      term: 'Letters of Administration',
      definition: 'A court-issued document granting authority to an administrator to manage the estate of someone who died without a valid will (intestate), similar to an executor\'s authority under a will.',
    },
  ],
  tips: [
    'Start estate planning early — you do not need to be wealthy or elderly. Anyone with assets, dependents, or specific wishes for their care should have at least a basic will and power of attorney.',
    'Review and update your estate plan after every major life event: marriage, divorce, birth of a child, death of a beneficiary, significant asset acquisition, moving to a new state or country, or changes in tax law.',
    'Ensure beneficiary designations on life insurance, retirement accounts, and bank accounts are current and consistent with your will and overall estate plan — these designations override your will.',
    'In India, register your will at the Sub-Registrar\'s office even though it is optional — a registered will carries much stronger evidentiary value and is significantly harder to challenge in court.',
    'Fund your trust — creating a trust document without transferring assets into it is one of the most common estate planning mistakes. An unfunded trust provides no probate avoidance or other benefits.',
    'Have explicit conversations with your family about your estate plan, especially in family business situations. Lack of communication causes more estate disputes than lack of documentation.',
    'Keep original estate planning documents in a fireproof safe or with your attorney, and inform your executor and key family members of their location. Do not store originals only in a bank safe deposit box, as access may be restricted after death.',
    'Consider the tax implications of your state of residence — states like Florida, Texas, and Nevada have no state income or estate tax, while states like New York, Massachusetts, and Oregon have their own estate tax with lower exemptions than the federal level.',
    'For Indian NRIs: Maintain a separate Indian will for Indian assets and a will in your country of residence for assets there. Ensure both wills are coordinated and do not inadvertently revoke each other.',
    'Include digital assets in your estate plan — email accounts, social media, cryptocurrency wallets, online businesses, digital photos, and subscription services. Document access procedures (not passwords in the will itself) in a secure, referenced location.',
    'Do not use a joint will with your spouse — while it seems simple, it becomes irrevocable upon the first death and prevents the surviving spouse from adapting to changed circumstances.',
    'If you have minor children, naming a guardian in your will is one of the most important decisions — without it, the court will decide who raises your children, and family disputes over custody are common.',
  ],
  faqs: [
    {
      question: 'What happens if I die without a will?',
      answer: 'If you die without a will (intestate), your assets are distributed according to your state or country\'s default succession laws. In the US, this typically means your spouse and children inherit in proportions set by state statute — unmarried partners, stepchildren, and friends receive nothing. In India, the applicable personal law (Hindu Succession Act, Indian Succession Act, or Muslim Personal Law) determines the distribution. Intestacy often results in unintended beneficiaries, family disputes, higher legal costs, and delays. Having a valid will ensures your assets go to the people and causes you choose.',
    },
    {
      question: 'What is the difference between a will and a trust, and do I need both?',
      answer: 'A will is a document that takes effect only upon your death and must go through probate (court supervision). A trust is a legal entity that holds assets during your life and after death, typically avoiding probate. Many estate plans use both: a revocable living trust as the primary vehicle for assets (avoiding probate, providing incapacity planning, and maintaining privacy), and a pour-over will as a safety net to catch any assets not transferred into the trust. You also need a will to name guardians for minor children, which a trust cannot do.',
    },
    {
      question: 'In India, does a nominee automatically become the owner of assets?',
      answer: 'No. A nominee in India is generally a custodian or trustee, not the legal owner. The Supreme Court of India has held that nomination is a mechanism for convenient transmission of assets upon death, but it does not override the rights of legal heirs as determined by a valid will or the applicable succession law. The nominee receives the assets to hold for legal heirs. However, there is an exception for life insurance — if a parent, spouse, or child is appointed as a "beneficial nominee," they have a beneficial interest in the insurance proceeds under the Insurance Act. To avoid confusion, always have a valid will that clearly specifies asset distribution.',
    },
    {
      question: 'How much does estate planning cost, and is it worth it?',
      answer: 'In the US, a basic will costs $300-$1,000 through an attorney, while a comprehensive estate plan with a revocable living trust, pour-over will, powers of attorney, and advance directives typically costs $1,500-$5,000+. In India, drafting a will through a lawyer costs ₹5,000-₹25,000, and will registration costs a nominal fee at the Sub-Registrar\'s office. The cost of NOT planning is far higher: probate fees (3-8% of estate value), potential estate taxes, family disputes, court-appointed guardianship proceedings, and the emotional toll on your family. Estate planning is one of the highest-return investments you can make for your family\'s financial security and peace of mind.',
    },
    {
      question: 'Can I write my own will, or do I need a lawyer?',
      answer: 'Legally, you can write your own will (some states even accept handwritten holographic wills), and in India a will does not require a lawyer. However, DIY wills are far more likely to contain errors, ambiguities, or technical deficiencies that make them vulnerable to legal challenges. Common mistakes include improper witnessing, vague language, failing to account for all assets, not addressing contingencies, and conflicting with beneficiary designations. For simple estates, reputable online services can work. For anything involving significant assets, blended families, business interests, real estate in multiple jurisdictions, or tax planning, hiring an experienced estate planning attorney is strongly recommended.',
    },
    {
      question: 'What is the current US federal estate tax exemption, and what happens when it sunsets?',
      answer: 'The 2024 federal estate and gift tax exemption is $13.61 million per individual ($27.22 million per married couple), with a top tax rate of 40%. Under the Tax Cuts and Jobs Act of 2017, this historically high exemption is scheduled to sunset after December 31, 2025, potentially reverting to approximately $6-7 million per person (adjusted for inflation). This means estates that are currently exempt could face significant estate tax liability. Proactive strategies include making large gifts before the sunset, funding irrevocable trusts, and using GRATs or other wealth transfer vehicles while the higher exemption is available.',
    },
  ],
};
