import type { EngineData } from '../types';

export const financialPlanningEngine: EngineData = {
  category: 'financial-planning',
  title: 'Financial Planning Fundamentals',
  description: 'Comprehensive guide to budgeting, cash flow management, emergency funds, and financial goal setting.',
  topics: [
    {
      name: 'Budgeting',
      description: 'The foundation of all financial planning — tracking income vs. expenses and allocating money purposefully.',
      details: [
        'A budget is a spending plan based on income and expenses. It helps ensure you have enough money for necessities and priorities.',
        'The 50/30/20 rule: Allocate 50% of after-tax income to needs (housing, food, utilities), 30% to wants (entertainment, dining), and 20% to savings and debt repayment.',
        'Zero-based budgeting assigns every dollar a job — income minus all allocations equals zero. This method forces deliberate decisions about every expense.',
        'Envelope budgeting uses physical or virtual envelopes for each spending category. Once an envelope is empty, spending in that category stops.',
        'Pay-yourself-first budgeting prioritizes savings before all other expenses, automating transfers to savings/investment accounts on payday.',
        'Track spending for at least 30 days before creating a budget to understand real spending patterns versus assumed ones.',
        'Review and adjust your budget monthly. Life changes — so should your budget.',
        'Common budgeting tools: spreadsheets, apps like YNAB (You Need A Budget), Mint, or Goodbudget.',
      ],
      subtopics: [
        {
          name: 'Fixed vs. Variable Expenses',
          description: 'Understanding the two main expense categories for effective budgeting.',
          details: [
            'Fixed expenses remain constant month-to-month: rent/mortgage, insurance premiums, loan EMIs, subscriptions.',
            'Variable expenses fluctuate: groceries, utilities, fuel, entertainment, dining out.',
            'Semi-variable expenses have a fixed base with a variable component: phone bills with data overage, utility bills with seasonal variation.',
            'Reducing fixed expenses (negotiating rent, refinancing loans) has a larger long-term impact than cutting variable expenses.',
          ],
        },
        {
          name: 'Income Tracking',
          description: 'Monitoring all sources of income for accurate financial planning.',
          details: [
            'Primary income: salary, wages, business income.',
            'Secondary income: freelancing, side hustles, rental income.',
            'Passive income: dividends, interest, royalties.',
            'Irregular income requires averaging over 6-12 months and budgeting based on the lower estimate.',
          ],
        },
      ],
    },
    {
      name: 'Cash Flow Management',
      description: 'Ensuring money is available when needed by managing the timing of income and expenses.',
      details: [
        'Cash flow is the movement of money in and out of your finances. Positive cash flow means more income than expenses.',
        'Track cash flow weekly or biweekly to identify patterns: when do large bills hit? When does income arrive?',
        'Maintain a cash flow buffer of 1 month\'s expenses in your checking account to avoid overdrafts.',
        'Align bill payment dates with income dates where possible. Many creditors allow you to change your billing date.',
        'Automate recurring payments to avoid late fees, but monitor accounts to ensure sufficient funds.',
        'Separate accounts for different purposes: operating (daily expenses), savings, and investments.',
        'A cash flow statement tracks all inflows and outflows over a period, revealing your true financial picture.',
        'Irregular expenses (annual insurance, car registration, holidays) should be divided by 12 and saved monthly.',
      ],
      subtopics: [
        {
          name: 'Cash Flow Statement',
          description: 'A personal financial statement showing all money movement.',
          details: [
            'Lists all income sources and their amounts for a specific period.',
            'Lists all expense categories with actual amounts spent.',
            'Net cash flow = Total Income - Total Expenses.',
            'Positive net cash flow should be directed to savings, investments, or debt paydown.',
            'Negative net cash flow signals a need to increase income or cut expenses immediately.',
          ],
        },
      ],
    },
    {
      name: 'Emergency Fund',
      description: 'A financial safety net for unexpected expenses or income loss.',
      details: [
        'An emergency fund covers 3-6 months of essential living expenses. Single-income households or freelancers should target 6-12 months.',
        'Keep emergency funds in a high-yield savings account — accessible but separate from daily spending.',
        'Start with a mini emergency fund of ₹10,000-50,000 / $500-1,000 while paying off high-interest debt.',
        'Only use for true emergencies: job loss, medical emergencies, urgent home/car repairs. NOT for vacations or sales.',
        'Replenish the emergency fund immediately after any withdrawal. Make this a budget priority.',
        'Consider a tiered approach: Tier 1 (immediate access, 1 month), Tier 2 (savings account, 2-3 months), Tier 3 (liquid investments, 3+ months).',
        'Inflation erodes emergency fund value — review and increase the target annually.',
      ],
    },
    {
      name: 'Financial Goal Setting',
      description: 'Defining clear, measurable financial objectives with timelines.',
      details: [
        'SMART goals: Specific, Measurable, Achievable, Relevant, Time-bound.',
        'Short-term goals (0-2 years): Emergency fund, vacation fund, small purchases, paying off credit card debt.',
        'Medium-term goals (2-7 years): Down payment on a house, car purchase, education fund, wedding fund.',
        'Long-term goals (7+ years): Retirement, children\'s education, financial independence, estate building.',
        'Prioritize goals: Needs before wants, high-interest debt before low-interest debt.',
        'Calculate the monthly savings needed: Goal Amount ÷ Months Until Deadline = Monthly Savings Required.',
        'Account for inflation: A goal costing ₹10,00,000 today may cost ₹14,80,000 in 5 years at 8% inflation.',
        'Review goals quarterly and adjust for life changes — marriage, children, job change, health issues.',
        'Assign each goal its own savings/investment account for clarity and motivation.',
        'Use the power of compounding — starting early matters more than starting big.',
      ],
      subtopics: [
        {
          name: 'Goal Prioritization Framework',
          description: 'A systematic approach to ranking financial goals.',
          details: [
            'Priority 1: Basic financial security — emergency fund, essential insurance, high-interest debt elimination.',
            'Priority 2: Employer benefits — maximize employer 401(k)/EPF match (free money).',
            'Priority 3: High-interest debt payoff (>8% interest).',
            'Priority 4: Retirement savings — aim for 15-20% of gross income.',
            'Priority 5: Medium-term goals — house down payment, education.',
            'Priority 6: Low-interest debt payoff and additional investing.',
            'Priority 7: Aspirational goals — early retirement, philanthropy, lifestyle upgrades.',
          ],
        },
      ],
    },
    {
      name: 'Net Worth Tracking',
      description: 'Measuring overall financial health by calculating assets minus liabilities.',
      details: [
        'Net Worth = Total Assets - Total Liabilities.',
        'Assets include: cash, savings, investments, retirement accounts, property, vehicles, valuables.',
        'Liabilities include: mortgages, car loans, student loans, credit card debt, personal loans.',
        'Track net worth monthly or quarterly to measure financial progress.',
        'A growing net worth over time indicates financial health, even if it is currently negative.',
        'Focus on liquid net worth (excluding primary residence) for a clearer picture of available wealth.',
        'Young professionals often have negative net worth due to student loans — this is normal and temporary with good planning.',
        'Net worth milestones: Emergency fund complete → Debt-free (except mortgage) → 1x annual salary saved → Financial independence.',
      ],
    },
    {
      name: 'Financial Ratios for Individuals',
      description: 'Key metrics to evaluate personal financial health.',
      details: [
        'Savings Rate: (Income - Expenses) / Income. Target: 20%+ of gross income.',
        'Debt-to-Income Ratio: Total Monthly Debt Payments / Gross Monthly Income. Healthy: below 36%. Mortgages should be below 28%.',
        'Emergency Fund Ratio: Liquid Savings / Monthly Essential Expenses. Target: 3-6 months.',
        'Investment Assets to Net Worth Ratio: Investment Assets / Net Worth. Higher is better for wealth building.',
        'Housing Expense Ratio: Housing Costs / Gross Income. Should not exceed 30%.',
        'Liquidity Ratio: Liquid Assets / Monthly Expenses. Minimum 3, ideal 6+.',
        'Solvency Ratio: Net Worth / Total Assets. Above 50% indicates strong solvency.',
      ],
    },
    {
      name: 'Time Value of Money (TVM) Calculations',
      description: 'Core financial math for calculating present value, future value, and annuity payments.',
      details: [
        'The Time Value of Money principle: A rupee/dollar today is worth more than the same amount in the future because it can earn interest',
        'Future Value (FV) = PV × (1 + r)^n. Example: ₹1,00,000 at 10% for 10 years = ₹2,59,374',
        'Present Value (PV) = FV / (1 + r)^n. Example: ₹5,00,000 needed in 10 years at 8% discount = ₹2,31,597 today',
        'Annuity FV (ordinary): FV = PMT × [((1+r)^n - 1) / r]. SIP of ₹10,000/month at 12% for 20 years = ₹99.9 lakh',
        'Annuity PV: PV = PMT × [(1 - (1+r)^-n) / r]. Used to calculate loan EMI or pension value',
        'EMI formula: EMI = P × r × (1+r)^n / ((1+r)^n - 1). ₹50 lakh home loan at 8.5% for 20 years = ₹43,391/month',
        'Rule of 72: Approximate doubling time = 72 / interest rate. At 12% return, money doubles in ~6 years',
        'Real vs. nominal returns: Real Return ≈ Nominal Return - Inflation. ₹1 lakh growing at 12% with 6% inflation = ~6% real growth',
        'Compounding frequency matters: Annual, semi-annual, quarterly, monthly, daily. More frequent compounding = higher effective rate',
        'Effective Annual Rate (EAR) = (1 + r/n)^n - 1. A 12% rate compounded monthly = 12.68% effective annual rate',
        'Perpetuity: PV = Payment / r. A ₹50,000 annual payment forever at 8% is worth ₹6,25,000 today',
        'Growing perpetuity: PV = Payment / (r - g). Used in terminal value calculations for business valuation (Gordon Growth Model)',
      ],
    },
  ],
  keyTerms: [
    { term: 'Budget', definition: 'A financial plan that estimates income and expenses over a specific period, typically monthly.' },
    { term: 'Cash Flow', definition: 'The net amount of money moving in and out of your finances in a given period.' },
    { term: 'Net Worth', definition: 'The difference between total assets and total liabilities; a snapshot of financial health.' },
    { term: 'Emergency Fund', definition: 'A reserve of money set aside for unplanned expenses or financial emergencies, typically 3-6 months of expenses.' },
    { term: 'Compound Interest', definition: 'Interest calculated on both the initial principal and accumulated interest, causing exponential growth over time.' },
    { term: 'Inflation', definition: 'The rate at which the general price level of goods and services rises, reducing purchasing power.' },
    { term: 'Liquidity', definition: 'How quickly an asset can be converted to cash without significant loss of value.' },
    { term: 'Sinking Fund', definition: 'Money set aside over time for a planned future expense, such as a car or vacation.' },
    { term: 'Time Value of Money', definition: 'The concept that a dollar today is worth more than a dollar in the future due to its earning potential.' },
    { term: 'Opportunity Cost', definition: 'The value of the best alternative forgone when making a financial decision.' },
    { term: 'Debt-to-Income Ratio', definition: 'The percentage of gross monthly income that goes toward monthly debt payments.' },
    { term: 'Financial Independence', definition: 'Having sufficient passive income or savings to cover all living expenses without active employment.' },
  ],
  tips: [
    'Automate your savings — set up automatic transfers on payday before you can spend it.',
    'Use the 24-hour rule: Wait 24 hours before any non-essential purchase over ₹2,000/$50.',
    'Track every expense for one month to discover spending leaks — subscriptions you forgot, habitual small purchases.',
    'Review all subscriptions quarterly. Cancel anything unused in the past 30 days.',
    'Negotiate recurring bills annually: insurance, phone, internet, gym memberships.',
    'Build a one-month buffer in your checking account to break the paycheck-to-paycheck cycle.',
    'Use cash or debit for discretionary spending — physical payment creates psychological resistance to overspending.',
    'Set up separate savings accounts for each major goal — naming them increases commitment.',
    'Calculate your true hourly wage (after taxes, commute costs, work expenses) and evaluate purchases in hours worked.',
    'Financial planning is not a one-time event — schedule monthly money dates to review and adjust.',
  ],
  faqs: [
    {
      question: 'How much should I save each month?',
      answer: 'Aim to save at least 20% of your after-tax income. The 50/30/20 rule suggests 50% for needs, 30% for wants, and 20% for savings/debt repayment. If you have high-interest debt, consider the debt avalanche method alongside minimum savings. Start with whatever you can, even 5%, and increase by 1% every few months.',
    },
    {
      question: 'How big should my emergency fund be?',
      answer: 'Standard advice is 3-6 months of essential expenses. If you have a single income, are self-employed, or work in a volatile industry, aim for 6-12 months. Start with a mini emergency fund of ₹10,000-50,000 ($500-1,000) and build from there. Keep it in a high-yield savings account for easy access.',
    },
    {
      question: 'Should I pay off debt or save first?',
      answer: 'Both simultaneously, with priority based on interest rates. Step 1: Build a mini emergency fund (1 month expenses). Step 2: Pay off high-interest debt (>8-10%). Step 3: Build full emergency fund (3-6 months). Step 4: Invest. Always make minimum payments on all debts while focusing extra payments on the highest-interest debt.',
    },
    {
      question: 'What is the best budgeting method?',
      answer: 'The best budget is the one you actually follow. Popular methods include: 50/30/20 (simple percentage allocation), Zero-based (every dollar assigned), Envelope system (physical/virtual spending limits per category), and Pay-yourself-first (save first, spend the rest). Try each for a month and see what fits your personality.',
    },
    {
      question: 'How do I start financial planning if I have no savings?',
      answer: 'Start where you are: 1) Track all expenses for 30 days. 2) Create a basic budget. 3) Find at least one expense to cut or reduce. 4) Set up automatic savings, even ₹500/$10 per paycheck. 5) Build a mini emergency fund. 6) Gradually increase savings rate. The most important step is starting — even small amounts compound over time.',
    },
  ],
};
