import type { EngineData } from '../types';

export const fintechToolsEngine: EngineData = {
  category: 'fintech-tools',
  title: 'Financial Technology, Tools & Modeling',
  description: 'Bloomberg Terminal, financial planning software, CRM systems, Excel modeling, and fintech tools for finance professionals.',
  topics: [
    {
      name: 'Bloomberg Terminal & Market Data Platforms',
      description: 'Professional-grade tools for real-time market data, analytics, and research.',
      details: [
        'Bloomberg Terminal: industry standard for institutional finance. Costs ~$24,000/year per user. Used by 325,000+ professionals globally',
        'Key Bloomberg functions: BQ (quote), FA (financial analysis), GP (graph), PORT (portfolio analytics), SRCH (security search), NEWS',
        'Bloomberg Excel Add-in (BDH, BDP, BDS functions): pull live/historical data directly into spreadsheets for custom analysis',
        'Bloomberg PORT: portfolio management — track performance, risk attribution, benchmark comparison, compliance monitoring',
        'Alternatives to Bloomberg: Refinitiv Eikon ($22,000/yr), FactSet ($12,000/yr), S&P Capital IQ ($15,000/yr), Morningstar Direct',
        'Free/affordable alternatives: Yahoo Finance, Google Finance, TradingView (freemium), Screener.in (India), Moneycontrol, Tickertape',
        'NSE/BSE data platforms: NSE India website (free EOD data), BSE India, CMIE Prowess (corporate financial database for India)',
        'Reuters/Refinitiv Datastream: historical financial data going back decades — gold standard for academic research and backtesting',
        'API-based data: Alpha Vantage (free tier), Polygon.io, IEX Cloud, Quandl — for building custom dashboards and automated analysis',
        'Real-time vs delayed data: professional terminals provide real-time quotes; free platforms typically have 15-20 minute delay',
      ],
      subtopics: [
        {
          name: 'Technical Analysis Tools',
          description: 'Charting and technical analysis platforms for market timing and pattern recognition.',
          details: [
            'TradingView: web-based charting with 100+ indicators, Pine Script for custom strategies, social features. Free tier available',
            'MetaTrader 4/5: popular for forex and CFD trading, supports Expert Advisors (automated trading bots)',
            'Zerodha Kite/Streak: India-focused trading platform with built-in charting. Streak allows no-code algo trading strategies',
            'Amibroker: professional backtesting and scanning software. AFL (Amibroker Formula Language) for custom indicators',
            'Key technical indicators available: Moving Averages (SMA/EMA), RSI, MACD, Bollinger Bands, Volume Profile, Fibonacci Retracements',
            'Screeners: Screener.in (India fundamentals), Chartink (India technical), Finviz (US stocks), Stock Rover (US fundamentals)',
          ],
        },
      ],
    },
    {
      name: 'Financial Planning Software',
      description: 'Professional tools for creating comprehensive financial plans and projections.',
      details: [
        'MoneyGuidePro (Envestnet): most popular US financial planning software. Goal-based planning, Monte Carlo simulations, client portal',
        'eMoney Advisor: comprehensive planning with account aggregation, client vault, advanced cash flow modeling. ~$4,000/year',
        'RightCapital: modern UI, tax planning module, Roth conversion analysis, estate planning. Popular with younger advisors. ~$2,400/year',
        'Financial Mappers (India): financial planning software designed for Indian advisors. Covers Indian tax, PPF, NPS, EPF projections',
        'Wealth Vantage / iFast (India): platform for Indian MFDs and RIAs — portfolio tracking, financial planning, client reporting',
        'Monte Carlo simulation: runs 1,000-10,000+ scenarios with variable returns, inflation, and spending to calculate retirement success probability',
        'Key planning features: goal-based planning, cash flow analysis, tax projection, insurance needs analysis, estate planning, education funding',
        'Client portals: let clients view their financial plan, portfolio, documents, and net worth in real-time. Increases engagement and transparency',
        'Integration capabilities: connect with custodians, CRM, portfolio management, tax software for seamless data flow',
        'Plan presentation: modern software generates professional PDF reports and interactive web-based plans clients can explore',
      ],
      subtopics: [
        {
          name: 'Robo-Advisory Platforms',
          description: 'Automated investment management and digital advisory platforms.',
          details: [
            'Wealthfront, Betterment (US): automated portfolio management, tax-loss harvesting, rebalancing. 0.25% AUM fee',
            'Zerodha Coin, Groww, Kuvera (India): direct mutual fund platforms with zero commission. Some offer advisory features',
            'Scripbox, ET Money (India): goal-based automated investment recommendations with SIP management',
            'Hybrid robo-advisors: combine algorithm-driven portfolio management with access to human advisors (Vanguard PAS, Schwab Intelligent Portfolios Premium)',
            'White-label robo platforms: let advisors offer robo-advisory under their own brand (e.g., Riskalyze Autopilot, AdvisorEngine)',
            'Key features: automated rebalancing, tax-loss harvesting, dividend reinvestment, goal tracking, risk-based asset allocation',
          ],
        },
      ],
    },
    {
      name: 'CRM Systems for Financial Advisors',
      description: 'Client Relationship Management tools for managing financial advisory practices.',
      details: [
        'Salesforce Financial Services Cloud: enterprise-grade CRM. Tracks households, financial accounts, referrals, compliance. ~$300/user/month',
        'Wealthbox CRM: designed for financial advisors. Clean UI, workflow automation, integrations with custodians. ~$59/user/month',
        'Redtail CRM: popular among independent advisors. Workflow management, compliance tracking, document storage. ~$99/month for 15 users',
        'Zoho CRM: affordable general-purpose CRM adaptable for finance. ~₹800-₹2,000/user/month. Good for Indian advisory firms',
        'HubSpot CRM: free tier available. Marketing automation + CRM. Good for content-driven advisory practices',
        'Key CRM features for advisors: contact management, task/workflow automation, email tracking, pipeline management, birthday/anniversary reminders',
        'Compliance integration: CRM should log all client communications for regulatory record-keeping (SEBI/SEC requirements)',
        'Client segmentation in CRM: tag clients by AUM tier, service model, review frequency, life stage, risk profile',
        'Pipeline tracking: track prospects from initial inquiry → discovery meeting → proposal → onboarding → active client',
        'Reporting: CRM dashboards for AUM growth, client retention, revenue per client, activity metrics, referral sources',
      ],
    },
    {
      name: 'Excel & Spreadsheet Modeling for Finance',
      description: 'Essential Excel skills and financial modeling techniques for financial analysis and planning.',
      details: [
        'Core financial functions: FV (future value), PV (present value), PMT (payment), RATE, NPER, IRR, XIRR, NPV, XNPV',
        'XIRR is critical for Indian MF investors: calculates actual returns on irregular cash flows (SIPs with variable amounts/dates)',
        'Loan amortization table: use PMT for EMI calculation, then split each payment into principal and interest using PPMT and IPMT',
        'DCF (Discounted Cash Flow) model: project free cash flows → discount at WACC → add terminal value → subtract debt = equity value',
        'Sensitivity analysis: Data Tables (1-variable and 2-variable) to show how output changes with different assumptions',
        'Scenario analysis: use CHOOSE function or Scenario Manager to toggle between Bull/Base/Bear case assumptions',
        'Portfolio tracker spreadsheet: GOOGLEFINANCE or Bloomberg API for live prices, SUMPRODUCT for weighted returns, STDEV for risk',
        'SIP return calculator: use FV function with monthly compounding. =FV(annual_rate/12, months, -monthly_sip) for future value',
        'Tax calculator in Excel: use nested IF or VLOOKUP with Indian/US tax slab tables for income tax estimation',
        'Retirement corpus calculator: factor in inflation-adjusted expenses, expected returns, life expectancy, and existing savings',
      ],
      subtopics: [
        {
          name: 'Financial Modeling Best Practices',
          description: 'Building professional-grade financial models in Excel.',
          details: [
            'Color coding convention: blue = manual input, black = formula, green = link to another sheet, red = link to external file',
            'Model structure: Assumptions sheet → Input data → Calculations → Output/Dashboard → Sensitivity analysis',
            'Three-statement model: Income Statement → Balance Sheet → Cash Flow Statement — all linked and self-balancing',
            'Error checks: build automatic checks — does BS balance? Do cash flows reconcile? Flag circular references',
            'Use named ranges and structured references instead of cell references like A1:B50 — makes formulas readable',
            'Version control: save dated versions (Model_v1.2_2024-03-15.xlsx), maintain a change log sheet',
            'Key shortcuts: F4 (toggle absolute/relative), Ctrl+Shift+Enter (array formula), Alt+= (AutoSum), F2 (edit cell), Ctrl+` (show formulas)',
            'Pivot Tables: essential for analyzing transaction data, portfolio holdings, client segmentation, revenue analysis',
          ],
        },
        {
          name: 'Google Sheets for Finance',
          description: 'Cloud-based spreadsheet tools and functions specific to financial analysis.',
          details: [
            'GOOGLEFINANCE function: =GOOGLEFINANCE("NSE:RELIANCE","price") for live stock prices. Free and auto-updating',
            'IMPORTHTML/IMPORTDATA: scrape financial data from websites directly into sheets for analysis',
            'Google Sheets + Apps Script: automate portfolio tracking, daily NAV pulls, email alerts for price targets',
            'Collaboration: multiple team members can work on the same financial model simultaneously with comment/suggest modes',
            'Google Sheets Add-ons: Supermetrics (marketing data), Coefficient (database connections), Sheetgo (workflow automation)',
            'Limitations vs Excel: slower with large datasets (>100K rows), fewer advanced functions, no Power Query/Power Pivot equivalent',
          ],
        },
      ],
    },
    {
      name: 'Accounting & Tax Software',
      description: 'Tools for bookkeeping, tax filing, and financial record management.',
      details: [
        'Tally Prime (India): dominant accounting software in India. GST compliance, inventory management, banking integration. ~₹18,000/year',
        'Zoho Books (India): cloud accounting with GST, invoicing, expense tracking, bank reconciliation. Starts free for small businesses',
        'QuickBooks: global standard for small business accounting. US and India versions available. Cloud-based with bank feeds. ~₹500-₹2,500/month',
        'ClearTax (India): popular for ITR filing, GST returns, TDS compliance. Both individual and business tax filing. Free ITR-1 filing',
        'TurboTax (US): most popular personal tax filing software. Interview-based approach guides through deductions and credits',
        'Winman CA ERP (India): practice management for Chartered Accountants — client tracking, compliance calendar, billing',
        'Xero: cloud accounting popular with startups. Strong API ecosystem, 1000+ integrations. ~$13-$70/month',
        'FreshBooks: invoicing-focused accounting for freelancers and service businesses. Time tracking, expense management, proposals',
        'Key features to evaluate: GST/tax compliance, bank reconciliation, multi-currency, reporting, API integrations, mobile access',
        'Data security: ensure any financial software uses bank-level encryption (256-bit AES), two-factor authentication, and regular backups',
      ],
    },
    {
      name: 'Investment & Portfolio Management Platforms',
      description: 'Tools for managing investment portfolios, tracking performance, and executing trades.',
      details: [
        'Morningstar Direct: institutional portfolio analytics, fund research, manager comparison. Industry standard for fund analysis',
        'Orion Portfolio Solutions: portfolio management, performance reporting, trading, rebalancing. Popular with US RIAs',
        'MProfit (India): portfolio tracking for Indian stocks, MFs, bonds, real estate. Supports XIRR, capital gains reporting. ₹1,999-₹4,999/year',
        'Value Research Online (India): mutual fund research, portfolio tracker, ratings, and comparison tools. Free basic version',
        'CAMS/KFintech (India): RTA platforms where you can view consolidated mutual fund holdings via CAS (Consolidated Account Statement)',
        'Smallcase (India): thematic portfolio platform. Advisors can create and manage model portfolios (smallcases) for clients',
        'Riskalyze (US): risk tolerance assessment tool. Generates a "Risk Number" (1-99) to match client risk capacity with portfolio risk',
        'Rebalancing tools: iRebal, Tamarac, Orion Eclipse — automate tax-efficient portfolio rebalancing across multiple accounts',
        'Trade execution: custodian platforms (Schwab, Fidelity, Zerodha) provide APIs for automated trading and order management',
        'Performance attribution: break down portfolio returns into asset allocation, security selection, market timing, and currency effects',
      ],
    },
  ],
  keyTerms: [
    { term: 'Bloomberg Terminal', definition: 'Professional market data and analytics platform by Bloomberg L.P. Provides real-time financial data, news, analytics, and trading tools. Industry standard in institutional finance.' },
    { term: 'Monte Carlo Simulation', definition: 'Statistical technique that runs thousands of random scenarios to estimate probability of outcomes. Used in retirement planning to assess likelihood of not running out of money.' },
    { term: 'XIRR', definition: 'Extended Internal Rate of Return. Excel function that calculates annualized return on irregular cash flows. Essential for calculating actual SIP returns in India.' },
    { term: 'DCF Model', definition: 'Discounted Cash Flow model. Valuation method that estimates a company\'s worth by projecting future cash flows and discounting them to present value.' },
    { term: 'CRM', definition: 'Client Relationship Management system. Software to track client interactions, manage workflows, automate communications, and maintain compliance records.' },
    { term: 'AUM Fee Model', definition: 'Advisory fee structure based on percentage of Assets Under Management. Typically 0.5-1.5% annually. Aligns advisor compensation with client wealth growth.' },
    { term: 'NAV', definition: 'Net Asset Value. Per-unit value of a mutual fund calculated daily. NAV = (Total Assets - Total Liabilities) / Number of Units Outstanding.' },
    { term: 'API', definition: 'Application Programming Interface. Allows different software systems to communicate. Financial APIs enable automated data pulls, trading, and reporting.' },
    { term: 'Robo-Advisor', definition: 'Digital platform providing automated, algorithm-driven financial planning with minimal human supervision. Low fees (0.25-0.50% AUM).' },
    { term: 'Three-Statement Model', definition: 'Financial model linking Income Statement, Balance Sheet, and Cash Flow Statement. Foundation of all corporate financial analysis and valuation.' },
  ],
  tips: [
    'Start with free tools (Google Finance, Screener.in, TradingView free tier) before investing in expensive platforms',
    'Master Excel/Google Sheets financial functions first — they\'re used everywhere in finance regardless of other tools',
    'XIRR is the most important function for Indian investors — use it to calculate true returns on SIPs and irregular investments',
    'Set up a portfolio tracking spreadsheet with automatic price feeds before recommending any tracking app to clients',
    'Learn keyboard shortcuts for every tool you use — it can 2-3x your productivity in Bloomberg, Excel, and CRM',
    'Always back up financial data in at least 2 locations — cloud + local drive. Client financial data loss is unrecoverable',
    'Use CRM religiously — log every client interaction. It protects you legally and helps personalize service',
    'Build Excel templates for common tasks (SIP calculator, loan comparison, tax estimation) — reuse across clients',
  ],
  faqs: [
    {
      question: 'Do I need a Bloomberg Terminal to work in finance?',
      answer: 'Not necessarily. Bloomberg is essential for institutional roles (investment banking, asset management, hedge funds). For financial advisors, planners, and retail-focused roles, alternatives like Morningstar, Screener.in, TradingView, and good Excel skills are sufficient. Many firms provide Bloomberg access if the role requires it.',
    },
    {
      question: 'What is the best Excel function for calculating investment returns in India?',
      answer: 'XIRR is the gold standard. It handles irregular cash flows (SIPs on different dates, lump sums, partial withdrawals) and gives you the true annualized return. Syntax: =XIRR(cash_flow_range, date_range). Use negative values for investments and positive for redemptions.',
    },
    {
      question: 'Which financial planning software should an independent Indian advisor use?',
      answer: 'Start with: 1) MProfit or Value Research for portfolio tracking, 2) Zoho CRM for client management (free tier), 3) Excel/Google Sheets for financial plans, 4) ClearTax for tax filing support. As you grow, consider Financial Mappers or Wealth Vantage for comprehensive planning. The total cost can be under ₹25,000/year.',
    },
    {
      question: 'How do I build a DCF model in Excel?',
      answer: 'Steps: 1) Project revenue and expenses for 5-10 years, 2) Calculate Free Cash Flow (FCF) each year, 3) Determine WACC (discount rate), 4) Calculate terminal value using Gordon Growth Model, 5) Discount all future cash flows to present value using NPV, 6) Subtract net debt to get equity value, 7) Divide by shares outstanding for per-share value. Build sensitivity tables for key assumptions.',
    },
  ],
};
