import type { EngineData } from '../types';

export const insuranceRiskEngine: EngineData = {
  category: 'insurance-risk',
  title: 'Insurance & Risk Management',
  description: 'Comprehensive guide to life, health, disability, liability insurance, and personal risk management strategies.',
  topics: [
    {
      name: 'Life Insurance',
      description: 'Financial protection for dependents in case of the policyholder\'s death.',
      details: [
        'Life insurance provides a death benefit (lump sum or periodic payments) to beneficiaries upon the insured person\'s death.',
        'Term Life Insurance: Pure protection for a specific period (10, 20, 30 years). Lowest cost, no cash value. Best for most people.',
        'Whole Life Insurance: Lifetime coverage with a cash value component that grows over time. Significantly more expensive than term.',
        'Universal Life Insurance: Flexible premium and death benefit with a cash value component linked to market or fixed interest rates.',
        'Endowment Plans: Combination of insurance and savings. Returns are typically lower than pure investment options. Generally not recommended.',
        'ULIPs (Unit Linked Insurance Plans — India): Combine insurance with market-linked investments. High charges in early years. Compare carefully with "term + mutual fund" combination.',
        'Rule of thumb: Life insurance coverage should be 10-15 times annual income, or enough to replace income until dependents are financially independent.',
        'Human Life Value method: Present value of future income minus personal expenses equals the insurance coverage needed.',
        'Buy term insurance early when you\'re young and healthy — premiums are much lower and you\'re more likely to qualify.',
        'Only buy life insurance if you have financial dependents. Single individuals with no dependents generally don\'t need life insurance.',
        'Riders: Additional benefits like accidental death, critical illness, waiver of premium, that can be added to a base policy.',
      ],
      subtopics: [
        {
          name: 'Needs Analysis',
          description: 'Calculating the right amount of life insurance coverage.',
          details: [
            'Income replacement method: Annual income × Years of income to replace = Coverage needed.',
            'DIME method: Debt + Income replacement + Mortgage + Education costs = Total coverage.',
            'Consider: Outstanding debts, mortgage balance, children\'s education costs, spouse\'s income gap, funeral expenses.',
            'Subtract: Existing insurance, savings, investments, spouse\'s earning capacity.',
            'Review coverage every 3-5 years or after major life events (marriage, children, home purchase).',
          ],
        },
      ],
    },
    {
      name: 'Health Insurance',
      description: 'Coverage for medical expenses including hospitalization, treatments, and prescriptions.',
      details: [
        'Health insurance covers medical expenses — hospitalization, surgeries, doctor visits, prescriptions, diagnostic tests.',
        'Types: Individual plans, family floater plans, group plans (employer-provided), senior citizen plans, critical illness plans.',
        'Family floater: Single sum insured shared among all family members. Cost-effective but ensure sum insured is adequate.',
        'Sum insured should cover potential hospitalization costs: Minimum ₹5-10 lakh in India, consider $250K+ in the US if not employer-provided.',
        'Critical Illness Insurance: Lump sum payout on diagnosis of specified serious illnesses (cancer, heart attack, stroke, kidney failure).',
        'Cashless hospitalization: Treatment at network hospitals without paying upfront. Insurer settles directly with hospital.',
        'Pre-existing diseases: Most policies cover pre-existing conditions after a waiting period (typically 2-4 years in India).',
        'Co-payment: Percentage of claim amount the policyholder must pay out-of-pocket. Lower copay = higher premium.',
        'Deductible: Amount the policyholder pays before insurance kicks in. Higher deductible = lower premium.',
        'Super top-up plans: Affordable way to increase total health coverage. Kicks in when claims exceed a threshold (deductible).',
        'COBRA (US): Allows continuation of employer health insurance for 18-36 months after leaving a job, but at full cost.',
        'Medicare (US): Government health insurance for 65+ and certain disabled individuals. Parts A (hospital), B (medical), C (Advantage), D (prescription).',
        'Ayushman Bharat (India): Government health insurance of ₹5 lakh/family for economically weaker sections.',
      ],
    },
    {
      name: 'Disability Insurance',
      description: 'Income replacement if you become unable to work due to illness or injury.',
      details: [
        'Disability insurance replaces a portion of income (typically 60-70%) if you cannot work due to disability.',
        'Short-term disability: Covers 3-6 months. Often provided by employers.',
        'Long-term disability: Covers years or until retirement age. More important to have personally.',
        'Own-occupation disability: Pays if you can\'t perform YOUR specific job. More expensive but better coverage.',
        'Any-occupation disability: Pays only if you can\'t perform ANY job you\'re qualified for. Cheaper but harder to claim.',
        'Elimination period: Waiting period before benefits begin (30, 60, 90, 180 days). Longer period = lower premium.',
        'SSDI (Social Security Disability Insurance — US): Government disability benefits for qualifying individuals. Strict eligibility criteria.',
        'Your ability to earn income is your most valuable asset in your working years — protecting it is critical.',
        'Group disability through employer is good, but doesn\'t follow you when you change jobs. Consider supplemental individual coverage.',
      ],
    },
    {
      name: 'Property & Liability Insurance',
      description: 'Protecting physical assets and against legal liability claims.',
      details: [
        'Homeowners/Renters Insurance: Covers dwelling, personal property, liability, additional living expenses if home is uninhabitable.',
        'Auto Insurance: Liability, collision, comprehensive, uninsured/underinsured motorist coverage.',
        'Umbrella Insurance: Extra liability coverage beyond home/auto policy limits. Typically $1-5 million. Inexpensive for the coverage provided.',
        'Professional Liability (E&O): For professionals whose advice/services could cause client financial harm. Doctors, lawyers, consultants.',
        'General Liability: For business owners against claims of injury, property damage, or negligence.',
        'Directors & Officers (D&O): Protects corporate directors and officers from personal liability arising from their decisions.',
        'Product Liability: For manufacturers and sellers against claims from product defects causing harm.',
        'In India: Motor insurance is mandatory. Home insurance is optional but strongly recommended, especially for mortgaged properties.',
        'Principle of indemnity: Insurance restores you to the financial position before the loss — you cannot profit from a claim.',
        'Replacement cost vs. Actual cash value: Replacement cost covers full replacement; ACV deducts depreciation.',
      ],
    },
    {
      name: 'Risk Management Principles',
      description: 'Framework for identifying, assessing, and managing personal financial risks.',
      details: [
        'Risk identification: List all potential financial risks — death, disability, illness, property loss, liability, market loss, job loss.',
        'Risk assessment: Evaluate probability (likelihood) and impact (financial severity) of each risk.',
        'Risk avoidance: Eliminate the risk entirely (e.g., not engaging in extreme sports).',
        'Risk reduction: Take steps to lower probability or impact (e.g., healthy lifestyle reduces health risks, diversification reduces market risk).',
        'Risk transfer: Shift the financial impact to another party through insurance or contracts.',
        'Risk retention: Accept the risk and self-insure (appropriate for low-severity, high-frequency risks like small medical expenses).',
        'The risk management matrix: Low probability + High impact → Transfer (insure). High probability + Low impact → Retain (self-insure). High probability + High impact → Avoid. Low probability + Low impact → Retain.',
        'Insurance is most valuable for low-probability, high-impact events. Self-insure for small, manageable losses.',
        'Emergency fund acts as self-insurance for moderate unexpected expenses.',
        'Review insurance coverage annually and after major life changes.',
      ],
    },
    {
      name: 'Annuities',
      description: 'Insurance products providing guaranteed income streams, typically for retirement.',
      details: [
        'An annuity is a contract with an insurance company that provides regular payments in exchange for a lump sum or series of payments',
        'Fixed Annuity: Guarantees a fixed interest rate for a set period. Low risk, predictable returns. Similar to a fixed deposit but with insurance features',
        'Variable Annuity: Returns linked to market-based sub-accounts (like mutual funds). Higher potential returns but also higher risk. Fees can be high (2-3%+)',
        'Indexed Annuity (Fixed-Indexed): Returns linked to a market index (S&P 500, Nifty) with a floor (typically 0% — no losses) and a cap on gains',
        'Immediate Annuity: Start receiving payments right away after a lump-sum investment. Ideal for retirees needing immediate income',
        'Deferred Annuity: Payments begin at a future date. Money grows tax-deferred during the accumulation phase',
        'Pension plans in India (LIC Jeevan Shanti, HDFC Life): Offer immediate and deferred annuity options with guaranteed payouts',
        'Annuity payout options: Life only (highest payment, stops at death), Life with period certain (minimum guaranteed period), Joint & survivor (covers spouse)',
        'Annuity taxation (India): Annuity income is taxed as "Income from Other Sources" at your slab rate. No tax on return of principal portion',
        'Annuity taxation (US): Growth is tax-deferred. Withdrawals taxed as ordinary income (not capital gains). 10% penalty if withdrawn before age 59½',
        'Surrender charges: Early withdrawal penalty, typically 5-7% in first year, declining annually. Lock-in period can be 5-10 years',
        'When to consider annuities: Guaranteed income need in retirement, already maxed other tax-advantaged accounts, longevity risk concern, pension replacement',
        'When to avoid: High fees erode returns, limited liquidity, better alternatives exist (SWP from mutual funds, dividend portfolio, NPS in India)',
      ],
    },
  ],
  keyTerms: [
    { term: 'Premium', definition: 'The amount paid periodically to the insurance company to maintain coverage.' },
    { term: 'Sum Insured / Coverage', definition: 'The maximum amount the insurance company will pay in case of a claim.' },
    { term: 'Deductible', definition: 'The amount the policyholder pays out-of-pocket before insurance coverage begins.' },
    { term: 'Co-payment', definition: 'The percentage of a claim amount that the policyholder is responsible for paying.' },
    { term: 'Claim', definition: 'A formal request to the insurance company to pay for a covered loss or service.' },
    { term: 'Rider', definition: 'An optional add-on to an insurance policy that provides additional benefits at extra cost.' },
    { term: 'Underwriting', definition: 'The process by which insurers evaluate risk and determine premiums for an applicant.' },
    { term: 'Beneficiary', definition: 'The person(s) designated to receive the insurance proceeds (death benefit) upon the insured\'s death.' },
    { term: 'Cash Value', definition: 'The savings component of a permanent life insurance policy that accumulates over time and can be borrowed against.' },
    { term: 'Term Insurance', definition: 'Life insurance that provides coverage for a specific period. No cash value. Lowest cost per unit of coverage.' },
    { term: 'Floater Policy', definition: 'A single policy that covers multiple family members under one sum insured (common in health insurance in India).' },
    { term: 'Waiting Period', definition: 'Time period after policy purchase during which certain conditions are not covered (e.g., pre-existing diseases).' },
  ],
  tips: [
    'Buy term life insurance — it provides the most coverage for the lowest cost. "Buy term, invest the rest" is sound advice.',
    'Get health insurance early — premiums are lower and pre-existing disease waiting periods start sooner.',
    'Don\'t buy insurance as an investment. Insurance is for protection; investments are for growth. Keep them separate.',
    'Read the policy document, especially exclusions and claim procedures, before buying.',
    'Disclose all pre-existing conditions honestly — non-disclosure can lead to claim rejection.',
    'Review and update beneficiary designations after major life events (marriage, divorce, birth, death).',
    'Compare quotes from at least 3-5 insurers before buying. Use comparison websites.',
    'Consider a super top-up health plan to enhance coverage affordably.',
    'Don\'t over-insure or under-insure — match coverage to actual needs.',
    'Maintain a claims-free record for no-claim bonuses, especially in health and auto insurance.',
  ],
  faqs: [
    {
      question: 'How much life insurance do I need?',
      answer: 'Use the income replacement method: 10-15 times your annual income. For a more precise calculation, use the DIME method: add up all Debts, Income replacement needs (annual income × years until dependents are independent), Mortgage balance, and Education costs for children. Subtract existing savings and investments. Example: If your annual income is ₹12 lakh, debts are ₹5 lakh, mortgage is ₹30 lakh, and education fund needed is ₹20 lakh, and you need income replacement for 25 years, your coverage need is approximately ₹3.55 crore (₹12L × 25 + ₹5L + ₹30L + ₹20L - existing savings).',
    },
    {
      question: 'Should I buy term insurance or whole life/endowment plans?',
      answer: 'Term insurance is almost always the better choice. It provides 10-20x more coverage for the same premium compared to whole life/endowment plans. The "investment" component of endowment/whole life plans typically returns 4-6% — well below what you could earn by investing in mutual funds. Strategy: Buy a term plan for protection and invest the premium difference in mutual funds (SIPs). This "buy term, invest the rest" approach gives you both adequate protection and superior wealth creation.',
    },
    {
      question: 'What health insurance coverage is adequate?',
      answer: 'In India, minimum ₹5-10 lakh for individuals, ₹10-25 lakh for families. In metro cities, consider ₹15-25 lakh given high hospital costs. Add a super top-up for cost-effective additional coverage. In the US, ensure coverage through employer or marketplace plans. Key factors: Age, family size, city of residence, existing health conditions, and family medical history. Also consider critical illness cover (₹25-50 lakh) as a supplement to regular health insurance.',
    },
  ],
};
