import type { EngineData } from '../types';

export const investmentManagementEngine: EngineData = {
  category: 'investment-management',
  title: 'Investment Management',
  description: 'Comprehensive guide to stocks, bonds, mutual funds, ETFs, portfolio theory, asset allocation, and investment strategies.',
  topics: [
    {
      name: 'Stocks (Equities)',
      description: 'Ownership shares in a company that represent a claim on part of the company\'s assets and earnings.',
      details: [
        'A stock represents fractional ownership in a company. Stockholders benefit from price appreciation and dividends.',
        'Common stock provides voting rights and variable dividends. Preferred stock provides fixed dividends but typically no voting rights.',
        'Market capitalization = Share Price × Total Outstanding Shares. Categories: Large-cap (>$10B/₹20,000Cr), Mid-cap ($2-10B), Small-cap (<$2B).',
        'Stock valuation metrics: P/E ratio (Price/Earnings), P/B ratio (Price/Book Value), Dividend Yield, EPS (Earnings Per Share), ROE (Return on Equity).',
        'Growth stocks: Companies expected to grow revenue/earnings faster than the market. Higher P/E, lower or no dividends. Examples: tech companies.',
        'Value stocks: Companies trading below intrinsic value based on fundamentals. Lower P/E, often higher dividends. Examples: established industrials.',
        'Dividend stocks: Companies with a history of regular, increasing dividend payments. Ideal for income-seeking investors.',
        'Blue-chip stocks: Large, well-established, financially sound companies with a history of reliable performance.',
        'Stock exchanges: NYSE, NASDAQ (US), BSE, NSE (India), LSE (UK), TSE (Japan).',
        'Stock prices are driven by earnings, growth expectations, interest rates, market sentiment, and macroeconomic factors.',
      ],
      subtopics: [
        {
          name: 'Fundamental Analysis',
          description: 'Evaluating a stock based on financial statements and economic factors.',
          details: [
            'Analyze income statement: Revenue growth, profit margins, EPS growth.',
            'Analyze balance sheet: Assets, liabilities, debt-to-equity ratio, book value.',
            'Analyze cash flow statement: Operating cash flow, free cash flow, capital expenditure.',
            'Key ratios: P/E, PEG (P/E to Growth), P/B, P/S (Price to Sales), Debt/Equity, Current Ratio.',
            'Intrinsic value estimation using DCF (Discounted Cash Flow) model: Present value of expected future cash flows.',
            'Compare company metrics with industry peers and historical averages.',
            'Qualitative factors: management quality, competitive advantage (moat), industry trends, regulatory environment.',
          ],
        },
        {
          name: 'Technical Analysis',
          description: 'Analyzing price patterns and trading volumes to forecast future price movements.',
          details: [
            'Based on the premise that historical price and volume data can predict future movements.',
            'Support and resistance levels: Price floors and ceilings where buying/selling pressure concentrates.',
            'Moving averages: SMA (Simple Moving Average), EMA (Exponential Moving Average) — smooth out price action.',
            'RSI (Relative Strength Index): Momentum indicator, overbought (>70) or oversold (<30).',
            'MACD (Moving Average Convergence Divergence): Trend-following momentum indicator.',
            'Chart patterns: Head and shoulders, double top/bottom, triangles, flags, cup and handle.',
            'Volume analysis confirms price trends — rising price with rising volume is bullish.',
            'Technical analysis works best as a complement to fundamental analysis, not a replacement.',
          ],
        },
      ],
    },
    {
      name: 'Bonds (Fixed Income)',
      description: 'Debt instruments where investors lend money to an entity (government or corporation) for a fixed period at a fixed interest rate.',
      details: [
        'A bond is a loan from the investor to the issuer. The issuer pays periodic interest (coupon) and returns the principal (face value) at maturity.',
        'Key terms: Face value (par value, typically $1,000/₹1,000), Coupon rate (annual interest rate), Maturity date, Yield to Maturity (YTM).',
        'Government bonds: US Treasury bonds, Indian Government Securities (G-Secs), UK Gilts. Considered risk-free benchmark.',
        'Corporate bonds: Issued by companies. Higher yield than government bonds to compensate for credit risk.',
        'Municipal bonds: Issued by state/local governments. Often tax-exempt in the issuing jurisdiction.',
        'Bond prices move inversely to interest rates: When rates rise, existing bond prices fall, and vice versa.',
        'Credit ratings (AAA to D) indicate the issuer\'s ability to repay. Agencies: Moody\'s, S&P, Fitch, CRISIL (India).',
        'Duration measures a bond\'s sensitivity to interest rate changes. Longer duration = greater price volatility.',
        'Yield curve: Plots yields across different maturities. Normal (upward sloping), Inverted (downward — recession signal), Flat.',
        'Bond laddering: Buying bonds with staggered maturities to manage interest rate risk and provide regular liquidity.',
      ],
    },
    {
      name: 'Mutual Funds',
      description: 'Pooled investment vehicles that collect money from many investors to invest in a diversified portfolio.',
      details: [
        'A mutual fund pools money from multiple investors and is managed by a professional fund manager.',
        'Net Asset Value (NAV) = (Total Assets - Total Liabilities) / Number of Outstanding Units. Calculated daily.',
        'Equity funds: Invest primarily in stocks. Sub-types: Large-cap, mid-cap, small-cap, multi-cap, sectoral, thematic.',
        'Debt funds: Invest in bonds and fixed-income securities. Sub-types: Liquid, short-duration, corporate bond, gilt funds.',
        'Hybrid/Balanced funds: Mix of equity and debt. Sub-types: Aggressive hybrid (65-80% equity), Conservative hybrid (75-90% debt).',
        'Index funds: Passively track a market index (Nifty 50, S&P 500). Lower expense ratios than actively managed funds.',
        'Expense ratio: Annual fee charged by the fund, expressed as a percentage of AUM. Lower is generally better. Index funds: 0.05-0.5%, Active funds: 0.5-2.5%.',
        'SIP (Systematic Investment Plan): Investing a fixed amount at regular intervals. Benefits from rupee/dollar cost averaging.',
        'SWP (Systematic Withdrawal Plan): Regular withdrawals from a fund, useful for generating income in retirement.',
        'ELSS (Equity Linked Saving Scheme): Tax-saving mutual funds in India with a 3-year lock-in under Section 80C.',
        'Direct plans have lower expense ratios than regular plans (no distributor commission). Always prefer direct plans.',
      ],
    },
    {
      name: 'ETFs (Exchange-Traded Funds)',
      description: 'Investment funds traded on stock exchanges, combining features of mutual funds and individual stocks.',
      details: [
        'ETFs trade on exchanges like stocks throughout the day at market-determined prices, unlike mutual funds which trade at end-of-day NAV.',
        'Most ETFs are passively managed, tracking an index. Some actively managed ETFs exist but are less common.',
        'Generally lower expense ratios than mutual funds: 0.03% to 0.75% for most index ETFs.',
        'Types: Equity ETFs, Bond ETFs, Commodity ETFs (Gold, Silver), Sector ETFs, International ETFs, Thematic ETFs.',
        'Creation/redemption mechanism keeps ETF prices close to their NAV through authorized participants.',
        'No minimum investment beyond the price of one share (plus brokerage).',
        'Tax-efficient due to in-kind creation/redemption mechanism (especially in the US).',
        'Liquidity varies: Popular ETFs (SPY, QQQ) are highly liquid; niche ETFs may have wider bid-ask spreads.',
        'In India, popular ETFs track Nifty 50, Nifty Next 50, Sensex, Gold, and Nifty Bank.',
        'ETFs are ideal for: Core portfolio holdings, tactical allocation, sector exposure, and cost-conscious investing.',
      ],
    },
    {
      name: 'Portfolio Theory & Asset Allocation',
      description: 'The science of constructing optimal portfolios that maximize return for a given level of risk.',
      details: [
        'Modern Portfolio Theory (MPT) by Harry Markowitz: Diversification reduces portfolio risk without proportionally reducing expected returns.',
        'Efficient Frontier: The set of optimal portfolios offering the highest expected return for each level of risk.',
        'Asset allocation is the most important investment decision — studies show it determines ~90% of portfolio return variation.',
        'Strategic asset allocation: Long-term target mix based on goals, risk tolerance, and time horizon. Example: 60% equity, 30% bonds, 10% alternatives.',
        'Tactical asset allocation: Short-term deviations from strategic allocation to exploit market opportunities.',
        'Common allocation models: Conservative (30/70 equity/bond), Moderate (60/40), Aggressive (80/20), All-equity (100/0).',
        'Age-based rule of thumb: Bond allocation = Your age (e.g., 30-year-old: 30% bonds, 70% equity). This is a starting point, not a rigid rule.',
        'Rebalancing: Periodically adjusting portfolio back to target allocation. Methods: Calendar (quarterly/annually), Threshold (when allocation drifts >5%).',
        'Correlation: How assets move relative to each other. Low or negative correlation between assets improves diversification benefits.',
        'Diversification across: Asset classes, geographies, sectors, market caps, and investment styles (growth/value).',
        'Risk-adjusted return metrics: Sharpe Ratio (excess return per unit of total risk), Sortino Ratio (excess return per unit of downside risk).',
      ],
      subtopics: [
        {
          name: 'Risk Tolerance Assessment',
          description: 'Determining an investor\'s ability and willingness to accept investment risk.',
          details: [
            'Risk capacity: Objective ability to take risk based on time horizon, income stability, savings rate, and financial obligations.',
            'Risk tolerance: Subjective willingness to accept risk based on personality, experience, and emotional response to losses.',
            'Conservative investor: Preserves capital, accepts lower returns, cannot tolerate significant portfolio declines.',
            'Moderate investor: Seeks balance between growth and stability, can tolerate moderate short-term declines.',
            'Aggressive investor: Maximizes long-term growth, comfortable with significant short-term volatility.',
            'Time horizon is the most important factor: Longer time = more risk capacity (more time to recover from downturns).',
          ],
        },
      ],
    },
    {
      name: 'Investment Strategies',
      description: 'Different approaches to building and managing investment portfolios.',
      details: [
        'Buy and Hold: Purchase quality investments and hold for the long term, ignoring short-term volatility. Backed by evidence: time in the market beats timing the market.',
        'Dollar/Rupee Cost Averaging (DCA/SIP): Investing fixed amounts at regular intervals regardless of price. Reduces impact of volatility.',
        'Value Investing: Buying undervalued stocks trading below intrinsic value. Pioneered by Benjamin Graham and Warren Buffett.',
        'Growth Investing: Investing in companies with above-average growth potential, even at higher valuations.',
        'Income Investing: Focusing on investments that generate regular income — dividends, bonds, REITs.',
        'Index Investing: Buying index funds/ETFs to match market returns at minimal cost. Recommended by Warren Buffett for most investors.',
        'Contrarian Investing: Going against prevailing market sentiment — buying when others are fearful, selling when others are greedy.',
        'Momentum Investing: Buying assets that have been rising and selling those that have been falling.',
        'Core-Satellite: Core portfolio in low-cost index funds (70-80%), satellite positions in individual stocks or active funds (20-30%).',
        'Factor Investing: Targeting specific return drivers (factors) like value, momentum, quality, size, and low volatility.',
      ],
    },
    {
      name: 'Cryptocurrency & Digital Assets',
      description: 'Understanding crypto assets, blockchain, and their role in a diversified portfolio.',
      details: [
        'Bitcoin (BTC): First and largest cryptocurrency by market cap. Decentralized digital currency with a fixed supply of 21 million coins. Often called "digital gold"',
        'Ethereum (ETH): Second-largest crypto. A programmable blockchain supporting smart contracts, DeFi (Decentralized Finance), and NFTs',
        'Blockchain: Distributed ledger technology that records transactions across a network of computers. Immutable, transparent, and decentralized',
        'Crypto asset classes: Payment tokens (BTC, LTC), Platform tokens (ETH, SOL), Stablecoins (USDT, USDC — pegged to USD), DeFi tokens, NFTs',
        'Stablecoins: Cryptocurrencies pegged to fiat currencies. USDT, USDC, DAI. Used for trading, lending, and cross-border payments',
        'DeFi (Decentralized Finance): Financial services (lending, borrowing, trading, insurance) built on blockchain without intermediaries',
        'Crypto taxation in India: 30% flat tax on crypto gains (Section 115BBH). 1% TDS on transfers (Section 194S). No offset of losses against other income',
        'Crypto taxation in US: Treated as property by IRS. Short-term gains taxed as ordinary income. Long-term (held >1 year) taxed at capital gains rates',
        'Crypto exchanges: Centralized (Binance, Coinbase, WazirX, CoinDCX) vs. Decentralized (Uniswap, PancakeSwap). Centralized offers convenience; decentralized offers privacy',
        'Portfolio allocation: Most financial advisors recommend 1-5% crypto allocation for risk-tolerant investors. High volatility demands small position sizes',
        'Key risks: Extreme volatility (50%+ drawdowns common), regulatory uncertainty, exchange hacks, private key loss, scams and rug pulls',
        'Cold storage vs. hot wallets: Cold storage (hardware wallets like Ledger, Trezor) for long-term holding. Hot wallets (exchange, mobile) for trading',
      ],
    },
    {
      name: 'Derivatives — Options, Futures & Hedging',
      description: 'Understanding derivative instruments for hedging risk and speculative strategies.',
      details: [
        'Derivatives are financial contracts whose value is derived from an underlying asset (stocks, bonds, commodities, indices, currencies)',
        'Futures: Binding agreement to buy/sell an asset at a predetermined price on a future date. Used for hedging and speculation. Traded on exchanges (NSE F&O, CME)',
        'Options: Right (not obligation) to buy (Call) or sell (Put) an asset at a specified price (strike price) before/on expiration. Buyer pays a premium',
        'Call Option: Right to buy. Buy calls when you expect the price to rise. In-the-money when market price > strike price',
        'Put Option: Right to sell. Buy puts when you expect the price to fall or to protect existing holdings (protective put / portfolio insurance)',
        'Options pricing: Premium = Intrinsic Value + Time Value. Affected by: underlying price, strike, time to expiry, volatility (IV), interest rates, dividends',
        'Greeks: Delta (price sensitivity), Gamma (delta sensitivity), Theta (time decay), Vega (volatility sensitivity), Rho (interest rate sensitivity)',
        'Covered Call: Own the stock + sell a call option. Generates income but caps upside. Popular strategy for income investors',
        'Protective Put: Own the stock + buy a put option. Acts as insurance against downside. Cost is the put premium',
        'Hedging with futures: Lock in prices for commodities (gold, oil, crops), currencies (USD/INR for exporters/importers), or portfolio values (Nifty futures)',
        'Index derivatives in India: Nifty 50 Futures & Options are the most liquid instruments on NSE. Weekly expiry (Thursday). Lot size matters',
        'Currency derivatives: USD/INR, EUR/INR futures on NSE. Used by businesses to hedge foreign exchange exposure',
        'Commodity derivatives: MCX (Multi Commodity Exchange — India) trades gold, silver, crude oil, natural gas, agricultural commodities',
        'Risks: Leverage amplifies both gains and losses. Options can expire worthless (100% loss of premium). Futures have unlimited loss potential',
        'SEBI F&O regulations (India): Minimum lot sizes, margin requirements (SPAN + Exposure margin), position limits, no naked selling for retail without margin',
      ],
    },
  ],
  keyTerms: [
    { term: 'P/E Ratio', definition: 'Price-to-Earnings ratio. Stock price divided by earnings per share. Indicates how much investors pay per dollar of earnings.' },
    { term: 'Market Capitalization', definition: 'Total market value of a company\'s outstanding shares. Share price × total shares.' },
    { term: 'Dividend Yield', definition: 'Annual dividend per share divided by share price, expressed as a percentage.' },
    { term: 'NAV', definition: 'Net Asset Value. The per-unit value of a mutual fund, calculated as (total assets - liabilities) / outstanding units.' },
    { term: 'Expense Ratio', definition: 'Annual fee charged by a fund to cover management and operational costs, expressed as a percentage of assets.' },
    { term: 'Alpha', definition: 'Excess return of an investment relative to its benchmark. Positive alpha = outperformance.' },
    { term: 'Beta', definition: 'Measure of an investment\'s volatility relative to the market. Beta > 1 = more volatile than market.' },
    { term: 'Sharpe Ratio', definition: 'Risk-adjusted return metric: (Portfolio Return - Risk-Free Rate) / Portfolio Standard Deviation. Higher is better.' },
    { term: 'Yield to Maturity (YTM)', definition: 'Total return anticipated on a bond if held until maturity, accounting for coupon payments and price difference from par.' },
    { term: 'Duration', definition: 'A measure of a bond\'s price sensitivity to interest rate changes. Higher duration = more sensitivity.' },
    { term: 'Asset Allocation', definition: 'The strategy of dividing a portfolio among different asset classes (stocks, bonds, cash, alternatives) to balance risk and reward.' },
    { term: 'Rebalancing', definition: 'The process of realigning portfolio weights back to the target allocation by buying and selling assets.' },
    { term: 'Diversification', definition: 'Spreading investments across various asset classes, sectors, and geographies to reduce risk.' },
    { term: 'CAGR', definition: 'Compound Annual Growth Rate. The annualized rate of return that smooths out volatility over a period.' },
    { term: 'AUM', definition: 'Assets Under Management. Total market value of investments managed by a fund or institution.' },
  ],
  tips: [
    'Start investing as early as possible — time in the market is your greatest advantage due to compounding.',
    'Keep investment costs low — every 1% in fees reduces your final portfolio by ~25% over 30 years.',
    'Diversify broadly — no single stock, sector, or country should dominate your portfolio.',
    'Don\'t try to time the market — even professionals fail at this consistently.',
    'Invest regularly through SIPs/DCA regardless of market conditions.',
    'Understand what you invest in — if you can\'t explain it simply, don\'t invest in it.',
    'Review your portfolio quarterly but resist the urge to make frequent changes.',
    'Rebalance annually or when allocation drifts more than 5% from target.',
    'Historical average stock market return: ~10-12% nominal, ~7-8% real (after inflation) over long periods.',
    'Past performance does not guarantee future results — always evaluate based on fundamentals and strategy.',
  ],
  faqs: [
    {
      question: 'What is the difference between mutual funds and ETFs?',
      answer: 'Both are pooled investment vehicles offering diversification. Key differences: ETFs trade on exchanges throughout the day at market prices; mutual funds trade once at end-of-day NAV. ETFs generally have lower expense ratios. Mutual funds can be purchased in fractional amounts via SIP; ETFs require buying whole units. Mutual funds may have higher tax efficiency in India; ETFs are often more tax-efficient in the US. For most investors, both are excellent choices — pick based on cost, convenience, and available options.',
    },
    {
      question: 'How should a beginner start investing?',
      answer: 'Step 1: Complete financial prerequisites (emergency fund, high-interest debt paid off). Step 2: Determine your risk tolerance and time horizon. Step 3: Start with broad market index funds (Nifty 50/S&P 500 index fund or ETF). Step 4: Set up automatic monthly investments (SIP). Step 5: Learn about asset allocation and diversify as your portfolio grows. Step 6: Avoid individual stocks until you understand fundamental analysis. Start simple, start small, but start now.',
    },
    {
      question: 'What is a good asset allocation for a 30-year-old?',
      answer: 'A 30-year-old with a long time horizon (30+ years to retirement) can typically afford higher equity allocation. A common starting point: 70-80% equity (split across large-cap, mid-cap, and international), 15-25% fixed income (bonds, debt funds), 5-10% alternatives (gold, REITs). Adjust based on personal risk tolerance, job stability, and financial obligations. As you approach retirement, gradually shift toward more conservative allocations.',
    },
    {
      question: 'Should I invest in individual stocks or funds?',
      answer: 'For most people, index funds/ETFs are the better choice. Research shows that 80-90% of actively managed funds underperform their benchmark over 15+ years. Individual stock picking requires significant time, knowledge, and emotional discipline. A reasonable approach: Build a core portfolio with index funds (70-80%), then allocate a small portion (20-30%) to individual stocks if you have the interest and knowledge to research them properly.',
    },
  ],
};
