import type { EngineData } from '../types';

export const regulatoryComplianceEngine: EngineData = {
  category: 'regulatory-compliance',
  title: 'Regulatory & Compliance',
  description: 'Comprehensive guide to SEBI/SEC regulations, fiduciary duties, ethical standards, and financial industry compliance.',
  topics: [
    {
      name: 'Securities Regulation — India (SEBI)',
      description: 'Securities and Exchange Board of India — the primary regulator for securities markets in India.',
      details: [
        'SEBI was established in 1992 under the SEBI Act, 1992, to protect investor interests and regulate the securities market.',
        'SEBI regulates: Stock exchanges (BSE, NSE), mutual funds, portfolio managers, investment advisers, credit rating agencies, depositories.',
        'Mutual fund regulations: SEBI mandates expense ratio caps — 2.25% for equity funds (AUM ≤₹500Cr), scaling down for larger AUMs. Direct plans must be available.',
        'Investment Adviser Regulations (2013): Advisers must be registered with SEBI. Must have relevant qualifications (CFP, CFA, or NISM certifications). Fee-only model required — no commissions from product manufacturers.',
        'Insider Trading Regulations: Trading on unpublished price-sensitive information (UPSI) is prohibited. Connected persons have reporting obligations.',
        'SEBI LODR (Listing Obligations and Disclosure Requirements): Listed companies must disclose material events, financial results quarterly, shareholding patterns.',
        'KYC (Know Your Customer): Mandatory for all investment accounts. Requires PAN, Aadhaar, address proof, and photograph.',
        'Investor grievance redressal: SEBI SCORES portal for filing complaints against market intermediaries.',
        'Recent SEBI initiatives: Mutual fund lite regulations, social stock exchange, regulation of finfluencers, T+1 settlement cycle.',
      ],
    },
    {
      name: 'Securities Regulation — US (SEC)',
      description: 'Securities and Exchange Commission — the primary regulator for securities markets in the United States.',
      details: [
        'SEC was established in 1934 after the Great Depression to restore investor confidence. Enforces federal securities laws.',
        'Key laws: Securities Act of 1933 (registration of securities), Securities Exchange Act of 1934 (trading regulations), Investment Company Act of 1940, Investment Advisers Act of 1940.',
        'Registration requirements: Public companies must register securities. Investment advisers with >$100M AUM must register with SEC; smaller advisers register with state regulators.',
        'SEC filings: 10-K (annual report), 10-Q (quarterly report), 8-K (material events), 13-F (institutional holdings), Form 4 (insider transactions).',
        'FINRA (Financial Industry Regulatory Authority): Self-regulatory organization that oversees broker-dealers and their registered representatives in the US.',
        'Series 7 (General Securities Representative): Required to sell most securities (stocks, bonds, options, mutual funds). Administered by FINRA. 125 questions, 225 minutes.',
        'Series 65 (Uniform Investment Adviser Law): Required for Investment Adviser Representatives. Covers fiduciary duty, portfolio management, ethics. 130 questions, 180 minutes.',
        'Series 66 (Uniform Combined State Law): Combines Series 63 and Series 65. Required alongside Series 7 for dual-registered advisors.',
        'SIE (Securities Industry Essentials): Prerequisite exam before Series 7. Covers basic securities concepts. Open to anyone age 18+.',
        'FINRA BrokerCheck: Free tool to verify the registration and background of brokers and advisers. Check disciplinary history before hiring an advisor.',
        'FINRA arbitration and mediation: Dispute resolution for investor complaints against broker-dealers. Mandatory arbitration clause in most brokerage agreements.',
        'Regulation Best Interest (Reg BI): Broker-dealers must act in the best interest of retail customers when making recommendations.',
        'Sarbanes-Oxley Act (SOX, 2002): Enhanced corporate governance, financial disclosures, and accountability after Enron/WorldCom scandals.',
        'Dodd-Frank Act (2010): Comprehensive financial reform after the 2008 crisis. Created the Consumer Financial Protection Bureau (CFPB).',
        'Accredited investor: Individual with income >$200K ($300K joint) or net worth >$1M (excluding primary residence). Can access private placements.',
      ],
    },
    {
      name: 'Fiduciary Duty',
      description: 'The highest standard of care — acting in the client\'s best interest.',
      details: [
        'A fiduciary is legally and ethically obligated to act in the client\'s best interest, ahead of their own.',
        'Fiduciary duty includes: Duty of loyalty (no conflicts of interest), Duty of care (competent advice), Duty of good faith.',
        'In the US: Registered Investment Advisers (RIAs) have fiduciary duty. Broker-dealers have a "suitability" standard (lower) but now also Reg BI.',
        'In India: SEBI-registered Investment Advisers have fiduciary obligations. Mutual fund distributors follow a suitability standard.',
        'Fee-only advisers vs. commission-based: Fee-only advisers are less likely to have conflicts of interest as they earn from client fees only.',
        'Common conflicts of interest: Recommending higher-commission products, churning (excessive trading), front-running, self-dealing.',
        'Disclosure requirements: Advisers must disclose conflicts of interest, compensation structure, disciplinary history, and investment process.',
        'The fiduciary standard is considered the gold standard for financial advice. Always ask your adviser if they are a fiduciary.',
      ],
    },
    {
      name: 'Ethical Standards',
      description: 'Professional conduct standards for financial advisers and planners.',
      details: [
        'CFP Board Code of Ethics: Integrity, objectivity, competence, fairness, confidentiality, professionalism, diligence.',
        'CFA Institute Code: Place client interests first, act with integrity, maintain competence, respect confidentiality.',
        'Anti-Money Laundering (AML): Financial institutions must verify client identity, monitor transactions, report suspicious activity (STR/SAR).',
        'Suitability requirement: Recommendations must be appropriate for the client\'s financial situation, risk tolerance, and investment objectives.',
        'Best execution: Executing client trades at the most favorable terms reasonably available.',
        'Privacy regulations: Client financial information is protected under GLBA (US), IT Act Section 43A (India), GDPR (EU).',
        'Whistle-blower protections: SEC and SEBI provide protections and rewards for reporting securities law violations.',
        'Continuing education: Most financial certifications require ongoing education to maintain competence. CFP: 30 CE hours every 2 years.',
      ],
    },
    {
      name: 'Financial Certifications',
      description: 'Professional designations in the financial planning and investment industry.',
      details: [
        'CFP (Certified Financial Planner): Gold standard for financial planning. Requires education, exam, experience, and ethics requirements. Recognized globally.',
        'CFA (Chartered Financial Analyst): Premier designation for investment management. Three levels of exams covering economics, ethics, portfolio management, financial analysis.',
        'CA/CPA: Chartered Accountant (India) / Certified Public Accountant (US). Primary accounting and tax professional designation.',
        'NISM Certifications (India): Required for mutual fund distributors (Series V-A), research analysts (Series XV), investment advisers (Series X-A/X-B).',
        'FPSB India: Financial Planning Standards Board India administers CFP certification in India.',
        'ChFC (Chartered Financial Consultant): Advanced financial planning designation, more coursework than CFP.',
        'CLU (Chartered Life Underwriter): Specialization in life insurance and estate planning.',
        'CAIA (Chartered Alternative Investment Analyst): Specialization in alternative investments (hedge funds, private equity, real assets).',
      ],
    },
    {
      name: 'Investor Protection',
      description: 'Mechanisms and organizations that protect retail investors.',
      details: [
        'SIPC (Securities Investor Protection Corporation — US): Protects investors if a brokerage firm fails. Coverage: $500K per account ($250K cash limit).',
        'FDIC (Federal Deposit Insurance Corporation — US): Insures bank deposits up to $250,000 per depositor per bank.',
        'DICGC (Deposit Insurance and Credit Guarantee Corporation — India): Insures bank deposits up to ₹5 lakh per depositor per bank.',
        'Investor Education and Protection Fund (IEPF — India): Protects investors and promotes financial literacy.',
        'Ombudsman: SEBI, RBI, and IRDAI have ombudsman mechanisms for grievance redressal.',
        'Investor rights: Right to full disclosure, right to fair treatment, right to privacy, right to grievance redressal, right to a fair market.',
        'Red flags of financial fraud: Guaranteed high returns, pressure to invest quickly, unregistered advisers/products, complex structures you don\'t understand.',
        'Due diligence: Always verify registration of advisers/brokers with SEBI/SEC, check disciplinary records, read all documents before investing.',
      ],
    },
  ],
  keyTerms: [
    { term: 'SEBI', definition: 'Securities and Exchange Board of India. The regulatory body for securities markets in India, established in 1992.' },
    { term: 'SEC', definition: 'Securities and Exchange Commission. The primary federal securities regulator in the United States.' },
    { term: 'Fiduciary', definition: 'A person or entity legally obligated to act in the best interest of another party, placing client interests above their own.' },
    { term: 'KYC', definition: 'Know Your Customer. Mandatory identity verification process required for opening financial accounts.' },
    { term: 'AML', definition: 'Anti-Money Laundering. Laws and procedures to prevent the generation of income through illegal actions.' },
    { term: 'Insider Trading', definition: 'Illegal practice of trading securities based on material, non-public information.' },
    { term: 'Accredited Investor', definition: 'An individual or entity meeting certain income or net worth thresholds, eligible to invest in unregistered securities.' },
    { term: 'Suitability', definition: 'Standard requiring that investment recommendations be appropriate for the client\'s financial situation and objectives.' },
    { term: 'Prospectus', definition: 'Legal document providing details about an investment offering, including risks, strategy, fees, and management.' },
    { term: 'NAV', definition: 'Net Asset Value. Per-unit value of a mutual fund calculated as (total assets - liabilities) / outstanding units.' },
    { term: 'SCORES', definition: 'SEBI Complaints Redress System. Online platform for investors to file complaints against market intermediaries in India.' },
  ],
  tips: [
    'Always verify your financial adviser\'s registration with SEBI (India) or SEC/FINRA (US) before engaging their services.',
    'Ask your adviser: "Are you a fiduciary?" and "How are you compensated?" — these two questions reveal potential conflicts.',
    'Read the scheme information document (SID) and key information memorandum (KIM) before investing in any mutual fund.',
    'File complaints through official channels: SEBI SCORES, FINRA BrokerCheck, CFPB — not just social media.',
    'Keep records of all financial transactions, adviser communications, and investment documents for at least 7 years.',
    'Understand the difference between a financial adviser (registered, regulated) and a financial influencer (unregulated, may have hidden incentives).',
    'Never invest in unregistered schemes or with unregistered advisers, regardless of promised returns.',
    'Review your adviser\'s Form ADV (US) or SEBI registration details to understand their business, fees, and conflicts.',
  ],
  faqs: [
    {
      question: 'What is the difference between a fiduciary and a suitability standard?',
      answer: 'A fiduciary must act in your BEST interest — recommending what\'s optimal for you. A suitability standard only requires that recommendations be SUITABLE — not necessarily the best option. Example: A fiduciary must recommend the lowest-cost index fund if it\'s best for you. Under suitability, recommending a higher-cost fund that\'s still "suitable" for your risk profile is permissible, even if a better option exists. In practice, this means fiduciary advisers (RIAs) generally offer more aligned advice than broker-dealers operating under suitability.',
    },
    {
      question: 'How do I check if a financial adviser is registered?',
      answer: 'In India: Search on SEBI\'s website under "Intermediary/Market Infrastructure Institutions" for registered Investment Advisers. Check AMFI website for mutual fund distributors. In the US: Use FINRA BrokerCheck (brokercheck.finra.org) for broker-dealers and SEC\'s IAPD (adviserinfo.sec.gov) for investment advisers. These databases show registration status, qualifications, employment history, and any disciplinary actions.',
    },
    {
      question: 'What should I do if I suspect investment fraud?',
      answer: 'Step 1: Stop all further transactions with the suspected entity. Step 2: Gather all documentation — account statements, communications, transaction records. Step 3: File a complaint with the regulator — SEBI SCORES (India), SEC/FINRA (US). Step 4: File a police complaint if criminal fraud is suspected. Step 5: Consult a securities lawyer for potential civil recovery. Step 6: Report to the Economic Offences Wing (India) or FBI (US) for serious fraud. Act quickly — recovery chances decrease with time.',
    },
    {
      question: 'What are the key SEBI regulations every Indian investor should know?',
      answer: 'Key regulations: 1) Mutual Fund Regulations — expense ratio caps, mandatory direct plans, standardized risk-o-meter. 2) Investment Adviser Regulations — advisers must be SEBI-registered, fee-only model required. 3) Insider Trading Regulations — trading on unpublished price-sensitive information is prohibited. 4) LODR — listed companies must disclose material information promptly. 5) PMS Regulations — minimum investment ₹50 lakh for Portfolio Management Services. 6) AIF Regulations — minimum ₹1 crore for Alternative Investment Funds. Understanding these helps you identify legitimate products and advisers.',
    },
  ],
};
