import type { EngineData } from '../types';

export const retirementPlanningEngine: EngineData = {
  category: 'retirement-planning',
  title: 'Retirement Planning',
  description: 'Comprehensive guide to pension plans, retirement accounts (401(k), PPF, NPS, IRA), withdrawal strategies, and retirement income planning.',
  topics: [
    {
      name: 'Retirement Planning Basics',
      description: 'Fundamental concepts for planning a financially secure retirement.',
      details: [
        'Retirement planning involves determining retirement income goals and the actions needed to achieve them.',
        'Key variables: Current age, desired retirement age, life expectancy, current savings, expected returns, inflation rate, desired retirement lifestyle.',
        'The 4% rule (Trinity Study): You can withdraw 4% of your portfolio in the first year of retirement, adjusting for inflation annually, with a high probability of not running out of money over 30 years.',
        'Replacement ratio: Most retirees need 70-80% of pre-retirement income to maintain their lifestyle. This varies based on lifestyle choices and health costs.',
        'Three-legged stool of retirement: Government benefits (Social Security/pension), employer-sponsored plans, personal savings/investments.',
        'Start early: Starting at 25 vs. 35 can result in nearly double the retirement corpus due to compounding.',
        'Rule of 25: To retire, you need 25 times your annual expenses saved (inverse of the 4% rule).',
        'Account for inflation: At 6% inflation, ₹1 lakh today equals ₹3.2 lakh in 20 years. At 3% inflation, $100K equals $181K in 20 years.',
        'Healthcare costs in retirement are often underestimated — plan for increasing medical expenses with age.',
      ],
    },
    {
      name: 'US Retirement Accounts',
      description: 'Tax-advantaged retirement savings vehicles available in the United States.',
      details: [
        '401(k): Employer-sponsored plan. 2024 contribution limit: $23,000 ($30,500 for 50+). Pre-tax contributions reduce taxable income.',
        'Roth 401(k): After-tax contributions, tax-free withdrawals in retirement. Same contribution limits as traditional 401(k).',
        'Traditional IRA: Individual Retirement Account. 2024 limit: $7,000 ($8,000 for 50+). Contributions may be tax-deductible.',
        'Roth IRA: After-tax contributions, tax-free growth and withdrawals. 2024 limit: $7,000 ($8,000 for 50+). Income limits apply.',
        '403(b): Similar to 401(k) but for non-profit and government employees.',
        '457(b): Deferred compensation plan for government employees. No early withdrawal penalty.',
        'SEP IRA: For self-employed individuals. 2024 limit: 25% of net self-employment income, up to $69,000.',
        'Solo 401(k): For self-employed with no employees. Allows both employee and employer contributions.',
        'HSA (Health Savings Account): Triple tax advantage — deductible contributions, tax-free growth, tax-free withdrawals for medical expenses. After 65, can be used for any purpose.',
        'Required Minimum Distributions (RMDs): Must begin at age 73 (as of SECURE 2.0 Act) for traditional accounts. Roth IRAs have no RMDs.',
      ],
      subtopics: [
        {
          name: 'Roth vs. Traditional',
          description: 'Choosing between pre-tax and after-tax retirement contributions.',
          details: [
            'Traditional: Tax deduction now, pay taxes on withdrawals in retirement. Best if you expect to be in a lower tax bracket in retirement.',
            'Roth: Pay taxes now, tax-free withdrawals in retirement. Best if you expect to be in the same or higher tax bracket in retirement.',
            'Young professionals often benefit more from Roth — lower current income means lower tax rate on contributions.',
            'Tax diversification: Having both Roth and traditional accounts gives flexibility to manage tax liability in retirement.',
            'Roth conversion (backdoor Roth): Converting traditional IRA/401(k) to Roth, paying taxes on the converted amount now for tax-free growth later.',
          ],
        },
      ],
    },
    {
      name: 'Indian Retirement Accounts',
      description: 'Retirement savings options available in India.',
      details: [
        'EPF (Employee Provident Fund): Mandatory for salaried employees. Employee contributes 12% of basic + DA, employer matches. Current interest rate: ~8.15%. Tax-free if held 5+ years.',
        'PPF (Public Provident Fund): Government-backed savings scheme. Lock-in: 15 years (partial withdrawal after 7 years). Current rate: ~7.1%. Maximum investment: ₹1.5 lakh/year. EEE tax status (Exempt-Exempt-Exempt).',
        'NPS (National Pension System): Market-linked retirement scheme. Two tiers: Tier I (retirement, lock-in till 60) and Tier II (voluntary, no lock-in). Tax benefits under 80CCD(1), 80CCD(1B) (additional ₹50,000), 80CCD(2) (employer contribution).',
        'Superannuation Fund: Employer-sponsored retirement benefit. Employer contributes up to 15% of basic salary.',
        'Gratuity: Employer pays 15 days\' salary for each completed year of service (after 5 years). Exempt up to ₹20 lakh.',
        'VPF (Voluntary Provident Fund): Additional voluntary EPF contribution up to 100% of basic salary at the same EPF interest rate.',
        'Senior Citizens Savings Scheme (SCSS): For 60+ individuals. Current rate: ~8.2%. Max deposit: ₹30 lakh. 5-year tenure.',
        'Atal Pension Yojana: Government pension scheme for unorganized sector. Fixed monthly pension of ₹1,000-5,000 after age 60.',
        'POMIS (Post Office Monthly Income Scheme): Fixed monthly income. Current rate: ~7.4%. Max deposit: ₹9 lakh (individual), ₹15 lakh (joint).',
      ],
    },
    {
      name: 'Pension Plans',
      description: 'Employer or government-provided retirement income plans.',
      details: [
        'Defined Benefit (DB) Plan: Employer guarantees a specific monthly benefit at retirement based on salary and years of service. Employer bears investment risk.',
        'Defined Contribution (DC) Plan: Employer and/or employee contribute to individual accounts. Retirement benefit depends on contributions and investment returns. Employee bears investment risk.',
        'DB plans are becoming rare in the private sector globally. Most new plans are DC-type (401(k), EPF, NPS).',
        'Social Security (US): Government retirement benefit based on 35 highest-earning years. Full retirement age: 67 (for those born 1960+). Can claim early at 62 (reduced) or delay until 70 (increased).',
        'UK State Pension: Based on National Insurance contributions. Full new State Pension: £203.85/week (2024-25). Need 35 qualifying years.',
        'In India, government employees get pension under Old Pension Scheme (OPS) or NPS depending on joining date.',
        'Pension annuity: Converting a lump sum into guaranteed periodic payments for life. Options: Life only, joint and survivor, period certain.',
      ],
    },
    {
      name: 'Withdrawal Strategies',
      description: 'Methods for drawing down retirement savings to ensure they last a lifetime.',
      details: [
        'The 4% Rule: Withdraw 4% of portfolio in year 1, then adjust for inflation annually. Based on 50/50 stock/bond portfolio.',
        'Variable percentage withdrawal: Adjust withdrawal rate based on portfolio performance. Withdraw more in good years, less in bad years.',
        'Bucket strategy: Divide portfolio into short-term (1-3 years in cash/bonds), medium-term (3-10 years in balanced), and long-term (10+ years in equity) buckets.',
        'Guardrails strategy: Set upper and lower limits on withdrawals. If portfolio grows significantly, increase spending; if it drops, reduce spending.',
        'Tax-efficient withdrawal order: Draw from taxable accounts first, then tax-deferred (traditional IRA/401k), then tax-free (Roth). This maximizes tax-free growth time.',
        'Required Minimum Distributions (US): Must withdraw minimum amounts from traditional retirement accounts starting at age 73.',
        'Systematic Withdrawal Plan (SWP) in India: Regular withdrawals from mutual funds. More tax-efficient than fixed deposits for retirees.',
        'Annuitization: Converting a portion of savings into a lifetime annuity for guaranteed income to cover essential expenses.',
        'Sequence of returns risk: Poor market returns in early retirement years can devastate a portfolio even if average returns are good. Mitigate with lower initial withdrawal rate or bucket strategy.',
      ],
    },
    {
      name: 'FIRE Movement',
      description: 'Financial Independence, Retire Early — achieving financial freedom well before traditional retirement age.',
      details: [
        'FIRE = Financial Independence, Retire Early. Goal is to accumulate enough wealth to live off investment income.',
        'FIRE number: Annual expenses × 25 (based on the 4% rule). Example: ₹6 lakh/year expenses → ₹1.5 crore FIRE number.',
        'Savings rate is the primary driver: 50% savings rate → ~17 years to FIRE. 70% savings rate → ~8.5 years.',
        'Lean FIRE: Achieving financial independence on a very frugal budget. Lower FIRE number, more restrictive lifestyle.',
        'Fat FIRE: Financial independence with a generous budget allowing for a comfortable lifestyle. Higher FIRE number needed.',
        'Barista FIRE/Coast FIRE: Having enough invested that compounding will fund traditional retirement; working part-time for current expenses.',
        'FIRE withdrawal: Many FIRE practitioners use 3-3.5% withdrawal rate for added safety over longer retirement periods.',
        'Challenges: Healthcare coverage before Medicare/government health benefits, lifestyle inflation, sequence of returns risk over very long retirement.',
      ],
    },
  ],
  keyTerms: [
    { term: '401(k)', definition: 'US employer-sponsored retirement plan allowing pre-tax or Roth contributions with potential employer matching.' },
    { term: 'IRA', definition: 'Individual Retirement Account. Tax-advantaged personal retirement savings account (Traditional or Roth).' },
    { term: 'PPF', definition: 'Public Provident Fund. Indian government-backed 15-year savings scheme with tax-free returns.' },
    { term: 'NPS', definition: 'National Pension System. Indian market-linked retirement scheme with tax benefits and partial annuitization at retirement.' },
    { term: 'EPF', definition: 'Employee Provident Fund. Mandatory Indian retirement savings for salaried employees with employer matching.' },
    { term: 'RMD', definition: 'Required Minimum Distribution. Mandatory annual withdrawals from US tax-deferred retirement accounts starting at age 73.' },
    { term: 'Annuity', definition: 'Financial product that provides guaranteed periodic payments, typically used for retirement income.' },
    { term: 'Vesting', definition: 'The process by which an employee earns the right to employer-contributed retirement benefits over time.' },
    { term: 'FIRE', definition: 'Financial Independence, Retire Early. Movement focused on high savings rates and investment to achieve early retirement.' },
    { term: '4% Rule', definition: 'Guideline suggesting withdrawing 4% of retirement portfolio in year one (inflation-adjusted thereafter) provides a high probability of lasting 30 years.' },
    { term: 'Replacement Ratio', definition: 'The percentage of pre-retirement income needed to maintain the same standard of living in retirement, typically 70-80%.' },
    { term: 'Sequence of Returns Risk', definition: 'The risk that poor investment returns early in retirement can permanently impair a portfolio even if long-term average returns are acceptable.' },
  ],
  tips: [
    'Start saving for retirement in your 20s — even small amounts grow enormously over 30-40 years.',
    'Always maximize employer matching in retirement plans — it\'s a 50-100% immediate return on your contribution.',
    'Increase retirement contributions by 1% each year or with every raise.',
    'Don\'t withdraw from retirement accounts early — penalties and lost compounding are devastating.',
    'Plan for 30+ years of retirement — longevity risk is real, especially for women.',
    'Include healthcare costs in retirement planning — they often increase significantly after 60.',
    'Consider tax diversification: Have money in pre-tax, after-tax, and tax-free accounts.',
    'Review your retirement plan annually and adjust contributions, allocation, and targets as needed.',
    'Don\'t rely solely on government benefits (Social Security/pension) — they may cover only 30-40% of needs.',
    'Delay claiming Social Security/pension until later for higher monthly benefits if possible.',
  ],
  faqs: [
    {
      question: 'How much do I need to retire?',
      answer: 'Use the Rule of 25: Multiply your expected annual retirement expenses by 25. For example, if you need ₹50,000/month (₹6 lakh/year), you need approximately ₹1.5 crore. In the US, if you need $50,000/year, you need ~$1.25 million. Adjust for inflation if retirement is many years away. This assumes a 4% withdrawal rate. For early retirement (FIRE), some use a more conservative 3-3.5% rule, requiring 28-33 times annual expenses.',
    },
    {
      question: 'PPF vs NPS — which is better for retirement?',
      answer: 'PPF: Guaranteed returns (~7.1%), fully tax-free (EEE status), no market risk, 15-year lock-in. Best for conservative investors and guaranteed returns. NPS: Market-linked returns (historically 9-12% for equity option), additional ₹50,000 tax deduction under 80CCD(1B), but 40% must be annuitized at retirement. Best for those comfortable with market risk and wanting higher returns. Ideal approach: Use both — PPF for guaranteed debt component, NPS for equity exposure and additional tax benefits.',
    },
    {
      question: 'At what age should I start retirement planning?',
      answer: 'Immediately, regardless of age. If you start at 25, investing ₹5,000/month at 12% returns gives you ~₹3.2 crore by age 60. The same amount starting at 35 gives only ~₹95 lakh — less than one-third. The power of compounding makes early starting exponentially more valuable than starting late with larger amounts. Even as a student, understanding retirement concepts prepares you to act immediately upon earning.',
    },
  ],
};
