import type { EngineData } from '../types';

export const taxPlanningEngine: EngineData = {
  category: 'tax-planning',
  title: 'Tax Planning',
  description: 'Comprehensive guide to income tax, capital gains, tax-efficient investing, estate/gift tax, and tax optimization strategies.',
  topics: [
    {
      name: 'Income Tax Fundamentals',
      description: 'Understanding how income is taxed and strategies to minimize tax liability legally.',
      details: [
        'Income tax is a progressive tax — higher income is taxed at higher rates through a bracket system.',
        'Marginal tax rate: The rate applied to the last dollar/rupee of income. Different from effective (average) tax rate.',
        'Effective tax rate: Total tax paid ÷ Total taxable income. Always lower than the highest marginal rate.',
        'Taxable income = Gross income - Deductions (standard or itemized) - Exemptions.',
        'Types of income: Earned income (salary, wages), business income, capital gains, interest, dividends, rental income.',
        'Tax planning is legal optimization of tax liability. Tax evasion (hiding income) is illegal.',
        'Tax year in the US: January-December. In India: April 1 - March 31.',
        'Filing deadlines: US (April 15), India (July 31 for individuals, October 31 for audited).',
      ],
      subtopics: [
        {
          name: 'US Federal Income Tax Brackets (2024)',
          description: 'Progressive tax brackets for US individual filers.',
          details: [
            '10%: Up to $11,600 (single) / $23,200 (married filing jointly)',
            '12%: $11,601 - $47,150 / $23,201 - $94,300',
            '22%: $47,151 - $100,525 / $94,301 - $201,050',
            '24%: $100,526 - $191,950 / $201,051 - $383,900',
            '32%: $191,951 - $243,725 / $383,901 - $487,450',
            '35%: $243,726 - $609,350 / $487,451 - $731,200',
            '37%: Over $609,350 / Over $731,200',
            'Standard deduction (2024): $14,600 (single), $29,200 (married filing jointly), $21,900 (head of household).',
          ],
        },
        {
          name: 'India Income Tax — New Regime (FY 2024-25)',
          description: 'Simplified tax regime with lower rates but fewer deductions.',
          details: [
            'Up to ₹3,00,000: Nil',
            '₹3,00,001 - ₹7,00,000: 5%',
            '₹7,00,001 - ₹10,00,000: 10%',
            '₹10,00,001 - ₹12,00,000: 15%',
            '₹12,00,001 - ₹15,00,000: 20%',
            'Above ₹15,00,000: 30%',
            'Standard deduction of ₹75,000 for salaried individuals.',
            'Rebate under 87A: No tax up to ₹7 lakh taxable income.',
            'Surcharge: 10% (₹50L-1Cr), 15% (₹1-2Cr), 25% (₹2-5Cr), applicable on high incomes.',
          ],
        },
        {
          name: 'India Income Tax — Old Regime Deductions',
          description: 'Key deductions available under the old tax regime.',
          details: [
            'Section 80C: Up to ₹1.5 lakh for PPF, ELSS, life insurance, EPF, tuition fees, home loan principal.',
            'Section 80D: Health insurance premiums — ₹25,000 (self/family), additional ₹25,000-50,000 (parents).',
            'Section 80CCD(1B): Additional ₹50,000 for NPS contribution.',
            'Section 80E: Interest on education loan (no upper limit, up to 8 years).',
            'Section 80G: Donations to specified funds/charities (50% or 100% deduction).',
            'Section 80TTA/80TTB: Interest on savings accounts (₹10,000 for <60, ₹50,000 for 60+).',
            'Section 24(b): Home loan interest up to ₹2 lakh for self-occupied property.',
            'HRA exemption: For salaried individuals paying rent, based on a formula involving salary, rent paid, and city.',
          ],
        },
      ],
    },
    {
      name: 'Capital Gains Tax',
      description: 'Tax on profits from selling investments and capital assets.',
      details: [
        'Capital gain = Sale price - Purchase price - Transaction costs. Taxed differently based on holding period.',
        'US Short-term capital gains (held ≤1 year): Taxed as ordinary income (10-37%).',
        'US Long-term capital gains (held >1 year): Taxed at 0%, 15%, or 20% depending on income.',
        'India — Equity (listed): STCG (held <1 year): 20%. LTCG (held >1 year): 12.5% on gains exceeding ₹1.25 lakh. (Updated as per Budget 2024)',
        'India — Debt funds: Gains taxed at slab rate regardless of holding period (post April 2023 change for new purchases).',
        'India — Real estate: LTCG (held >2 years): 12.5% without indexation. STCG: At slab rate.',
        'Tax-loss harvesting: Selling losing investments to offset capital gains, then reinvesting. Wash sale rules apply (30 days in US).',
        'Step-up in basis (US): Inherited assets get a cost basis equal to fair market value at date of death — eliminates unrealized gains.',
        'Indexation (India — old rules): Adjusting purchase price for inflation using CII (Cost Inflation Index) to reduce taxable LTCG. Removed for most assets from July 2024.',
      ],
    },
    {
      name: 'Tax-Efficient Investing',
      description: 'Strategies to minimize the tax impact on investment returns.',
      details: [
        'Asset location: Place tax-inefficient investments (bonds, REITs) in tax-advantaged accounts; tax-efficient investments (index funds, ETFs) in taxable accounts.',
        'Hold investments for long-term to qualify for lower long-term capital gains rates.',
        'Use tax-advantaged accounts to the maximum: 401(k), IRA, PPF, NPS, ELSS.',
        'Index funds and ETFs are more tax-efficient than actively managed funds due to lower turnover.',
        'Tax-loss harvesting: Systematically realizing losses to offset gains. Can offset up to $3,000 of ordinary income annually in the US.',
        'Qualified dividends (US) are taxed at LTCG rates (0-20%). Non-qualified dividends taxed as ordinary income.',
        'In India, dividends are taxable at slab rate. Equity fund dividends are less tax-efficient than growth option.',
        'Growth option in mutual funds defers tax until redemption; dividend option creates periodic tax liability.',
        'Municipal bonds (US) offer tax-free interest income at the federal level and sometimes state level.',
        'Roth conversions in low-income years can lock in low tax rates for future tax-free growth.',
      ],
    },
    {
      name: 'Estate & Gift Tax',
      description: 'Taxes on wealth transfer during life (gifts) and at death (estate tax).',
      details: [
        'US Federal Estate Tax: Applies to estates exceeding $13.61 million (2024). Tax rate: 18-40% on amounts above exemption.',
        'US Gift Tax: Annual exclusion of $18,000 per recipient (2024). Gifts above this count against lifetime exemption.',
        'India: No inheritance tax or estate duty currently. However, income from inherited assets is taxable.',
        'India Gift Tax: Gifts exceeding ₹50,000 from non-relatives are taxable as income of the recipient.',
        'Exemptions in India: Gifts from relatives (as defined in IT Act), on occasion of marriage, by will/inheritance are exempt.',
        'UK Inheritance Tax: 40% on estates above £325,000. Residence nil-rate band: additional £175,000 for homes left to direct descendants.',
        'Trusts can be used to minimize estate/gift tax exposure and control wealth distribution.',
        'Life insurance proceeds are generally tax-free to beneficiaries but may be included in the estate for estate tax purposes.',
        'Charitable giving reduces estate size and provides income tax deductions during life.',
      ],
    },
    {
      name: 'Tax Planning Strategies',
      description: 'Legal methods to reduce overall tax burden.',
      details: [
        'Maximize all available deductions and credits before exploring advanced strategies.',
        'Tax-deferred growth: Retirement accounts allow investments to grow without annual tax drag.',
        'Income splitting: Distributing income among family members in lower tax brackets (where legal).',
        'Timing income and deductions: Accelerating deductions or deferring income to manage bracket exposure.',
        'Charitable strategies: Donor-advised funds, qualified charitable distributions from IRA (US), 80G donations (India).',
        'Section 80C planning (India): Maximize the ₹1.5 lakh deduction through EPF, PPF, ELSS, insurance, etc.',
        'Health Savings Account (US): Triple tax benefit — deductible contributions, tax-free growth, tax-free withdrawals for medical.',
        'Capital gains planning: Harvest losses, hold for long-term rates, use exemptions (like ₹1.25 lakh LTCG exemption in India).',
        'Business deductions: Home office, vehicle, equipment, education — all legal deductions for self-employed/business owners.',
        'Advance tax planning: Estimate income throughout the year to avoid penalties for under-withholding.',
      ],
    },
  ],
  keyTerms: [
    { term: 'Marginal Tax Rate', definition: 'The tax rate applied to the last dollar/rupee of taxable income. It represents the rate on the next unit of income earned.' },
    { term: 'Effective Tax Rate', definition: 'Total tax paid divided by total taxable income. Represents the average rate paid across all brackets.' },
    { term: 'Standard Deduction', definition: 'A flat deduction amount that reduces taxable income, available to all taxpayers who don\'t itemize.' },
    { term: 'Capital Gains', definition: 'Profit from selling a capital asset (stocks, property, etc.). Classified as short-term or long-term based on holding period.' },
    { term: 'Tax-Loss Harvesting', definition: 'Selling investments at a loss to offset capital gains and reduce tax liability.' },
    { term: 'Section 80C', definition: 'Indian Income Tax Act provision allowing deduction of up to ₹1.5 lakh for specified investments and expenses.' },
    { term: 'LTCG / STCG', definition: 'Long-Term Capital Gains / Short-Term Capital Gains. Tax rates differ based on asset type and holding period.' },
    { term: 'Indexation', definition: 'Adjusting purchase price of assets for inflation to calculate real capital gains, reducing tax liability.' },
    { term: 'TDS', definition: 'Tax Deducted at Source. Tax collected by the payer at the time of payment (salary, interest, rent, etc.) in India.' },
    { term: 'Advance Tax', definition: 'Tax paid in installments during the financial year instead of a lump sum at year-end. Required when tax liability exceeds ₹10,000 / applicable thresholds.' },
  ],
  tips: [
    'Plan taxes at the beginning of the financial year, not at the end — last-minute tax saving often leads to poor investment choices.',
    'In India, compare old vs. new tax regime annually to choose the more beneficial option.',
    'Keep all investment and expense proofs organized throughout the year — don\'t scramble at filing time.',
    'Use the full ₹1.5 lakh Section 80C limit (India) — ELSS gives both tax savings and market-linked returns.',
    'In the US, contribute to HSA if eligible — it\'s the only account with triple tax benefits.',
    'Tax-loss harvest systematically at year-end in taxable accounts.',
    'Don\'t let tax tail wag the investment dog — a good investment with some tax is better than a bad one with no tax.',
    'Consider Roth conversions in years with lower income (US).',
    'Consult a qualified tax professional for complex situations — the cost is often recovered in tax savings.',
    'File returns on time to avoid penalties, interest, and loss of refund processing speed.',
  ],
  faqs: [
    {
      question: 'Old regime vs. new regime in India — which should I choose?',
      answer: 'Choose old regime if your total deductions (80C, 80D, HRA, home loan interest, NPS) exceed approximately ₹3.75 lakh. Choose new regime if your deductions are minimal. Key comparison: New regime has lower rates but almost no deductions. Old regime has higher rates but allows deductions that can significantly reduce taxable income. Calculate your tax under both regimes annually — the better option depends on your specific deductions and income level.',
    },
    {
      question: 'How is equity LTCG taxed in India?',
      answer: 'As per Budget 2024 updates: Long-term capital gains on listed equity shares and equity mutual funds (held >12 months) are taxed at 12.5% on gains exceeding ₹1.25 lakh per financial year. Short-term capital gains (held <12 months) are taxed at 20%. Securities Transaction Tax (STT) is applicable on equity transactions. Tax-saving tip: Harvest gains up to ₹1.25 lakh annually tax-free by selling and repurchasing equity investments.',
    },
    {
      question: 'What is tax-loss harvesting and how does it work?',
      answer: 'Tax-loss harvesting involves selling investments that are at a loss to offset gains from other investments, reducing your overall tax liability. Example: You have ₹2 lakh profit from Fund A and ₹80,000 loss in Fund B. Selling Fund B crystallizes the loss, reducing your taxable gain to ₹1.2 lakh. You can then reinvest in a similar (not identical) fund. In the US, wash sale rules prevent buying a "substantially identical" security within 30 days before/after the sale. India does not have wash sale rules currently.',
    },
  ],
};
